#!/usr/bin/env zsh
[[ "$DOTFILES_MODE" != "ultra-nerd" ]] && return 0
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias home='cd ~'
alias dl='cd ~/Downloads'
alias docs='cd ~/Documents'
if command -v ranger >/dev/null 2>&1; then
    alias r='ranger'
fi
if command -v nnn >/dev/null 2>&1; then
    alias n='nnn'
fi
alias v='vim'
alias sv='sudo vim'
alias gst='git status'
alias gpl='git pull'
alias gps='git push'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gc='git commit'
alias gcm='git commit -m'
alias d='docker'
alias dc='docker-compose'
alias dps='docker ps'
alias di='docker images'
alias dex='docker exec -it'
alias update='sudo apt update && sudo apt upgrade -y'
alias upgrade='update'
alias cleanup='sudo apt autoremove -y'
alias ping='ping -c 5'
alias fastping='ping -c 100 -s.2'
alias psg='ps aux | grep -v grep | grep -i'
alias h='history'
alias hg='history | grep'
alias bconf='$EDITOR ~/.zshrc'
alias szrc='source ~/.zshrc'
alias reload='source ~/.zshrc'
