#!/bin/bash

LAYOUT=$(hyprctl -j getoption general:layout | jq -r '.str')

case $LAYOUT in
  master)
    hyprctl keyword general:layout dwindle
    hyprctl keyword unbind SUPER,J
    hyprctl keyword unbind SUPER,K
    hyprctl keyword bind SUPER,J,layoutmsg,cyclenext
    hyprctl keyword bind SUPER,K,layoutmsg,cycleprev
    notify-send -u low "Dwindle Layout"
    ;;
  dwindle)
    hyprctl keyword general:layout master
    hyprctl keyword unbind SUPER,J
    hyprctl keyword unbind SUPER,K
    hyprctl keyword unbind SUPER,O
    hyprctl keyword bind SUPER,J,cyclenext
    hyprctl keyword bind SUPER,K,cycleprev,prev
    notify-send -u low "Master Layout"
    ;;
esac
