#!/bin/bash

STATUS_FILE="/tmp/touchpad.status"

toggle() {
  if [[ -f "$STATUS_FILE" ]] && [[ $(cat "$STATUS_FILE") = "on" ]]; then
    hyprctl keyword "device:syna3067:00-06cb:8265-touchpad:enabled" false
    hyprctl keyword "device:synps/2-synaptics-touchpad:enabled" false
    printf "off" > "$STATUS_FILE"
    notify-send -u low -i "touchpad-disabled" "Touchpad Disabled"
  else
    hyprctl keyword "device:syna3067:00-06cb:8265-touchpad:enabled" true
    hyprctl keyword "device:synps/2-synaptics-touchpad:enabled" true
    printf "on" > "$STATUS_FILE"
    notify-send -u low -i "touchpad" "Touchpad Enabled"
  fi
}

toggle
