alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias a='cd ..'
alias aa='cd ../..'
alias aaa='cd ../../..'
alias aaaa='cd ../../../..'
alias aaaaa='cd ../../../..'
alias home='cd ~'
alias dots='cd "$DOTFILES_DIR"'
alias dotfiles='cd "$DOTFILES_DIR"'
alias dotst='git -C "$DOTFILES_DIR" status --short --branch'
alias edots='$EDITOR "$DOTFILES_DIR"'
alias docs='cd ~/Documents'
alias dt='cd ~/Desktop'
alias tmp='cd /tmp'
alias root='cd /'
alias bk='cd -'
alias x='exit'
alias c='clear'
alias cls='clear'
alias lsa='ls -a'
alias lsd='ls -d */'
alias lsdot='ls -d .*'
alias lsf='ls -p | grep -v /'
alias lsbig='ls -lS | head -20'
alias lshidden='ls -d .* 2>/dev/null'
alias ltree='eza --tree --level=3 --icons=auto 2>/dev/null || find . -maxdepth 3 -print'
alias l1='ls -1'
alias lh='ls -lhS'
alias lr='ls -lR'
alias duh='du -sh'
alias dfh='df -h'
alias freeh='free -h'
alias h='history'
alias j='jobs -l'
alias clr='clear'
alias please='sudo'
alias pathlines='printf "%s\n" ${PATH//:/\\n}'
alias mkdirp='mkdir -p'
alias focus='printf "\033c" && date +"%F %T"'
alias dotupdate='bash "$DOTFILES_DIR/bin/dotupdate.sh"'
alias dothealth='bash "$DOTFILES_DIR/bin/health_check.sh"'
alias dotbench='bash "$DOTFILES_DIR/bin/benchmark_shell.sh"'
alias dotfix='sh "$DOTFILES_DIR/install/install.sh"'
alias dotloadfull='. "$DOTFILES_DIR/core/aliases.sh" && . "$DOTFILES_DIR/core/functions.sh"'
alias dotbranch='git -C "$DOTFILES_DIR" branch'
alias dotdiff='git -C "$DOTFILES_DIR" diff'
alias dotdocs='xdg-open "$DOTFILES_DIR/docs/index.html" 2>/dev/null || open "$DOTFILES_DIR/docs/index.html" 2>/dev/null'
alias dotfetch='git -C "$DOTFILES_DIR" fetch --all --prune'
alias dothelp='echo "Pinak'\''s Dotfiles v$DOTFILES_VERSION — see dotdocs for docs"'
alias dotlog='git -C "$DOTFILES_DIR" log --oneline --graph --decorate -20'
alias dotmode='echo "$DOTFILES_MODE"'
alias dotpush='git -C "$DOTFILES_DIR" push'
alias dotreload='exec "$SHELL" -l'
alias dotver='echo "$DOTFILES_VERSION"'
alias gap='git add -p'
alias gcm='git commit -m'
alias gcan='git commit --amend --no-edit'
alias gpl='git pull --rebase --autostash'
alias gsw='git switch'
alias grbc='git rebase --continue'
alias grba='git rebase --abort'
alias grbs='git rebase --skip'
alias gpr='git pull --rebase'
alias prune='git remote prune origin'
alias shipit='git status --short && git push'
alias glg='git log --oneline --decorate --graph'
alias gla='git log --oneline --decorate --graph --all'
alias gcount='git shortlog -sn'
alias gbl='git blame -w'
alias gcl='git clone'
alias gdf='git diff --name-only'
alias gdw='git diff --word-diff'
alias gdc='git diff --cached'
alias gpsup='git push --set-upstream origin HEAD'
alias grv='git remote -v'
alias gsta='git stash apply'
alias gstd='git stash drop'
alias gswc='git switch -c'
alias gcp='git cherry-pick'
alias gmc='git merge --continue'
alias gma='git merge --abort'
alias gff='git merge --ff-only'
alias gwp='git worktree prune'
alias grepo='git init'
alias gtags='git tag -l'
alias gshow='git show'
if command -v docker >/dev/null 2>&1; then
    alias dk='_x docker'
    alias dkps='_x docker ps'
    alias dkpsa='_x docker ps -a'
    alias dkim='_x docker images'
    alias dkex='_x docker exec -it'
    alias dklogs='_x docker logs -f'
    alias dklogst='_x docker logs --tail 100 -f'
    alias dkstop='_x docker stop $(docker ps -q)'
    alias dkrm='_x docker rm $(docker ps -aq)'
    alias dkrmi='_x docker rmi $(docker images -q)'
    alias dkprune='_x docker system prune -af'
    alias dkclean='_x docker system prune -af --volumes'
    alias dkbuild='_x docker build -t'
    alias dkrun='_x docker run -it --rm'
    alias dkrunbg='_x docker run -d'
    alias dkexec='_x docker exec -it'
    alias dkstart='_x docker start'
    alias dkrestart='_x docker restart'
    alias dkpause='_x docker pause'
    alias dkunpause='_x docker unpause'
    alias dktop='_x docker top'
    alias dkstats='_x docker stats'
    alias dkcp='_x docker cp'
    alias dkport='_x docker port'
    alias dkcom='_x docker compose'
    alias dkup='_x docker compose up -d'
    alias dkdown='_x docker compose down'
    alias dkpsall='_x docker compose ps'
    alias dklogsall='_x docker compose logs -f'
    alias dknet='_x docker network ls'
    alias dkvol='_x docker volume ls'
    alias dksys='_x docker system df'
fi
if command -v podman >/dev/null 2>&1; then
    alias pod='_x podman'
    alias podps='_x podman ps'
    alias podpsa='_x podman ps -a'
    alias podim='_x podman images'
    alias podex='_x podman exec -it'
    alias podlogs='_x podman logs -f'
    alias podstop='_x podman stop $(podman ps -q)'
    alias podrm='_x podman rm $(podman ps -aq)'
    alias podprune='_x podman system prune -af'
    alias podbuild='_x podman build -t'
    alias podrun='_x podman run -it --rm'
    alias podcom='_x podman compose'
    alias podup='_x podman compose up -d'
    alias poddown='_x podman compose down'
fi
if command -v kubectl >/dev/null 2>&1; then
    alias kgpw='_x kubectl get pods -w'
    alias kgns='_x kubectl get namespaces'
    alias kuse='_x kubectl config use-context'
    alias kd='_x kubectl describe'
    alias kdp='_x kubectl describe pod'
    alias kds='_x kubectl describe svc'
    alias kdd='_x kubectl describe deployment'
    alias kl='_x kubectl logs'
    alias klf='_x kubectl logs -f'
    alias ka='_x kubectl apply -f'
    alias kpf='_x kubectl port-forward'
    alias kexec='_x kubectl exec -it'
    alias ktop='_x kubectl top pods'
    alias ktopn='_x kubectl top nodes'
    alias kedit='_x kubectl edit'
    alias kc='_x kubectl create'
    alias kcf='_x kubectl create -f'
    alias kroll='_x kubectl rollout status'
    alias krestart='_x kubectl rollout restart'
    alias klabel='_x kubectl label'
    alias ktaint='_x kubectl taint'
    alias kcord='_x kubectl cordon'
    alias kuncord='_x kubectl uncordon'
    alias kdrain='_x kubectl drain'
    alias kapi='_x kubectl api-resources'
    alias kexplain='_x kubectl explain'
fi
if command -v systemctl >/dev/null 2>&1; then
    alias scsr='_x systemctl restart'
    alias scse='_x systemctl enable'
    alias scsd='_x systemctl disable'
    alias scn='_x systemctl daemon-reload'
    alias scens='_x systemctl enable --now'
    alias scdis='_x systemctl disable --now'
    alias scu='_x systemctl --user'
    alias scus='_x systemctl --user status'
    alias scust='_x systemctl --user start'
    alias scusp='_x systemctl --user stop'
    alias scusr='_x systemctl --user restart'
    alias scuse='_x systemctl --user enable'
    alias scusd='_x systemctl --user disable'
    alias scl='_x systemctl list-units'
    alias scla='_x systemctl list-units --all'
    alias scfail='_x systemctl list-units --failed'
    alias scmask='_x systemctl mask'
    alias scunmask='_x systemctl unmask'
    alias sccat='_x systemctl cat'
    alias sclist='_x systemctl list-unit-files'
    alias scon='_x systemctl is-active'
fi
if command -v journalctl >/dev/null 2>&1; then
    alias jc='_x journalctl'
    alias jce='_x journalctl -e'
    alias jcf='_x journalctl -f'
    alias jcu='_x journalctl -u'
    alias jcub='_x journalctl -u -b'
    alias jcs='_x journalctl --since'
    alias jct='_x journalctl --until'
    alias jcp='_x journalctl -p err'
    alias jcdf='_x journalctl --disk-usage'
    alias jcro='_x journalctl --rotate'
    alias jcv='_x journalctl --verify'
    alias jcemerg='_x journalctl -p emerg'
    alias jcalert='_x journalctl -p alert'
    alias jccrit='_x journalctl -p crit'
    alias jcwarn='_x journalctl -p warning'
    alias jcnotice='_x journalctl -p notice'
    alias jcinfo='_x journalctl -p info'
    alias jcdebug='_x journalctl -p debug'
    alias jcboot='_x journalctl -b'
fi
if command -v pacman >/dev/null 2>&1; then
    alias pac='sudo pacman'
    alias pacs='_x pacman -Ss'
    alias pacsi='_x pacman -Si'
    alias pacq='_x pacman -Q'
    alias pacqi='_x pacman -Qi'
    alias pacql='_x pacman -Ql'
    alias pacqo='_x pacman -Qo'
    alias pacqs='_x pacman -Qs'
    alias pacup='sudo pacman -Syu'
    alias pacin='sudo pacman -S'
    alias pacrm='sudo pacman -Rns'
    alias pacrmu='sudo pacman -Rdd'
    alias pacor='sudo pacman -Sc'
    alias pacowned='_x pacman -Qii'
    alias pacorph='_x pacman -Qtdq'
    alias pacclean='sudo pacman -Rns $(pacman -Qtdq)'
    alias paclsorph='_x pacman -Qtd'
    alias pacfiles='_x pacman -Fl'
    alias pacdep='_x pacman -Si'
    alias pacwhy='_x pacman -D --asexplicit'
    alias fixpacman='sudo rm -f /var/lib/pacman/db.lck'
fi
if command -v yay >/dev/null 2>&1; then
    alias yay='yay'
    alias yays='yay -Ss'
    alias yayq='yay -Q'
    alias yayup='yay -Syu'
    alias yayi='yay -S'
    alias yayrm='yay -Rns'
    alias yayclean='yay -Sc'
    alias yaygendb='yay -Y --gendb'
    alias yaydev='yay -S --devel'
    alias yayfiles='yay -Fl'
fi
if command -v apt >/dev/null 2>&1 || command -v apt-get >/dev/null 2>&1; then
    alias apt='_x apt'
    alias aptup='sudo apt update && sudo apt upgrade -y'
    alias aptin='sudo apt install'
    alias aptr='sudo apt remove'
    alias aptp='sudo apt purge'
    alias apts='_x apt search'
    alias aptsh='_x apt show'
    alias aptq='dpkg -l'
    alias aptqi='dpkg -l | grep'
    alias aptau='sudo apt autoremove'
    alias aptd='sudo apt download'
    alias aptsrc='sudo apt source'
    alias aptbuild='sudo apt build-dep'
    alias aptpolicy='_x apt policy'
    alias aptchangelog='_x apt changelog'
    alias aptlistup='_x apt list --upgradable'
    alias aptlistins='_x apt list --installed'
    alias apthold='sudo apt-mark hold'
    alias aptunhold='sudo apt-mark unhold'
    alias aptshowhold='apt-mark showhold'
    alias aptfix='sudo apt --fix-broken install'
    alias aptupdate='sudo apt update'
    alias aptdistup='sudo apt full-upgrade'
fi
if command -v dnf >/dev/null 2>&1; then
    alias dnf='_x dnf'
    alias dnfs='_x dnf search'
    alias dnfsi='_x dnf info'
    alias dnfup='sudo dnf upgrade'
    alias dnfi='sudo dnf install'
    alias dnfrm='sudo dnf remove'
    alias dnfau='sudo dnf autoremove'
    alias dnfq='_x dnf list installed'
    alias dnfqi='_x dnf list installed | grep'
    alias dnfrep='_x dnf repolist'
    alias dnfre='_x dnf group list'
    alias dnfcache='sudo dnf clean all'
    alias dnfhist='_x dnf history'
    alias dnfhistinfo='_x dnf history info'
    alias dnfroll='_x dnf history rollback'
    alias dnfdowng='_x dnf downgrade'
    alias dnflocal='sudo dnf localinstall'
    alias dnfprov='_x dnf provides'
    alias dnfchk='_x dnf check-update'
    alias dnfmod='_x dnf module'
fi
if command -v brew >/dev/null 2>&1; then
    alias brew='_x brew'
    alias brews='_x brew search'
    alias brewin='_x brew install'
    alias brewrm='_x brew uninstall'
    alias brewq='_x brew list'
    alias brewsrv='_x brew services'
    alias brewsrvl='_x brew services list'
    alias brewsrvr='_x brew services restart'
    alias brewup='_x brew update && brew upgrade'
    alias brewupc='_x brew update && brew upgrade && brew cleanup'
    alias brewclean='_x brew cleanup'
    alias brewdoc='_x brew doctor'
    alias brewout='_x brew outdated'
    alias brewpin='_x brew pin'
    alias brewsr='_x brew tap'
    alias brewinfo='_x brew info'
    alias brewcask='_x brew install --cask'
    alias brewdep='_x brew deps'
    alias brewuses='_x brew uses'
    alias brewleaves='_x brew leaves'
fi
if command -v flatpak >/dev/null 2>&1; then
    alias flat='flatpak'
    alias flats='flatpak search'
    alias flati='flatpak install'
    alias flatrm='flatpak uninstall'
    alias flatup='flatpak update'
    alias flatq='flatpak list'
    alias flatrun='flatpak run'
    alias flatinfo='flatpak info'
    alias flatover='flatpak override'
fi
if command -v snap >/dev/null 2>&1; then
    alias snap='snap'
    alias snaps='snap search'
    alias snapi='sudo snap install'
    alias snaprm='sudo snap remove'
    alias snapup='sudo snap refresh'
    alias snapq='snap list'
    alias snapinfo='snap info'
    alias snapch='sudo snap changes'
fi
if command -v nix >/dev/null 2>&1; then
    alias nix='nix'
    alias nixs='nix search'
    alias nixsh='nix shell'
    alias nixi='nix profile install'
    alias nixrm='nix profile remove'
    alias nixup='nix profile upgrade'
    alias nixq='nix profile list'
    alias nixdev='nix develop'
    alias nixbuild='nix build'
    alias nixrun='nix run'
    alias nixgc='nix store gc'
    alias nixopt='nix store optimise'
fi
if command -v zypper >/dev/null 2>&1; then
    alias zyp='sudo zypper'
    alias zyps='zypper search'
    alias zypi='sudo zypper install'
    alias zypr='sudo zypper remove'
    alias zypup='sudo zypper update'
    alias zypdup='sudo zypper dist-upgrade'
    alias zypl='zypper list-installed'
    alias zypclean='sudo zypper clean'
    alias zyplr='zypper lr'
    alias zypprov='zypper what-provides'
fi
if command -v apk >/dev/null 2>&1; then
    alias apk='apk'
    alias apks='apk search'
    alias apki='apk add'
    alias apkrm='apk del'
    alias apkup='apk update && apk upgrade'
    alias apkq='apk list'
    alias apkqi='apk list -I'
    alias apkinfo='apk info'
    alias apkclean='apk cache clean'
fi
if command -v node >/dev/null 2>&1; then
    alias node='node'
    alias nt='_x npm test'
    alias nb='_x npm run build'
    alias nrn='_x npm run --'
    alias np='_x npm publish'
    alias nup='_x npm update'
    alias nout='_x npm outdated'
    alias nls='_x npm list'
    alias ndoc='_x npm docs'
    alias ninit='_x npm init -y'
    alias nstar='_x npm star'
    alias nuni='_x npm uninstall'
    alias nlex='_x npm exec'
    alias nwhy='_x npm why'
    alias naud='_x npm audit'
    alias naux='_x npm audit fix'
fi
if command -v npx >/dev/null 2>&1; then
    alias npx='npx'
fi
if command -v pnpm >/dev/null 2>&1; then
    alias pn='_x pnpm'
    alias pni='_x pnpm install'
    alias pnr='_x pnpm run'
    alias pnd='_x pnpm run dev'
    alias pnb='_x pnpm run build'
    alias pnt='_x pnpm test'
    alias pna='_x pnpm add'
    alias pnad='_x pnpm add -D'
    alias pnrm='_x pnpm remove'
    alias pnup='_x pnpm update'
    alias pnout='_x pnpm outdated'
    alias pnls='_x pnpm list'
    alias pninit='_x pnpm init'
    alias pnpub='_x pnpm publish'
    alias pnlint='_x pnpm lint'
    alias pnex='_x pnpm exec'
    alias pnlc='_x pnpm lint:check'
    alias pnstore='_x pnpm store'
fi
if command -v yarn >/dev/null 2>&1; then
    alias y='yarn'
    alias ya='yarn add'
    alias yad='yarn add -D'
    alias yr='yarn run'
    alias yb='yarn build'
    alias yd='yarn dev'
    alias yt='yarn test'
    alias yrm='yarn remove'
    alias yls='yarn list'
    alias yinit='yarn init'
    alias ypub='yarn publish'
    alias ylint='yarn lint'
    alias ygl='yarn global list'
    alias yga='yarn global add'
fi
if command -v python3 >/dev/null 2>&1; then
    alias py='_x python3'
    alias py2='python2 2>/dev/null || python3'
    alias py3='_x python3'
    alias pipup='_x python3 -m pip install --upgrade pip'
    alias venv='_x python3 -m venv .venv'
    alias akt='source .venv/bin/activate'
    alias dakt='deactivate'
    alias pyreq='_x pip freeze > requirements.txt'
    alias pyr='_x python3 -m pip install -r requirements.txt'
    alias pyi='_x python3 -i'
    alias pym='_x python3 -m'
    alias pyt='_x python3 -m pytest'
    alias pyun='_x python3 -m unittest'
fi
if command -v pip >/dev/null 2>&1 || command -v pip3 >/dev/null 2>&1; then
    alias pip='pip3 2>/dev/null || pip'
    alias pi='_x pip install'
    alias piu='_x pip install --upgrade'
    alias pir='_x pip install -r requirements.txt'
    alias pls='_x pip list'
    alias pout='_x pip list --outdated'
    alias psh='_x pip show'
    alias pch='_x pip check'
    alias pdown='_x pip download'
    alias phash='_x pip hash'
fi
if command -v cargo >/dev/null 2>&1; then
    alias cr='_x cargo'
    alias crb='_x cargo build'
    alias crbr='_x cargo build --release'
    alias crr='_x cargo run'
    alias crrr='_x cargo run --release'
    alias crt='_x cargo test'
    alias crcl='_x cargo clippy'
    alias crf='_x cargo fmt'
    alias crc='_x cargo check'
    alias crd='_x cargo doc'
    alias crp='_x cargo publish'
    alias cru='_x cargo update'
    alias crout='_x cargo outdated'
    alias crclean='_x cargo clean'
    alias crbench='_x cargo bench'
    alias crfix='_x cargo fix'
    alias crl='_x cargo +nightly'
    alias crw='_x cargo watch'
    alias cradd='_x cargo add'
    alias crrm='_x cargo remove'
fi
if command -v go >/dev/null 2>&1; then
    alias go='_x go'
    alias gor='_x go run'
    alias gob='_x go build'
    alias got='_x go test'
    alias gotv='_x go test -v ./...'
    alias goi='_x go install'
    alias gom='_x go mod'
    alias gomt='_x go mod tidy'
    alias gomv='_x go mod vendor'
    alias gog='_x go get'
    alias gof='_x go fmt ./...'
    alias gol='_x go vet ./...'
    alias godoc='_x go doc'
    alias gogen='_x go generate ./...'
    alias goc='_x go clean'
    alias gocache='_x go clean -cache'
    alias goenv='_x go env'
    alias gop='_x go tool pprof'
fi
if command -v terraform >/dev/null 2>&1; then
    alias tfv='_x terraform validate'
    alias tff='_x terraform fmt'
    alias tfw='_x terraform workspace'
    alias tfwl='_x terraform workspace list'
    alias tfws='_x terraform workspace select'
    alias tfs='_x terraform show'
    alias tfo='_x terraform output'
    alias tfst='_x terraform state'
    alias tfstl='_x terraform state list'
    alias tfimp='_x terraform import'
    alias tfprov='_x terraform providers'
    alias tfgraph='_x terraform graph'
    alias tfconsole='_x terraform console'
fi
if command -v ansible >/dev/null 2>&1; then
    alias an='_x ansible'
    alias anp='_x ansible-playbook'
    alias ang='_x ansible-galaxy'
    alias anv='_x ansible-vault'
    alias and='_x ansible-doc'
    alias ancon='_x ansible-config'
    alias aninv='_x ansible-inventory'
fi
if command -v helm >/dev/null 2>&1; then
    alias hl='_x helm'
    alias hls='_x helm list'
    alias hli='_x helm install'
    alias hlu='_x helm upgrade'
    alias hlui='_x helm upgrade --install'
    alias hld='_x helm delete'
    alias hlr='_x helm rollback'
    alias hlg='_x helm get'
    alias hlga='_x helm get all'
    alias hlgs='_x helm get values'
    alias hlh='_x helm history'
    alias hlsh='_x helm show'
    alias hlshc='_x helm show chart'
    alias hlshv='_x helm show values'
    alias hlrepo='_x helm repo'
    alias hlrl='_x helm repo list'
    alias hlra='_x helm repo add'
    alias hlru='_x helm repo update'
    alias hlsea='_x helm search'
    alias hlver='_x helm version'
    alias hlcomp='_x helm completion'
    alias hlplug='_x helm plugin'
    alias hlpl='_x helm plugin list'
fi
if command -v tmux >/dev/null 2>&1; then
    alias tad='_x tmux attach -d'
    alias tl='_x tmux list-sessions'
    alias tn='_x tmux new-session -s'
    alias tk='_x tmux kill-session -t'
    alias tks='_x tmux kill-server'
    alias tsw='_x tmux switch-client'
    alias trn='_x tmux rename-session'
    alias tlp='_x tmux list-panes'
    alias tsplit='_x tmux split-window -h'
    alias tsplitv='_x tmux split-window'
    alias tprev='_x tmux previous-window'
    alias tnext='_x tmux next-window'
    alias tswap='_x tmux swap-window'
fi
if command -v ssh >/dev/null 2>&1; then
    alias ssh='_x ssh'
    alias ssha='_x ssh -A'
    alias sshi='_x ssh -o StrictHostKeyChecking=no'
    alias ssk='ssh-keygen'
    alias sskr='ssh-keygen -R'
    alias ssc='ssh-copy-id'
fi
alias myipl='ip addr show | grep "inet " | awk "{print \$2}" | cut -d/ -f1 | head -1'
alias weather='curl -fsSL wttr.in'
alias portlisten='ss -tlnp 2>/dev/null || netstat -tlnp'
alias pingf='ping -c 100 -s 1472 -f'
alias pb='ping -c 4 8.8.8.8'
alias net='ip -br addr'
alias ipl='ip -br link'
alias ipa='ip -br addr'
alias ipr='ip route'
alias nst='netstat -tulanp 2>/dev/null || ss -tulanp'
alias trace='traceroute'
if command -v dig >/dev/null 2>&1; then
    alias dns='dig +short'
    alias dnsx='dig ANY +short'
    alias dnsmx='dig MX +short'
    alias dnsns='dig NS +short'
    alias dnstxt='dig TXT +short'
    alias dnsany='dig ANY'
fi
if command -v nmap >/dev/null 2>&1; then
    alias nm='nmap'
    alias nms='nmap -sn'
    alias nmp='nmap -sV -sC'
    alias nmo='nmap -O'
fi
if command -v curl >/dev/null 2>&1; then
    alias cur='curl -fsSL'
    alias curh='curl -I'
    alias curv='curl -v'
    alias curj='curl -s | jq .'
    alias curd='curl -X DELETE'
    alias curp='curl -X POST'
    alias curu='curl -X PUT'
fi
if command -v wget >/dev/null 2>&1; then
    alias wg='wget -c'
    alias wgr='wget -r -np -nH'
fi
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias rmr='rm -r'
alias rmf='rm -f'
alias cpf='cp -f'
alias mvfs='mv -f'
alias cpv='_x rsync -ah --progress'
alias mkd='mkdir -p'
alias rsync='_x rsync -avz --progress'
alias rsyncdn='_x rsync -avz --dry-run --progress'
alias chx='chmod +x'
alias chm='chmod'
alias chown='chown'
alias chgrp='chgrp'
alias ln='ln -s'
alias lnh='readlink -f'
alias backup='cp -r "$1" "${1}.bak-$(date +%Y%m%d-%H%M%S)"'
alias timestamp='date +%s'
alias today='date +%F'
alias week='date +%V'
alias mount='mount | column -t'
alias tart='tar -tzf'
alias tarjx='tar -xjf'
alias tarjc='tar -cjf'
alias tarzx='tar -xJf'
alias tarzc='tar -cJf'
alias tarl='tar -tvf'
alias gunz='gunzip'
alias bz2='bzip2'
alias bunz='bunzip2'
alias xz='xz'
alias unxz='unxz'
alias 7z='7z'
alias 7zx='7z x'
alias 7za='7z a'
alias rarx='unrar x'
alias ps='ps auxf'
alias pse='ps aux | grep'
alias pst='_x pstree'
alias psea='ps -e'
alias kill9='kill -9'
alias kill15='kill -15'
alias pkillf='_x pkill -f'
alias pid='_x pgrep -f'
alias nohup='nohup'
alias disown='disown'
alias bg='bg'
alias fg='fg'
alias nice='nice -n'
alias renice='renice -n'
alias topcpu='ps aux --sort=-%cpu | head 2>/dev/null || ps aux -r | head'
alias topmem='ps aux --sort=-%mem | head 2>/dev/null || ps aux -m | head'
alias iotop='iotop -o 2>/dev/null || echo "iotop not found"'
alias gr='grep'
alias gri='grep -i'
alias grr='grep -r'
alias grri='grep -ri'
alias grl='grep -rl'
alias grc='grep -c'
alias sed='sed'
alias awk='awk'
alias sort='sort'
alias uniq='uniq'
alias uniqc='sort | uniq -c | sort -rn'
alias wc='wc'
alias wcw='wc -w'
alias cut='cut'
alias tr='tr'
alias fold='fold'
alias column='column -t'
alias join='join'
alias diff='diff'
alias diffy='diff -y'
alias cmp='cmp'
alias head='head'
alias tail='tail'
alias tair='tail -f'
alias taill='tail -100'
alias headl='head -100'
alias nl='nl -ba'
alias tac='tac 2>/dev/null || tail -r'
alias rev='rev'
alias shuf='shuf'
alias yes='yes'
if command -v rg >/dev/null 2>&1; then
    alias rg='rg --hidden --glob "!.git"'
    alias rgi='rg -i --hidden --glob "!.git"'
    alias rgf='rg --files'
    alias rgl='rg --files-with-matches'
    alias rgc='rg --count'
fi
if command -v fd >/dev/null 2>&1; then
    alias fd='fd --hidden'
    alias fdi='fd -i'
fi
if command -v gpg >/dev/null 2>&1; then
    alias gpg='_x gpg'
    alias gpge='_x gpg -e'
    alias gpgd='_x gpg -d'
    alias gpgs='_x gpg -s'
    alias gpgv='_x gpg --verify'
    alias gpgl='_x gpg --list-keys'
    alias gpgls='_x gpg --list-secret-keys'
    alias gpgk='_x gpg --list-keys'
    alias gpgex='_x gpg --export'
    alias gpgimport='_x gpg --import'
    alias gpgrecv='_x gpg --recv-keys'
    alias gpgens='_x gpg --gen-key'
fi
if command -v openssl >/dev/null 2>&1; then
    alias ossl='openssl'
    alias osslcsr='openssl req -new -newkey rsa:2048 -nodes'
    alias osslchk='openssl s_client -connect'
    alias osslx='openssl x509 -in'
    alias osslr='openssl rand -hex'
    alias osslgen='openssl genrsa'
fi
if command -v shred >/dev/null 2>&1; then
    alias shred='shred -uz'
    alias shredf='shred -uz -n 7'
fi
if command -v lsof >/dev/null 2>&1; then
    alias lsof='lsof'
    alias lsofi='lsof -i'
    alias lsofp='lsof -P'
    alias lsofn='lsof -nP'
fi
alias du='du -h'
alias dud='du -h --max-depth=1'
alias dfT='df -hT'
alias blk='lsblk -f'
alias findsuid='find / -perm -4000 -type f'
alias disks='lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINT'
alias fdisk='fdisk -l'
alias smart='sudo smartctl -a'
alias cpuinfo='lscpu 2>/dev/null || sysctl -n machdep.cpu.brand_string'
alias meminfo='free -h'
alias diskspace='df -h'
alias uptime='uptime'
alias dmesg='dmesg -T'
alias uname='uname -a'
alias dateutc='date -u'
alias caldate='cal'
alias nproc='nproc 2>/dev/null || sysctl -n hw.ncpu'
alias release='cat /etc/os-release 2>/dev/null || cat /usr/lib/os-release'
alias arch='uname -m'
alias vim='nvim 2>/dev/null || command vim'
alias sv='nvim 2>/dev/null || command vim'
alias nv='nvim'
alias codel='code .'
alias micro='micro'
if command -v lazygit >/dev/null 2>&1; then
    alias lg='lazygit'
fi
if command -v yazi >/dev/null 2>&1; then
    alias yz='yazi'
fi
if command -v zellij >/dev/null 2>&1; then
    alias zj='zellij'
    alias zja='zellij attach'
    alias zjl='zellij list-sessions'
fi
if command -v just >/dev/null 2>&1; then
    alias just='just'
    alias justl='just --list'
fi
if command -v make >/dev/null 2>&1; then
    alias mk='make'
    alias mkc='make clean'
    alias mki='make install'
    alias mkt='make test'
fi
if command -v mysql >/dev/null 2>&1; then
    alias myq='mysql'
    alias myqr='mysql -u root -p'
    alias mydump='mysqldump'
    alias mydumpr='mysqldump -u root -p'
fi
if command -v psql >/dev/null 2>&1; then
    alias psql='psql'
    alias psqlr='psql -U postgres'
    alias pgdump='pg_dump'
    alias pgres='pg_restore'
fi
if command -v sqlite3 >/dev/null 2>&1; then
    alias sq3='sqlite3'
    alias sq3d='sqlite3 .dump'
fi
if command -v redis-cli >/dev/null 2>&1; then
    alias rcli='redis-cli'
    alias rcliping='redis-cli ping'
    alias rcliinfo='redis-cli info'
    alias rclimon='redis-cli monitor'
fi
alias s3='_x s3cmd'
alias mc='mc'
if command -v aws >/dev/null 2>&1; then
    alias aws='aws'
    alias awsw='aws sts get-caller-identity'
    alias awsinfo='aws ec2 describe-instances'
    alias awss3='aws s3'
    alias awss3ls='aws s3 ls'
    alias awslb='aws elb describe-load-balancers'
    alias awsecs='aws ecs list-clusters'
    alias awsecr='aws ecr describe-repositories'
    alias awslam='aws lambda list-functions'
    alias awslog='aws logs describe-log-groups'
    alias awscw='aws cloudwatch'
    alias awsiam='aws iam list-users'
    alias awsr53='aws route53 list-hosted-zones'
fi
if command -v gcloud >/dev/null 2>&1; then
    alias gcl='gcloud'
    alias gcls='gcloud compute ssh'
    alias gcll='gcloud compute instances list'
    alias gclc='gcloud container clusters list'
    alias gclgke='gcloud container clusters get-credentials'
    alias gcllogs='gcloud logging list'
fi
if command -v az >/dev/null 2>&1; then
    alias az='az'
    alias azl='az vm list'
    alias azs='az vm start'
    alias azst='az vm stop'
    alias azr='az vm restart'
    alias azg='az group list'
    alias azaks='az aks list'
fi
if command -v ffmpeg >/dev/null 2>&1; then
    alias ffp='ffprobe'
    alias ffg='ffplay'
    alias ffconvert='ffmpeg -i'
    alias ffmp3='ffmpeg -i "$1" -q:a 0 "${1%.*}.mp3"'
    alias ffcompress='ffmpeg -i "$1" -vcodec libx265 -crf 28'
    alias ffgif='ffmpeg -i "$1" -vf "fps=10,scale=320:-1" "${1%.*}.gif"'
    alias ffscreencap='ffmpeg -f x11grab -video_size 1920x1080 -i :0.0'
fi
if command -v convert >/dev/null 2>&1; then
    alias img='convert'
    alias imgres='convert -resize'
    alias imgfmt='convert -format'
    alias imgcompress='convert -quality 85'
fi
if command -v nvidia-smi >/dev/null 2>&1; then
    alias gpul='nvidia-smi --query-gpu=index,name,utilization.gpu,memory.used,memory.total,temperature.gpu --format=csv'
    alias gputop='nvidia-smi dmon -s pucvmet'
fi
alias matrix='printf "\01101000\01100101\01101100\01101100\01101111\n"'
alias coinflip='awk "BEGIN{srand();print rand()<0.5?\"heads\":\"tails\"}"'
alias dice='echo $((RANDOM % 6 + 1))'
alias randpw='openssl rand -base64 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_urlsafe(16))"'
alias sha='shasum -a 256'
alias md5sum='md5 2>/dev/null || command md5sum'
alias hex='xxd'
alias base64e='base64'
alias base64d='base64 -d'
alias urlenc='_x python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))"'
alias urldec='_x python3 -c "import urllib.parse,sys; print(urllib.parse.unquote(sys.argv[1]))"'

alias count='wc -l'
alias lines='cat -n'
alias cht='curl -fsSL "https://cht.sh/$1"'
alias learn='curl -fsSL "https://learnxinyminutes.com/docs/$1"'
alias cheat='curl -fsSL "https://cheat.sh/$1"'
alias man='man'
alias help='help'
alias info='info'
alias what='type'
alias ali='alias'
alias envg='env | grep'
alias fn='declare -f 2>/dev/null || typeset -f'
alias dsync='dot_sync'
alias chmode='export DOTFILES_MODE'
alias modestat='echo "Mode: ${DOTFILES_MODE:-unknown}"'
alias dotinfo='echo "Dotfiles: $DOTFILES_DIR | Mode: ${DOTFILES_MODE:-unknown} | Shell: $SHELL"'
alias pgit='git'
alias pgitst='git status --short --branch'
alias pgitadd='git add'
alias pgitaddall='git add -A'
alias pgitaddpatch='git add -p'
alias pgitbr='git branch'
alias pgitbrd='git branch -d'
alias pgitbrD='git branch -D'
alias pgitbrall='git branch -a'
alias pgitbrnm='git branch -m'
alias pgitco='git checkout'
alias pgitsw='git switch'
alias pgitswc='git switch -c'
alias pgitcl='git clone'
alias pgitcm='git commit'
alias pgitcmm='git commit -m'
alias pgitcma='git commit --amend'
alias pgitcmne='git commit --amend --no-edit'
alias pgitdf='git diff'
alias pgitdfs='git diff --staged'
alias pgitdfw='git diff --word-diff'
alias pgitdfn='git diff --name-only'
alias pgitft='git fetch'
alias pgitftp='git fetch --all --prune'
alias pgitlg='git log --oneline --graph -20'
alias pgitlga='git log --oneline --graph --all -20'
alias pgitlgs='git log --oneline --graph --all --simplify-by-decoration'
alias pgitmg='git merge'
alias pgitmgff='git merge --ff-only'
alias pgitmgnc='git merge --no-commit'
alias pgitph='git push'
alias pgitphf='git push --force-with-lease'
alias pgitphu='git push -u origin HEAD'
alias pgitpl='git pull'
alias pgitplr='git pull --rebase --autostash'
alias pgitpr='git remote prune origin'
alias pgitsh='git stash'
alias pgitshp='git stash pop'
alias pgitshl='git stash list'
alias pgitsha='git stash apply'
alias pgitshd='git stash drop'
alias pgitshw='git stash show -p'
alias pgitrb='git rebase'
alias pgitrbc='git rebase --continue'
alias pgitrba='git rebase --abort'
alias pgitrbs='git rebase --skip'
alias pgitrbi='git rebase -i'
alias pgitrs='git reset'
alias pgitrsf='git reset --hard'
alias pgitrss='git reset --soft'
alias pgitrm='git remote -v'
alias pgitrma='git remote add'
alias pgitrmrm='git remote remove'
alias pgitcp='git cherry-pick'
alias pgitcpnc='git cherry-pick --no-commit'
alias pgitbl='git blame'
alias pgitgr='git grep'
alias pgittg='git tag'
alias pgitcfg='git config'
alias pgitcfgg='git config --global'
alias pgitwrk='git worktree'
alias pgitwrka='git worktree add'
alias pgitwrkl='git worktree list'
alias pgitwrkpr='git worktree prune'
alias pgitign='git update-index --assume-unchanged'
alias pgitignn='git update-index --no-assume-unchanged'
alias pgitignl='git ls-files -v | grep "^[a-z]"'
alias pgitarc='git archive'
alias pgitbnd='git bundle'
alias pgitdesc='git describe'
alias pgitref='git reflog'
alias pgitcln='git clean -fd'
alias pgitshow='git show'
alias pgitsm='git submodule'
alias pgitinit='git init'
alias pgitbis='git bisect'
alias pgitci='git citool'
alias pdk='_x docker'
alias pdkps='_x docker ps'
alias pdkpsa='_x docker ps -a'
alias pdkpsq='_x docker ps -q'
alias pdkpsl='_x docker ps -l'
alias pdkim='_x docker images'
alias pdkima='_x docker images -a'
alias pdkimq='_x docker images -q'
alias pdkimrm='_x docker rmi'
alias pdkex='_x docker exec -it'
alias pdkexsh='_x docker exec -it /bin/sh'
alias pdkexba='_x docker exec -it /bin/bash'
alias pdkcp='_x docker cp'
alias pdklogs='_x docker logs'
alias pdklogsf='_x docker logs -f'
alias pdklogst='_x docker logs --tail 100 -f'
alias pdkrun='_x docker run -it --rm'
alias pdkrund='_x docker run -d'
alias pdkrunp='_x docker run -it --rm -p'
alias pdkrunv='_x docker run -it --rm -v'
alias pdkrn='_x docker run --name'
alias pdkst='_x docker start'
alias pdkstp='_x docker stop'
alias pdkstpa='_x docker stop $(docker ps -q)'
alias pdkrs='_x docker restart'
alias pdkrm='_x docker rm'
alias pdkrma='_x docker rm $(docker ps -aq)'
alias pdkrmv='_x docker rm -v'
alias pdkbl='_x docker build'
alias pdkblt='_x docker build -t'
alias pdkblnc='_x docker build --no-cache -t'
alias pdkblpus='_x docker buildx build --push'
alias pdkpush='_x docker push'
alias pdkpull='_x docker pull'
alias pdkpsh='_x docker push'
alias pdkcm='_x docker commit'
alias pdknet='_x docker network'
alias pdknetls='_x docker network ls'
alias pdknetcr='_x docker network create'
alias pdknetrm='_x docker network rm'
alias pdkvol='_x docker volume'
alias pdkvolls='_x docker volume ls'
alias pdkvolrm='_x docker volume rm'
alias pdkvolpr='_x docker volume prune'
alias pdkstts='_x docker stats'
alias pdkstop='_x docker top'
alias pdkpr='_x docker system prune'
alias pdkpra='_x docker system prune -af'
alias pdkprv='_x docker system prune -af --volumes'
alias pdkdf='_x docker system df'
alias pdkdh='_x docker system df'
alias pdkpsf='_x docker ps --format'
alias pdkcom='_x docker compose'
alias pdkcomp='_x docker compose ps'
alias pdkcomup='_x docker compose up -d'
alias pdkcomdown='_x docker compose down'
alias pdkcomlogs='_x docker compose logs -f'
alias pdkcombuild='_x docker compose build'
alias pdkcompull='_x docker compose pull'
alias pdkcomrestart='_x docker compose restart'
alias pdkcomstop='_x docker compose stop'
alias pdkcomstart='_x docker compose start'
alias pdkcomrm='_x docker compose rm'
alias pdkcomex='_x docker compose exec'
alias pdkcomrun='_x docker compose run --rm'
alias pdkcomcr='_x docker compose create'
alias pdkcomsc='_x docker compose scale'
alias pdkcomtop='_x docker compose top'
alias pdkcomps='_x docker compose images'
alias pk='_x kubectl'
alias pkgs='_x kubectl get all'
alias pkgp='_x kubectl get pods'
alias pkgpw='_x kubectl get pods -w'
alias pkgsv='_x kubectl get svc'
alias pkgdep='_x kubectl get deployments'
alias pkgng='_x kubectl get nodes'
alias pkgns='_x kubectl get namespaces'
alias pkgst='_x kubectl get statefulsets'
alias pkgds='_x kubectl get daemonsets'
alias pkgcj='_x kubectl get cronjobs'
alias pkgj='_x kubectl get jobs'
alias pkgi='_x kubectl get ingress'
alias pkgcm='_x kubectl get configmaps'
alias pkgsec='_x kubectl get secrets'
alias pkgpv='_x kubectl get pv'
alias pkgpvc='_x kubectl get pvc'
alias pkgsc='_x kubectl get storageclass'
alias pkgn='_x kubectl get networkpolicies'
alias pkgall='_x kubectl get all --all-namespaces'
alias pkdesc='_x kubectl describe'
alias pkdp='_x kubectl describe pod'
alias pkds='_x kubectl describe svc'
alias pkdd='_x kubectl describe deployment'
alias pkdn='_x kubectl describe node'
alias kdl='_x kubectl describe pod -l app'
alias pklog='_x kubectl logs'
alias pklogf='_x kubectl logs -f'
alias pklogp='_x kubectl logs --previous'
alias pkapp='_x kubectl apply -f'
alias pkappl='_x kubectl apply -f --recursive'
alias pkdel='_x kubectl delete'
alias pkdelp='_x kubectl delete pod'
alias pkdels='_x kubectl delete svc'
alias pkex='_x kubectl exec -it'
alias pkexsh='_x kubectl exec -it -- /bin/sh'
alias pkexba='_x kubectl exec -it -- /bin/bash'
alias pkpf='_x kubectl port-forward'
alias pktop='_x kubectl top pods'
alias pktopn='_x kubectl top nodes'
alias pkedit='_x kubectl edit'
alias pkcr='_x kubectl create -f'
alias pkroll='_x kubectl rollout status'
alias pkrollh='_x kubectl rollout history'
alias pkrollu='_x kubectl rollout undo'
alias pkres='_x kubectl rollout restart'
alias pkscale='_x kubectl scale'
alias pklab='_x kubectl label'
alias pktaint='_x kubectl taint'
alias pkcord='_x kubectl cordon'
alias pkuncord='_x kubectl uncordon'
alias pkdrain='_x kubectl drain'
alias pkapi='_x kubectl api-resources'
alias pkapiv='_x kubectl api-versions'
alias pkexpl='_x kubectl explain'
alias pkctx='_x kubectl config current-context'
alias pkuse='_x kubectl config use-context'
alias pkgetctx='_x kubectl config get-contexts'
alias pksetctx='_x kubectl config set-context'
alias pkview='_x kubectl config view'
alias pkcns='_x kubectl config set-context --namespace'
alias pkcp='_x kubectl cp'
alias pkauth='_x kubectl auth can-i'
alias pkcomp='_x kubectl completion'
alias pkwatch='_x kubectl get pods --watch'
alias psc='_x systemctl'
alias pscst='_x systemctl status'
alias pscup='_x systemctl start'
alias pscdown='_x systemctl stop'
alias pscrs='_x systemctl restart'
alias pscen='_x systemctl enable'
alias pscdis='_x systemctl disable'
alias pscenow='_x systemctl enable --now'
alias pscdisn='_x systemctl disable --now'
alias pscmask='_x systemctl mask'
alias pscunmask='_x systemctl unmask'
alias pscrel='_x systemctl daemon-reload'
alias psclist='_x systemctl list-units'
alias psclista='_x systemctl list-units --all'
alias psclistf='_x systemctl list-unit-files'
alias pscfail='_x systemctl list-units --failed'
alias pscisact='_x systemctl is-active'
alias pscisen='_x systemctl is-enabled'
alias psccat='_x systemctl cat'
alias pscedit='_x systemctl edit'
alias pscadd='_x systemctl add-wants'
alias pschlp='_x systemctl help'
alias psctim='_x systemd-analyze'
alias pscblame='_x systemd-analyze blame'
alias psccrit='_x systemd-analyze critical-chain'
alias pscca='_x systemd-analyze calendar'
alias psccond='_x systemd-analyze condition'
alias pjc='_x journalctl'
alias pjce='_x journalctl -e'
alias pjcf='_x journalctl -f'
alias pjcu='_x journalctl -u'
alias pjcub='_x journalctl -u -b'
alias pjcs='_x journalctl --since'
alias pjct='_x journalctl -n'
alias pjcp='_x journalctl -p'
alias pjcerr='_x journalctl -p err'
alias pjcwarn='_x journalctl -p warning'
alias pjcinfo='_x journalctl -p info'
alias pjcdebug='_x journalctl -p debug'
alias pjcb='_x journalctl -b'
alias pjcb1='_x journalctl -b -1'
alias pjcb2='_x journalctl -b -2'
alias pjcboot='_x journalctl --list-boots'
alias pjcdsk='_x journalctl --disk-usage'
alias pjcro='_x journalctl --rotate'
alias pjcvac='_x journalctl --vacuum-size'
alias pjcvact='_x journalctl --vacuum-time'
alias ppod='_x podman'
alias ppodps='_x podman ps'
alias ppodpsa='_x podman ps -a'
alias ppodim='_x podman images'
alias ppodimrm='_x podman rmi'
alias ppodex='_x podman exec -it'
alias ppodlogs='_x podman logs'
alias ppodlogsf='_x podman logs -f'
alias ppodrun='_x podman run -it --rm'
alias ppodrund='_x podman run -d'
alias ppodst='_x podman start'
alias ppodstp='_x podman stop'
alias ppodrs='_x podman restart'
alias ppodrm='_x podman rm'
alias ppodbl='_x podman build -t'
alias ppodpull='_x podman pull'
alias ppodpush='_x podman push'
alias ppodpr='_x podman system prune -af'
alias ppodnet='_x podman network ls'
alias ppodvol='_x podman volume ls'
alias ppodcom='_x podman compose'
alias ppodcomp='_x podman compose ps'
alias ppodcompup='_x podman compose up -d'
alias ppodcompdown='_x podman compose down'
alias ppodcomplogs='_x podman compose logs -f'
alias ptf='_x terraform'
alias ptfinit='_x terraform init'
alias ptfinitup='_x terraform init -upgrade'
alias ptfpl='_x terraform plan'
alias ptfplo='_x terraform plan -out=tfplan'
alias ptfap='_x terraform apply'
alias ptfapo='_x terraform apply tfplan'
alias ptfdes='_x terraform destroy'
alias ptfval='_x terraform validate'
alias ptffmt='_x terraform fmt'
alias ptffmtr='_x terraform fmt -recursive'
alias ptfws='_x terraform workspace'
alias ptfwsl='_x terraform workspace list'
alias ptfwss='_x terraform workspace select'
alias ptfwsn='_x terraform workspace new'
alias ptfwsd='_x terraform workspace delete'
alias ptfsh='_x terraform show'
alias ptfout='_x terraform output'
alias ptfst='_x terraform state list'
alias ptfstsh='_x terraform state show'
alias ptfstmv='_x terraform state mv'
alias ptfstrm='_x terraform state rm'
alias ptfstpull='_x terraform state pull'
alias ptfstpush='_x terraform state push'
alias ptfim='_x terraform import'
alias ptfprv='_x terraform providers'
alias ptfprvlock='_x terraform providers lock'
alias ptfprvmir='_x terraform providers mirror'
alias ptfgr='_x terraform graph'
alias ptfcon='_x terraform console'
alias ptfun='_x terraform untaint'
alias ptftaint='_x terraform taint'
alias ptfvers='_x terraform version'
alias ptfref='_x terraform refesh'
alias pan='_x ansible'
alias panall='_x ansible all -m'
alias panping='_x ansible all -m ping'
alias pangath='_x ansible all -m gather_facts'
alias pansh='_x ansible all -m shell -a'
alias panpl='_x ansible-playbook'
alias panplchk='_x ansible-playbook --check'
alias panplsy='_x ansible-playbook --syntax-check'
alias pangal='_x ansible-galaxy'
alias pangals='_x ansible-galaxy search'
alias pangalin='_x ansible-galaxy install'
alias pangup='_x ansible-galaxy collection install --upgrade'
alias panvault='_x ansible-vault'
alias panvenc='_x ansible-vault encrypt'
alias panvdec='_x ansible-vault decrypt'
alias panved='_x ansible-vault edit'
alias panvcr='_x ansible-vault create'
alias panvvi='_x ansible-vault view'
alias pandoc='_x ansible-doc'
alias pandocl='_x ansible-doc -l'
alias pnaconf='_x ansible-config list'
alias paninv='_x ansible-inventory --graph'
alias ph='_x helm'
alias phls='_x helm list'
alias phlsa='_x helm list --all'
alias phlsn='_x helm list -n'
alias phi='_x helm install'
alias phin='_x helm install --namespace'
alias phiu='_x helm upgrade --install'
alias phup='_x helm upgrade'
alias phupn='_x helm upgrade --namespace'
alias phdel='_x helm delete'
alias phdeln='_x helm delete --purge'
alias phroll='_x helm rollback'
alias phrold='_x helm rollback --dry-run'
alias phget='_x helm get all'
alias phgv='_x helm get values'
alias phgvc='_x helm get values --all'
alias phgn='_x helm get notes'
alias phgh='_x helm get hooks'
alias phgm='_x helm get manifest'
alias phhis='_x helm history'
alias phhisn='_x helm history --namespace'
alias phsh='_x helm show chart'
alias phshv='_x helm show values'
alias phshr='_x helm show readme'
alias phshc='_x helm show crds'
alias phrp='_x helm repo'
alias phrpl='_x helm repo list'
alias phrpa='_x helm repo add'
alias phrprm='_x helm repo remove'
alias phrpu='_x helm repo update'
alias phrpidx='_x helm repo index'
alias phsea='_x helm search hub'
alias phsr='_x helm search repo'
alias phver='_x helm version'
alias phenv='_x helm env'
alias phcomp='_x helm completion'
alias phplg='_x helm plugin'
alias phplgl='_x helm plugin list'
alias phplgi='_x helm plugin install'
alias phplgrm='_x helm plugin remove'
alias ptmx='_x tmux'
alias ptmxls='_x tmux list-sessions'
alias ptmxnew='_x tmux new-session -s'
alias ptmxatt='_x tmux attach'
alias ptmxattd='_x tmux attach -d'
alias ptmxkill='_x tmux kill-session -t'
alias ptmxkillall='_x tmux kill-server'
alias ptmxsw='_x tmux switch-client -t'
alias ptmxren='_x tmux rename-session -t'
alias ptmxlist='_x tmux list-windows -a'
alias ptmxpanes='_x tmux list-panes -a'
alias ptmxsp='_x tmux split-window -h'
alias ptmxspv='_x tmux split-window'
alias ptmxwin='_x tmux new-window'
alias ptmxclose='_x tmux kill-pane'
alias ptmxprev='_x tmux previous-window'
alias tmxn='_x tmux next-window'
alias ptmxmv='_x tmux move-window'
alias ptmxswp='_x tmux swap-window -t'
alias ptmxsync='_x tmux setw synchronize-panes'
alias ptmxcap='_x tmux capture-pane -pS -'
alias ptmxbuf='_x tmux save-buffer'
alias ptmxchoos='_x tmux choose-session'
alias pbr='_x brew'
alias pbrls='_x brew list'
alias pbrsr='_x brew search'
alias pbri='_x brew install'
alias pbrci='_x brew install --cask'
alias pbrrm='_x brew uninstall'
alias pbrupg='_x brew upgrade'
alias pbrup='_x brew update && brew upgrade'
alias pbrcl='_x brew cleanup'
alias pbrcln='_x brew cleanup --prune=all'
alias pbrdoc='_x brew doctor'
alias pbrout='_x brew outdated'
alias pbrinfo='_x brew info'
alias pbrdep='_x brew deps'
alias pbrtree='_x brew deps --tree'
alias pbruses='_x brew uses'
alias pbrleaves='_x brew leaves'
alias pbrpin='_x brew pin'
alias pbrunpin='_x brew unpin'
alias pbrsvc='_x brew services'
alias pbrsvcls='_x brew services list'
alias pbrsvcst='_x brew services start'
alias pbrsvcsp='_x brew services stop'
alias pbrsvcrs='_x brew services restart'
alias pbrserv='_x brew services'
alias pbrbun='_x brew bundle'
alias pbrbund='_x brew bundle dump'
alias pbrbunc='_x brew bundle cleanup'
alias pbrcask='_x brew casks'
alias pbrform='_x brew formulae'
alias ppac='_x pacman'
alias ppaq='_x pacman -Q'
alias ppaqi='_x pacman -Qi'
alias ppaql='_x pacman -Ql'
alias ppaqo='_x pacman -Qo'
alias ppaqs='_x pacman -Qs'
alias ppaqdt='_x pacman -Qdt'
alias ppaqd='_x pacman -Qd'
alias ppaqe='_x pacman -Qe'
alias ppaqm='_x pacman -Qm'
alias ppas='_x pacman -Ss'
alias ppasi='_x pacman -Si'
alias ppaup='sudo pacman -Syu'
alias ppain='sudo pacman -S'
alias pparm='sudo pacman -Rns'
alias ppard='sudo pacman -Rdd'
alias ppasc='sudo pacman -Sc'
alias ppaf='_x pacman -Fl'
alias ppaowns='_x pacman -Qo'
alias ppafiles='_x pacman -Fl'
alias ppaorph='_x pacman -Qtdq'
alias ppaclean='sudo pacman -Rns $(pacman -Qtdq)'
alias ppaar='sudo pacman -Syu --noconfirm'
alias ppau='sudo pacman -Syu'
alias ppasy='sudo pacman -Sy'
alias ppauma='sudo pacman -Syu --noconfirm'
alias ppah='_x pacman -Qii'
alias papt='_x apt'
alias papts='_x apt search'
alias paptsh='_x apt show'
alias paptup='sudo apt update'
alias paptug='sudo apt upgrade -y'
alias paptfu='sudo apt full-upgrade -y'
alias paptin='sudo apt install'
alias paptrm='sudo apt remove'
alias paptpur='sudo apt purge'
alias paptau='sudo apt autoremove -y'
alias paptcl='sudo apt clean'
alias paptac='sudo apt autoclean'
alias paptfix='sudo apt --fix-broken install'
alias paptdw='sudo apt download'
alias paptsrc='sudo apt source'
alias paptbd='sudo apt build-dep'
alias paptpl='_x apt policy'
alias paptlu='_x apt list --upgradable'
alias paptli='_x apt list --installed'
alias paptsrv='_x apt list --installed | grep -i'
alias paph='apt-mark hold'
alias papunh='apt-mark unhold'
alias papsh='apt-mark showhold'
alias papch='apt-get changelog'
alias pdnf='_x dnf'
alias pdnfs='_x dnf search'
alias pdnfsi='_x dnf info'
alias pdnfup='sudo dnf upgrade -y'
alias pdnfi='sudo dnf install'
alias pdnfrm='sudo dnf remove'
alias pdnfau='sudo dnf autoremove -y'
alias pdnfq='_x dnf list installed'
alias pdnfqi='_x dnf list installed | grep'
alias pdnfre='_x dnf repolist'
alias pdnfgl='_x dnf group list'
alias pdnfcc='sudo dnf clean all'
alias pdnfhi='_x dnf history'
alias pdnfhiu='_x dnf history userinstalled'
alias pdnfroll='_x dnf history rollback'
alias pdnfdw='_x dnf downgrade'
alias pdnfli='sudo dnf localinstall'
alias pdnfprov='_x dnf provides'
alias pdnfchk='_x dnf check-update'
alias pdnfmod='_x dnf module list'
if command -v yay >/dev/null 2>&1; then
alias pyay='yay'
alias pyays='yay -Ss'
alias pyayq='yay -Q'
alias pyayqi='yay -Qi'
alias pyayup='yay -Syu'
alias pyayin='yay -S'
alias pyayrm='yay -Rns'
alias pyaycl='yay -Sc'
alias pyaydb='yay -Y --gendb'
alias pyaydev='yay -S --devel'
alias pyayfl='yay -Fl'
alias pyaynews='yay -P --news'
alias pyaycf='yay -Pg'
fi
alias pnpm='_x npm'
alias pnmini='_x npm init -y'
alias pnminst='_x npm install'
alias pnmins='_x npm install --save'
alias pnmisd='_x npm install --save-dev'
alias pnmig='_x npm install -g'
alias pnmrm='_x npm uninstall'
alias pnmrms='_x npm uninstall --save'
alias pnmrmd='_x npm uninstall --save-dev'
alias pnmrmg='_x npm uninstall -g'
alias pnmup='_x npm update'
alias pnmout='_x npm outdated'
alias pnmls='_x npm list'
alias pnmlsg='_x npm list -g --depth=0'
alias pnmrun='_x npm run'
alias pnmt='_x npm test'
alias pnmb='_x npm run build'
alias pnmd='_x npm run dev'
alias pnms='_x npm run start'
alias pnmlnt='_x npm run lint'
alias pnmfmt='_x npm run format'
alias pnmpub='_x npm publish'
alias pnmvers='_x npm version'
alias pnmhr='_x npm run'
alias pnmcx='_x npm cache clean --force'
alias pnmaud='_x npm audit'
alias pnmaudf='_x npm audit fix'
alias pnmwho='_x npm whoami'
alias pnmlog='_x npm login'
alias pnmdc='_x npm docs'
alias pnmbug='_x npm bugs'
alias pnmrepo='_x npm repo'
alias pnmex='_x npm exec'
alias pnmwhy='_x npm why'
alias pnmdedup='_x npm dedupe'
alias pnmci='_x npm ci'
alias pnmprune='_x npm prune'
alias pnpn='_x pnpm'
alias pnpni='_x pnpm install'
alias pnpnr='_x pnpm run'
alias pnpnd='_x pnpm run dev'
alias pnpnb='_x pnpm run build'
alias pnpnt='_x pnpm test'
alias pnpnl='_x pnpm run lint'
alias pnpna='_x pnpm add'
alias pnpnad='_x pnpm add -D'
alias pnpnag='_x pnpm add -g'
alias pnpnrm='_x pnpm remove'
alias pnpnup='_x pnpm update'
alias pnpnout='_x pnpm outdated'
alias pnpnls='_x pnpm list'
alias pnpnlsg='_x pnpm list -g'
alias pnpninit='_x pnpm init'
alias pnpnpub='_x pnpm publish'
alias pnpnex='_x pnpm exec'
alias pnpnst='_x pnpm store'
alias pnpnstp='_x pnpm store prune'
alias pnpnstst='_x pnpm store status'
alias pcr='_x cargo'
alias pcrbl='_x cargo build'
alias pcrblr='_x cargo build --release'
alias pcrbn='_x cargo bench'
alias pcrun='_x cargo run'
alias pcrrunr='_x cargo run --release'
alias pcrt='_x cargo test'
alias pcrtf='_x cargo test -- --nocapture'
alias pcrck='_x cargo check'
alias pcrcl='_x cargo clippy'
alias pcrfmt='_x cargo fmt'
alias pcrfix='_x cargo fix'
alias pcrdoc='_x cargo doc'
alias pcrpub='_x cargo publish'
alias pcrup='_x cargo update'
alias pcrau='_x cargo outdated'
alias pcradd='_x cargo add'
    alias pcrrm='_x cargo remove'
alias pcrcln='_x cargo clean'
alias pcrinit='_x cargo init'
alias pcrnew='_x cargo new'
alias pcrw='_x cargo watch'
alias pcrl='_x cargo +nightly'
alias pcret='_x cargo expand'
alias pgo='_x go'
alias pgorun='_x go run'
alias pgob='_x go build'
alias pgobld='_x go build -o'
alias pgoget='_x go get'
alias pgoin='_x go install'
alias pgot='_x go test'
alias pgotv='_x go test -v ./...'
alias pgotc='_x go test -cover ./...'
alias pgom='_x go mod'
alias pgomi='_x go mod init'
alias pgomt='_x go mod tidy'
alias pgomv='_x go mod vendor'
alias pgomd='_x go mod download'
alias pgomgl='_x go mod graph'
alias pgomwh='_x go mod why'
alias pgof='_x go fmt ./...'
alias pgov='_x go vet ./...'
alias pgoenv='_x go env'
alias pgocln='_x go clean -cache'
alias pgodoc='_x go doc'
alias pgover='_x go version'
alias pgogen='_x go generate'
alias pgolint='golint ./...'
alias pgost='_x go tool pprof'
alias ppy='_x python3'
alias ppys='_x python3 -S'
alias ppyi='_x python3 -i'
alias ppym='_x python3 -m'
alias ppyhttp='_x python3 -m http.server'
alias ppyjson='_x python3 -m json.tool'
alias ppyv='_x python3 -m venv'
alias ppyactivate='source .venv/bin/activate'
alias ppypip='_x python3 -m pip'
alias ppypia='_x pip install'
alias ppypir='_x pip install -r requirements.txt'
alias ppyfreeze='_x pip freeze > requirements.txt'
alias ppyinst='_x pip list'
alias ppyout='_x pip list --outdated'
alias ppyt='_x python3 -m pytest'
alias ppytv='_x python3 -m pytest -v'
alias ppyun='_x python3 -m unittest'
alias ppyvrb='_x python3 -m unittest -v'
alias ppycov='_x python3 -m pytest --cov'
alias ppyblack='_x python3 -m black'
alias ppyflk='_x python3 -m flake8'
alias ppymb='_x python3 -m mypy'
alias ppylint='_x python3 -m pylint'
alias ppyband='_x python3 -m bandit'
alias ppysa='_x python3 -m safety check'
alias ppyuv='_x pip install uv && uv'
alias ppytut='_x python3 -m pendulum'
alias ppychk='_x python3 -m py_compile'
alias ppycfg='_x python3 -m site'
alias ppyupip='_x python3 -m pip install --upgrade pip'
alias psh='_x ssh'
alias psha='_x ssh -A'
alias pshc='ssh-copy-id'
alias pshk='ssh-keygen'
alias pshkr='ssh-keygen -R'
alias pshkf='ssh-keygen -F'
alias pshK='_x ssh -o StrictHostKeyChecking=no'
alias pshp='_x ssh -p'
alias pshj='_x ssh -J'
alias pshl='_x ssh -L'
alias pshr='_x ssh -R'
alias pshD='_x ssh -D'
alias pshv='_x ssh -v'
alias pshf='_x ssh -f'
alias pshN='_x ssh -N'
alias pshcp='_x scp -r'
alias pshrsync='_x rsync -avz -e ssh'
alias pgg='_x gpg'
alias pggc='_x gpg -c'
alias pgge='_x gpg -e'
alias pggd='_x gpg -d'
alias pggs='_x gpg -s'
alias pggv='_x gpg --verify'
alias pggls='_x gpg --list-keys'
alias pgglssec='_x gpg --list-secret-keys'
alias pgglo='_x gpg --list-keys --keyid-format LONG'
alias pggks='_x gpg --list-keys | grep "^pub\|^sub"'
alias pggk='_x gpg --keyserver keyserver.ubuntu.com --search-keys'
alias pggrecv='_x gpg --recv-keys'
alias pggen='_x gpg --full-generate-key'
alias pggexp='_x gpg --export -a'
alias pggimp='_x gpg --import'
alias pggxprt='_x gpg --export-secret-keys -a'
alias pggdel='_x gpg --delete-key'
alias pggdels='_x gpg --delete-secret-key'
alias pggsign='_x gpg --sign-key'
alias pggenc='_x gpg --encrypt'
alias pggchm='_x gpg --change-passphrase'
alias pggkys='_x gpg --show-key'
alias pggarm='_x gpg --armor'
alias pggcle='_x gpgconf --kill gpg-agent'
alias pggrel='_x gpgconf --reload gpg-agent'
alias psys='cat /etc/os-release'
alias psysk='uname -a'
alias psysh='hostnamectl'
alias psyblk='lsblk'
alias psyld='uptime'
alias psym='free -h'
alias psyd='df -h'
alias psyc='lscpu'
alias psyp='ps aux | head -20'
alias psyu='who'
alias psyw='who -b'
alias psyl='last'
alias psyda='date'
alias psyche='cal'
    alias psymod='lsmod'
alias psypci='lspci'
alias psyusb='lsusb'
alias psydm='dmesg -T'
alias psykrn='uname -r'
alias pnet='ip addr'
alias pnetl='ip link'
alias pnetr='ip route'
alias pnetn='ip neigh'
alias pnets='ip -stats'
alias pnetns='ip netns'
alias pnslk='nslookup'
alias pnetst='ss -tulanp'
alias pnetstt='ss -tunap'
alias pnets4='ss -t4'
alias pnetstl='ss -tlnp'
alias pnetfw='iptables -L -n -v'
alias pnetfw6='ip6tables -L -n -v'
alias pnetm='nmap -sn'
alias pnetmp='nmap -sV -sC'
alias pnett='traceroute'
alias pnetp='ping -c 4'
alias pnetpf='ping -c 100 -f'
alias pnetd='dig'
alias pnetdns='dig +short'
alias pneth='host'
alias pnetw='wget -c'
alias pnetcur='curl -fsSL'
alias pnetmyip='curl -fsSL ifconfig.me'
alias pnetdh='dhclient'
alias pnettcp='tcptraceroute'
alias pnetbw='iperf3'
alias pnetwbw='speedtest-cli'
alias pproc='ps auxf'
alias pproca='ps aux'
alias pprocf='ps aux | grep'
alias pproct='_x pstree'
alias pprocpid='_x pgrep -f'
alias pprock='kill -9'
alias pprocterm='kill -15'
alias pprocpk='_x pkill -f'
alias pprocn='nice -n'
alias pprocrn='renice -n'
alias pprocnohup='nohup'
alias pprocnice='nice -n 19'
alias pproci='iotop -o'
alias pprocs='ps --sort=-%cpu | head'
alias ptexg='grep'
alias ptexgr='grep -r'
alias ptexgi='grep -i'
alias ptexv='grep -v'
alias ptexl='grep -l'
alias ptexc='grep -c'
alias ptexs='sed'
alias ptexsr='sort'
alias ptexx='sed -n'
alias ptexa='awk'
alias ptexaw='awk "{print}"'
alias ptexu='uniq'
alias ptexuc='sort | uniq -c | sort -rn'
alias ptexwc='wc -l'
alias ptexww='wc -w'
alias ptexcut='cut -d'
alias ptextr='tr'
alias ptexpd='paste -d'
alias ptexcol='column -t'
alias ptexdf='diff'
alias ptexdiy='diff -y'
alias ptexhd='head -n'
alias ptextl='tail -n'
alias ptextf='tail -f'
alias ptexxm='xmllint --format'
alias ptexj='_x python3 -m json.tool'
alias ptexy='yq eval'
alias ptexb='bat --language'
alias ptexxd='xxd'
alias psec='openssl version'
alias pseca='openssl enc -aes-256-cbc -salt -in'
alias psecd='openssl enc -d -aes-256-cbc -in'
alias psecr='openssl rand -hex'
alias psecrs='openssl rand -base64'
alias pseck='openssl genrsa -out'
alias psecreq='openssl req -new -key'
alias psecx='openssl x509 -in'
alias psecs='openssl s_client -connect'
alias psecv='openssl verify'
alias psech='sha256sum'
alias psecsh='shasum -a 256'
alias psecmd5='md5sum'
alias psecshred='shred -uz'
alias psecharden='chmod 600'
alias pfilecp='cp -i'
alias pfilemv='mv -i'
alias pfilerm='rm -i'
alias pfilecpf='cp -f'
alias pfilemvf='mv -f'
alias pfilermf='rm -f'
alias pfilermr='rm -r'
alias pfilersync='_x rsync -avz'
alias pfilemk='mkdir -p'
alias pfilechx='chmod +x'
alias pfilechm='chmod'
alias pfileown='chown'
alias pfilegrp='chgrp'
alias pfileln='ln -sf'
alias pfilebak='cp -r "$1" "$1.bak"'
alias pfiletouch='touch'
alias pfileread='cat -n'
alias pfileless='less -N'
alias pfilehead='head -n'
alias pfiletail='tail -n'
alias pfilefoll='tail -f'
alias pfilewatch='watch -n 2'
alias pfilefind='find . -name'
alias pfilerca='fd'
alias pfiletree='_x tree'
alias pfilestat='stat'
alias parcx='tar -xf'
alias parct='tar -czf'
alias parctxz='tar -xJf'
alias parctzx='tar -cJf'
alias parcjx='tar -xjf'
alias parcjc='tar -cjf'
alias parctl='tar -tvf'
alias parczip='zip -r'
alias parczipd='zip -r -d .'
alias parcunz='unzip'
alias parcunzl='unzip -l'
alias parcunzt='unzip -t'
alias parc7z='7z x'
alias parc7za='7z a'
alias parc7zl='7z l'
alias parc7zt='7z t'
alias parcr='unrar x'
alias parcgl='gunzip'
alias parcgz='gzip'
alias parcbl='bunzip2'
alias parcbz='bzip2'
alias parcxl='unxz'
alias parcxz='xz'
alias pdbm='mysql -u root -p'
alias pdbmd='mysqldump -u root -p'
alias pdbms='mysql -u root -p -e'
alias pdbps='psql -U postgres'
alias pdbpsd='pg_dump -U postgres'
alias pdbsq='sqlite3'
alias pdbredis='redis-cli'
alias pdbredping='redis-cli ping'
alias pdbmong='mongosh'
alias pdevv='nvim'
alias pdevcode='code'
alias pdevmake='make'
alias pdevjust='just'
alias pdevlazy='lazygit'
alias pdevyazi='yazi'
alias pdevzellij='zellij'
alias pdevgit='git'
alias pdevgh='gh'
alias pdevglb='glab'
alias pcaws='aws'
alias pcawss3='aws s3 ls'
alias pcawsec2='aws ec2 describe-instances'
alias pcawsiam='aws iam list-users'
alias pcawsinfo='aws sts get-caller-identity'
alias pcgcl='gcloud'
alias pcgclls='gcloud compute instances list'
alias pcgclgke='gcloud container clusters list'
alias pcaz='az'
alias pcazls='az vm list'
alias pcazaks='az aks list'
alias pmediaff='ffmpeg -i'
alias pmediafp='ffprobe'
alias pmediafg='ffplay'
alias pmediaimg='convert'
alias pmediaimgr='convert -resize'
alias pmediaimgg='convert -gravity center'
alias pmediaimgq='convert -quality 85'
alias pmediaexif='exiftool'
alias putiltime='date +%s'
alias putilnow='date +"%F %T"'
alias putiltoday='date +%F'
alias putilsum='sha256sum'
alias putilmd5='md5sum'
alias putilb64='base64'
alias putilb64d='base64 -d'
alias putiluuid='uuidgen'
alias putilpw='openssl rand -base64 16'
alias putilurle='_x python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))"'
alias putilurld='_x python3 -c "import urllib.parse,sys; print(urllib.parse.unquote(sys.argv[1]))"'
alias putiljson='_x python3 -m json.tool'
alias putilyaml='_x python3 -c "import sys,yaml,json; print(yaml.dump(json.load(sys.stdin)))"'
alias putilxml='xmllint --format'
alias putiltimer='start=$(date +%s); "$@"; code=$?; end=$(date +%s); echo "elapsed: $((end-start))s"; return $code'
alias putilbench='hyperfine'
alias putilrand='shuf -i'
alias putilseq='seq'
alias putilcls='clear'
alias puticlean='rm -rf ~/.cache/*'
alias putilps='ps auxf'
alias putilkill='kill -9'
alias putilhs='history | grep'
alias putilhist='history'
alias putilsr='source "$HOME/.zshrc"'
alias pfd='fd'
alias pbat='bat'
alias prg='rg'
alias peza='eza'
alias pdu='dust'
alias pdf='duf'
alias ptop='btop'

if command -v atuin >/dev/null 2>&1; then
    alias atu='atuin'
    alias atus='atuin search'
    alias atul='atuin login'
    alias atur='atuin register'
    alias atusync='atuin sync'
    alias atust='atuin status'
    alias atuh='atuin history'
    alias atuhl='atuin history list'
    alias atustats='atuin stats'
fi

if command -v direnv >/dev/null 2>&1; then
    alias dir='direnv'
    alias dira='direnv allow'
    alias dird='direnv deny'
    alias dirr='direnv reload'
    alias dire='direnv edit'
    alias dirv='direnv view'
    alias dirh='direnv hook'
fi

if command -v zoxide >/dev/null 2>&1; then
    alias z='zoxide'
    alias zi='zoxide query -i'
fi

if command -v fzf >/dev/null 2>&1; then
    alias fz='fzf'
    alias fzp='fzf --preview'
fi

if command -v gh >/dev/null 2>&1; then
    alias gh='gh'
    alias ghs='gh status'
    alias ghp='gh pr'
    alias ghpl='gh pr list'
    alias ghpc='gh pr create'
    alias ghpm='gh pr merge'
    alias ghco='gh pr checkout'
    alias ghi='gh issue'
    alias ghil='gh issue list'
    alias ghic='gh issue create'
    alias ghr='gh release'
    alias ghrl='gh release list'
    alias ghrc='gh release create'
    alias ghrd='gh release download'
    alias ghrv='gh release view'
    alias ghrep='gh repo'
    alias ghrepv='gh repo view'
    alias ghcl='gh repo clone'
    alias ghcr='gh repo create'
    alias ghw='gh workflow'
fi

if command -v fastfetch >/dev/null 2>&1; then
    alias ffet='_x fastfetch'
    alias ffetl='_x fastfetch -l'
fi

if command -v hyperfine >/dev/null 2>&1; then
    alias hf='hyperfine'
    alias hfw='hyperfine --warmup'
fi

if command -v delta >/dev/null 2>&1; then
    alias delta='delta'
fi

if command -v jq >/dev/null 2>&1; then
    alias jq='jq'
    alias jqc='jq -c'
    alias jqr='jq -r'
    alias jqs='jq -S'
fi

if command -v yq >/dev/null 2>&1; then
    alias yq='yq'
    alias yqe='yq eval'
    alias yqp='yq eval -P'
fi

if command -v glow >/dev/null 2>&1; then
    alias glow='glow'
    alias glows='glow -s'
fi

if command -v dog >/dev/null 2>&1; then
    alias dog='dog'
    alias doga='dog A'
    alias dogmx='dog MX'
    alias dogns='dog NS'
    alias dogtxt='dog TXT'
fi

if command -v http >/dev/null 2>&1; then
    alias https='https'
fi

if command -v procs >/dev/null 2>&1 || command -v bottom >/dev/null 2>&1; then
    alias procs='procs'
fi

if command -v bandwhich >/dev/null 2>&1; then
    alias band='bandwhich'
    alias bandl='bandwhich -r'
fi

if command -v gping >/dev/null 2>&1; then
    alias gping='gping'
fi

if command -v ouch >/dev/null 2>&1; then
    alias ouch='ouch'
    alias ouchd='ouch decompress'
    alias ouchc='ouch compress'
    alias ouchl='ouch list'
fi

if command -v sd >/dev/null 2>&1; then
    alias sd='sd'
fi

if command -v navi >/dev/null 2>&1; then
    alias navi='navi'
    alias naviq='navi --query'
fi

if command -v tldr >/dev/null 2>&1 || command -v tealdeer >/dev/null 2>&1; then
    alias tldr='tldr 2>/dev/null || tealdeer'
fi

if command -v lazydocker >/dev/null 2>&1; then
    alias lzd='lazydocker'
fi

if command -v vivid >/dev/null 2>&1; then
    alias vivid='vivid'
    alias vividg='vivid generate'
    alias vividt='vivid themes'
fi

if command -v chezmoi >/dev/null 2>&1; then
    alias chez='chezmoi'
    alias cheza='chezmoi apply'
    alias chezd='chezmoi diff'
    alias cheze='chezmoi edit'
    alias chezad='chezmoi add'
    alias chezup='chezmoi update'
    alias chezcd='chezmoi cd'
    alias chezi='chezmoi init'
    alias chezs='chezmoi status'
    alias chezr='chezmoi re-add'
fi

if command -v act >/dev/null 2>&1; then
    alias act='act'
    alias actl='act -l'
    alias actp='act -p'
    alias actpush='act push'
    alias actpr='act pull_request'
    alias actw='act -W'
fi

if command -v vault >/dev/null 2>&1; then
    alias vault='vault'
    alias vaults='vault status'
    alias vaultl='vault login'
    alias vaultkv='vault kv'
    alias vaultkvg='vault kv get'
    alias vaultkvp='vault kv put'
    alias vaultkvd='vault kv delete'
    alias vaultr='vault read'
    alias vaultw='vault write'
fi

if command -v kind >/dev/null 2>&1; then
    alias kind='kind'
    alias kindc='kind create cluster'
    alias kindd='kind delete cluster'
    alias kindg='kind get clusters'
    alias kindk='kind get kubeconfig'
fi

if command -v vagrant >/dev/null 2>&1; then
    alias vg='vagrant'
    alias vgu='vagrant up'
    alias vgh='vagrant halt'
    alias vgd='vagrant destroy'
    alias vgs='vagrant status'
    alias vgssh='vagrant ssh'
    alias vgp='vagrant provision'
    alias vgreload='vagrant reload'
    alias vgbox='vagrant box list'
fi

if command -v packer >/dev/null 2>&1; then
    alias pk='packer'
    alias pkb='packer build'
    alias pkv='packer validate'
    alias pkf='packer fmt'
    alias pkinit='packer init'
fi

if command -v age >/dev/null 2>&1; then
    alias age='age'
    alias agee='age -e'
    alias aged='age -d'
    alias agegen='age-keygen'
fi

if command -v sops >/dev/null 2>&1; then
    alias sops='sops'
    alias sopse='sops -e'
    alias sopsd='sops -d'
    alias sopsi='sops -i'
fi

if command -v argocd >/dev/null 2>&1; then
    alias argo='argocd'
    alias argol='argocd login'
    alias argos='argocd app sync'
    alias argog='argocd app get'
    alias argolist='argocd app list'
    alias argodiff='argocd app diff'
fi

if command -v minikube >/dev/null 2>&1; then
    alias mk='minikube'
    alias mks='minikube start'
    alias mkstop='minikube stop'
    alias mkd='minikube delete'
    alias mkst='minikube status'
    alias mkpa='minikube pause'
    alias mkun='minikube unpause'
    alias mkdash='minikube dashboard'
    alias kip='minikube ip'
    alias mkadd='minikube addons list'
fi

if command -v k0s >/dev/null 2>&1; then
    alias k0='k0s'
    alias k0s='k0s status'
    alias k0c='k0s kubectl'
    alias k0start='k0s controller'
fi

if command -v talosctl >/dev/null 2>&1; then
    alias tals='talosctl version'
    alias talc='talosctl config'
fi

if command -v skopeo >/dev/null 2>&1; then
    alias sk='skopeo'
    alias skc='skopeo copy'
    alias skl='skopeo list-tags'
    alias ski='skopeo inspect'
    alias sks='skopeo sync'
fi

if command -v dive >/dev/null 2>&1; then
    alias dive='dive'
fi

if command -v hadolint >/dev/null 2>&1; then
    alias hado='hadolint'
fi

if command -v trivy >/dev/null 2>&1; then
    alias trivy='trivy'
    alias trivyi='trivy image'
    alias trivyf='trivy fs'
    alias trivyr='trivy repo'
fi

if command -v cosign >/dev/null 2>&1; then
    alias cosign='cosign'
    alias cosignv='cosign verify'
    alias cosigns='cosign sign'
fi

alias try='curl -fsSL https://cht.sh'
alias tldrl='curl -fsSL https://cheat.sh'

if command -v rclone >/dev/null 2>&1; then
    alias rcl='rclone'
    alias rclls='rclone ls'
    alias rclsync='rclone sync'
    alias rclc='rclone copy'
    alias rclmv='rclone move'
fi

if command -v restic >/dev/null 2>&1; then
    alias rest='restic'
    alias restb='restic backup'
    alias restr='restic restore'
    alias rests='restic snapshots'
    alias restc='restic check'
fi

if command -v borg >/dev/null 2>&1; then
    alias borg='borg'
    alias borgc='borg create'
    alias borge='borg extract'
    alias borgl='borg list'
    alias borgi='borg info'
    alias borgd='borg delete'
    alias borgpr='borg prune'
fi

if command -v kopia >/dev/null 2>&1; then
    alias kop='kopia'
    alias kops='kopia snapshot create'
    alias kopl='kopia snapshot list'
    alias kopm='kopia mount'
    alias kopc='kopia cache clear'
fi

alias pclr='clear'
alias pdup='_x docker compose up -d'
alias pddown='_x docker compose down'

alias py='_x python3'
alias ip='ip -br addr'
alias free='free -h'
alias pscpu='ps aux --sort=-%cpu'
alias psmem='ps aux --sort=-%mem'
alias psuser='ps -u'
alias nslookup='nslookup'
alias curl='curl'
alias tar='tar'
alias unzip='unzip'
alias ssh='_x ssh'
alias scp='scp'
alias mkdir='mkdir -p'
alias rmdir='rmdir'
alias chmod='chmod'
alias xargs='xargs'
alias touch='touch'
alias watch='watch'
alias date='date'
alias bc='bc -l'
alias expr='expr'
alias printf='printf'
alias duk='du -sh * | sort -h'
alias psi='ps aux | grep -i'
alias psaux='ps aux'
alias psf='ps auxf'

alias psxl='ps aux --forest'
alias iftop='sudo iftop'
alias dnst='dig +short'
alias idg='id -g'
alias idu='id -u'
alias groups='groups'
alias last='last'
alias w='w'
alias tmpdir='cd $(mktemp -d)'
alias math='_x python3 -c'
alias seq='seq'
alias shuffle='shuf'
alias expand='expand'
alias unexpand='unexpand'
alias od='od'
alias strings='strings'
alias comm='comm'
alias grepw='grep -w'
alias grepr='grep -r'
alias grex='grep -r --exclude-dir=.git --exclude-dir=node_modules'
alias du2='du -sh --max-depth=2'
alias dux='du -sh * | sort -h'
alias pr='pr'
alias rsample='shuf -n'
alias rstring='_x python3 -c "import secrets; print(secrets.token_hex())"'
alias serv='_x systemctl'
alias jrnl='_x journalctl'
alias pod='_x podman'
alias podps='_x podman ps'
alias podrun='_x podman run -it --rm'
alias podimg='_x podman images'
alias dstats='_x docker stats --no-stream'
alias kns='_x kubectl config set-context --namespace'
alias kpf='_x kubectl port-forward'

# ---- Clipboard (macOS pbcopy/pbpaste mapped to Linux equivalents) ----
if command -v xclip >/dev/null 2>&1; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
elif command -v wl-copy >/dev/null 2>&1; then
    alias pbcopy='wl-copy'
    alias pbpaste='wl-paste'
fi
alias pbc='pbcopy'
alias pbp='pbpaste'
alias cpy='pbcopy'
alias pst='pbpaste'

alias path="echo \$PATH | tr ':' '\\n' | sort -u"
alias envg="env | grep -i"
alias nohist='unset HISTFILE'
alias clhist='HISTSIZE=0; HISTSIZE=5000'
alias histgrep='history | grep -i'
alias cleanshell='env - bash --norc --noprofile'
alias tmp='cd /tmp'
alias tstamp='stamp'
alias topcmds='topcommands'
alias port='_x ss -tlnp 2>/dev/null || _x netstat -tlnp 2>/dev/null || echo "no port tool"'
alias ports='_x ss -tulpn 2>/dev/null || _x netstat -tulpn 2>/dev/null || _x lsof -i -n -P 2>/dev/null'
alias lw='ls -ldh $(pwd)'
alias le="ls | grep -o '.[^.]*$' | sort | uniq"
alias dsstore='find . -name ".DS_Store" -type f -delete -print 2>/dev/null'
alias mirrorsite='_x wget -m -k -K -E -e robots=off 2>/dev/null || echo "wget needed"'
alias ff='find . -type f -name'
alias gwip='git add -A && git rm $(git ls-files --deleted) 2>/dev/null; git commit --no-verify -m "wip"'
alias gwipe='git reset --hard && git clean --force -df'
alias nah='git reset --hard && git clean -df'
alias gbage='for k in $(git branch -a | sed "s/^..//;s/ ->.*//" 2>/dev/null); do echo -e "$(git show --pretty=format:"%ci %cr" $k -- 2>/dev/null | head -1)\t$k"; done | sort -r'
alias gmn='git merge --no-ff --no-commit'
dash() { cd -; }
alias -- -='dash'
alias :q='exit'
alias q='exit'
alias sep='printf "=%.0s" $(seq 1 $(tput cols))'
alias countfiles='for t in files links directories; do echo $(find . -type ${t:0:1} 2>/dev/null | wc -l) $t; done 2>/dev/null'
if command -v yay >/dev/null 2>&1 && command -v fzf >/dev/null 2>&1; then
    alias yayf="yay -Slq | fzf --multi --preview 'yay -Sii {1}' --preview-window=down:75% | xargs -ro yay -S"
fi
if command -v xdotool >/dev/null 2>&1 && command -v xclip >/dev/null 2>&1; then
    alias clickpaste='sleep 3; xdotool type "$(xclip -o -selection clipboard)"'
fi
alias ipa='_x ip -br addr 2>/dev/null || _x ifconfig 2>/dev/null'
alias net='_x ip -br addr 2>/dev/null || _x ifconfig 2>/dev/null'
alias trace='_x traceroute 2>/dev/null || _x traceroute6 2>/dev/null || echo "no traceroute"'
alias pid='_x pgrep -f'
alias disks='_x lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINT 2>/dev/null || _x diskutil list 2>/dev/null'
alias smart='_x sudo smartctl -a 2>/dev/null || echo "no smartctl"'
alias sha='_x shasum -a 256 2>/dev/null || _x sha256sum 2>/dev/null'
alias hex='_x xxd 2>/dev/null || _x od -A x -t x1z 2>/dev/null'
alias cht='_x curl -fsSL "https://cht.sh/$1" 2>/dev/null || echo "curl needed"'
alias learn='_x curl -fsSL "https://learnxinyminutes.com/docs/$1" 2>/dev/null'
if command -v docker >/dev/null 2>&1; then
    alias docker-ip="_x docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2>/dev/null"
fi
if command -v nvim >/dev/null 2>&1; then
    alias svi='sudo nvim'
    alias vis='nvim "+set si"'
elif command -v vim >/dev/null 2>&1; then
    alias svi='sudo vim'
    alias vis='vim "+set si"'
fi

alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gap='git add --patch'
alias gau='git add -u'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbm='git branch -m'
alias gbc='git branch --show-current'
alias gc='git commit -v'
alias gca='git commit -a -v'
alias gcam='git commit --amend --no-edit'
alias gcan='git commit --amend --no-verify'
alias gcne='git commit --no-edit'
alias gcnv='git commit --no-verify'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdw='git diff --word-diff'
alias gds='git diff --stat'
alias gf='git fetch'
alias gfa='git fetch --all'
alias gfr='git fetch --prune'
alias gi='git init'
alias gl='git log --oneline -n 20'
alias gla='git log --oneline --graph --all --decorate'
alias glg='git log --oneline --graph'
alias gp='git push'
alias gpo='git push origin'
alias gpoh='git push origin HEAD'
alias gpu='git push --set-upstream origin'
alias gpl='git pull'
alias gplr='git pull --rebase'
alias gr='git remote -v'
alias gra='git remote add'
alias grm='git remote remove'
alias grv='git remote -v'
alias gs='git status'
alias gss='git status --short'
alias gst='git stash'
alias gsta='git stash apply'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gstd='git stash drop'
alias gsw='git switch'
alias gswc='git switch --create'
alias gt='git tag'
alias gtl='git tag -l'
alias gtd='git tag -d'
alias gtop='gcd'
alias grh='git reset --hard'
alias grs='git reset --soft'
alias gm='git merge'
alias gmnf='git merge --no-ff'
alias gmt='git mergetool'
alias gmv='git mv'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'
alias grbs='git rebase --skip'
alias gcl='git clone'
alias gcl1='git clone --depth=1'
alias gbl='git blame'
alias gcf='git config'
alias gcfl='git config -l'
alias gk='gitk'
alias gkw='gitk --all'
alias gsh='git show'
alias gshs='git show --stat'
alias gshn='git show --name-only'
alias gdf='git difftool'
alias gcm='gcm'
alias gmm='gmm'

alias find='_x fd 2>/dev/null || find'
alias cat='_x bat --style=plain --paging=never 2>/dev/null || _x batcat --style=plain --paging=never 2>/dev/null || cat'
alias ls='_x eza --group-directories-first --icons 2>/dev/null || _x exa --group-directories-first 2>/dev/null || ls --color=auto 2>/dev/null || ls -G'
alias ll='_x eza -l --group-directories-first --icons 2>/dev/null || _x exa -l 2>/dev/null || ls -l'
alias la='_x eza -la --group-directories-first --icons 2>/dev/null || _x exa -la 2>/dev/null || ls -la'
alias tree='_x eza -T --icons 2>/dev/null || _x tree 2>/dev/null || echo "tree/eza needed"'
alias grep='_x rg --color=auto 2>/dev/null || grep --color=auto'
alias du='du -h'
alias df='df -h'
alias mkdir='mkdir -p'
alias wget='_x wget 2>/dev/null || _x curl -fSL -o 2>/dev/null || echo "no download tool"'
alias diff='_x delta 2>/dev/null || diff --color=auto 2>/dev/null || diff'
alias top='_x btop 2>/dev/null || _x htop 2>/dev/null || top'
alias ps='ps auxf'
alias ping='_x prettyping 2>/dev/null || ping'
alias dig='_x dog 2>/dev/null || dig'
alias man='_x tldr 2>/dev/null || man'
alias fd='_x fd 2>/dev/null || find'
alias duf='du -sh * | sort -h'
alias dud='du -sh ./* | sort -h'
alias dus='du -sh .[!.]* * 2>/dev/null | sort -h'
alias usage='du -sh * 2>/dev/null | sort -h'
alias duls='du -sm * | sort -n'
alias dirs='ls -d */'
alias ldir='ls -d */'
alias lf='find . -maxdepth 1 -type f -exec ls -lh {} + 2>/dev/null | sort -k5 -h'
alias lsof='_x lsof -i -P -n 2>/dev/null || echo "lsof needed"'
alias ports='_x ss -tlnp 2>/dev/null || _x netstat -tlnp 2>/dev/null || _x lsof -i -P -n 2>/dev/null | grep LISTEN'
alias listen='_x ss -tlnp 2>/dev/null || _x netstat -tlnp 2>/dev/null'
alias connections='_x ss -tunp 2>/dev/null || _x netstat -tunp 2>/dev/null'
alias myip='_x dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || _x curl -s ifconfig.me 2>/dev/null || echo "N/A"'
alias myipl='_x ip addr show scope global 2>/dev/null | grep -oP "inet \K[\d.]+" || _x ifconfig 2>/dev/null | grep "inet " | grep -v 127.0.0.1 | awk "{print \$2}"'
alias dns='_x dig +short'
alias flush='_x sudo resolvectl flush-caches 2>/dev/null || _x sudo systemd-resolve --flush-caches 2>/dev/null || _x sudo killall -HUP mDNSResponder 2>/dev/null || echo "no flush"'
alias speed='_x curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py 2>/dev/null | _x python3 - 2>/dev/null || echo "speedtest-cli needed"'
alias weather='_x curl -fsSL wttr.in 2>/dev/null || echo "curl needed"'
alias weather3='_x curl -fsSL "wttr.in?F" 2>/dev/null || echo "curl needed"'
alias moon='_x curl -fsSL "wttr.in/Moon" 2>/dev/null || echo "curl needed"'
alias json='python3 -m json.tool 2>/dev/null || echo "python3 needed"'
alias xml='_x xmllint --format - 2>/dev/null || echo "xmllint needed"'
alias yaml='_x python3 -c "import sys,yaml; yaml.dump(yaml.safe_load(sys.stdin), sys.stdout, default_flow_style=False)" 2>/dev/null || echo "python3+yaml needed"'
alias csv='_x python3 -c "import sys,csv; r=csv.reader(sys.stdin); [print(l) for l in r]" 2>/dev/null || column -t -s, 2>/dev/null'
alias ts='_x python3 -c "import sys,json; [print(json.dumps(eval(l))) for l in sys.stdin]" 2>/dev/null'

