background {
  monitor =
  path = screenshot
  blur_passes = 4
  blur_size = 10
  noise = 0.02
  contrast = 0.7
  brightness = 0.5
  vibrancy = 0.3
  vibrancy_darkness = 0.3
}

input-field {
  monitor =
  size = 280, 55
  outline_thickness = 2
  dots_size = 0.25
  dots_spacing = 0.45
  dots_center = true
  outer_color = rgb(88c0d0)
  inner_color = rgb(2e3440)
  font_color = rgb(d8dee9)
  fade_on_empty = true
  placeholder_text = <i>  unlock...</i>
  hide_input = false
  position = 0, -80
  halign = center
  valign = center
}

label {
  monitor =
  text = $TIME
  font_size = 64
  font_family = JetBrains Mono Nerd Font ExtraLight
  color = rgb(eceff4)
  position = 0, 60
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] date '+%A, %B %d, %Y'
  font_size = 16
  font_family = JetBrains Mono Nerd Font
  color = rgb(88c0d0)
  position = 0, 20
  halign = center
  valign = center
}
