status is-interactive; or exit
abbr -a gad 'git add'
abbr -a gadv 'git add --verbose'
abbr -a ga 'git add'
abbr -a gadf 'git add --force'
abbr -a gpu 'git push'
abbr -a gpuv 'git push --verbose'
abbr -a gp 'git push'
abbr -a gpuf 'git push --force'
abbr -a gco 'git commit'
abbr -a gcov 'git commit --verbose'
abbr -a gc 'git commit'
abbr -a gcof 'git commit --force'
abbr -a gch 'git checkout'
abbr -a gchv 'git checkout --verbose'
abbr -a gchf 'git checkout --force'
abbr -a gbr 'git branch'
abbr -a gbrv 'git branch --verbose'
abbr -a gb 'git branch'
abbr -a gbrf 'git branch --force'
abbr -a gst 'git status'
abbr -a gstv 'git status --verbose'
abbr -a gs 'git status'
abbr -a gstf 'git status --force'
abbr -a gdi 'git diff'
abbr -a gdiv 'git diff --verbose'
abbr -a gd 'git diff'
abbr -a gdif 'git diff --force'
abbr -a glo 'git log'
abbr -a glov 'git log --verbose'
abbr -a gl 'git log'
abbr -a glof 'git log --force'
abbr -a gme 'git merge'
abbr -a gmev 'git merge --verbose'
abbr -a gm 'git merge'
abbr -a gmef 'git merge --force'
abbr -a gre 'git rebase'
abbr -a grev 'git rebase --verbose'
abbr -a gr 'git rebase'
abbr -a gref 'git rebase --force'
abbr -a gsh 'git show'
abbr -a gshv 'git show --verbose'
abbr -a gshf 'git show --force'
abbr -a gfe 'git fetch'
abbr -a gfev 'git fetch --verbose'
abbr -a gf 'git fetch'
abbr -a gfef 'git fetch --force'
abbr -a gta 'git tag'
abbr -a gtav 'git tag --verbose'
abbr -a gt 'git tag'
abbr -a gtaf 'git tag --force'
abbr -a gbl 'git blame'
abbr -a gblv 'git blame --verbose'
abbr -a gblf 'git blame --force'
abbr -a gin 'git init'
abbr -a ginv 'git init --verbose'
abbr -a gi 'git init'
abbr -a ginf 'git init --force'
abbr -a ggr 'git grep'
abbr -a ggrv 'git grep --verbose'
abbr -a gg 'git grep'
abbr -a ggrf 'git grep --force'
abbr -a gcl 'git clean'
abbr -a gclv 'git clean --verbose'
abbr -a gclf 'git clean --force'
abbr -a gbi 'git bisect'
abbr -a gbiv 'git bisect --verbose'
abbr -a gbif 'git bisect --force'
abbr -a gwo 'git worktree'
abbr -a gwov 'git worktree --verbose'
abbr -a gw 'git worktree'
abbr -a gwof 'git worktree --force'
abbr -a kgpods 'kubectl get pods'
abbr -a kgepods 'kubectl get pods'
abbr -a kgsvc 'kubectl get svc'
abbr -a kgesvc 'kubectl get svc'
abbr -a kgdeploy 'kubectl get deploy'
abbr -a kgedeploy 'kubectl get deploy'
abbr -a kgcm 'kubectl get cm'
abbr -a kgecm 'kubectl get cm'
abbr -a kgsecret 'kubectl get secret'
abbr -a kgesecret 'kubectl get secret'
abbr -a kgnode 'kubectl get node'
abbr -a kgenode 'kubectl get node'
abbr -a kgns 'kubectl get ns'
abbr -a kgens 'kubectl get ns'
abbr -a kging 'kubectl get ing'
abbr -a kgeing 'kubectl get ing'
abbr -a kgpv 'kubectl get pv'
abbr -a kgepv 'kubectl get pv'
abbr -a kgpvc 'kubectl get pvc'
abbr -a kgepvc 'kubectl get pvc'
abbr -a kgsts 'kubectl get sts'
abbr -a kgests 'kubectl get sts'
abbr -a kgds 'kubectl get ds'
abbr -a kgeds 'kubectl get ds'
abbr -a kgjob 'kubectl get job'
abbr -a kgejob 'kubectl get job'
abbr -a kgcj 'kubectl get cj'
abbr -a kgecj 'kubectl get cj'
abbr -a kgrs 'kubectl get rs'
abbr -a kgers 'kubectl get rs'
abbr -a kgrc 'kubectl get rc'
abbr -a kgerc 'kubectl get rc'
abbr -a kgquota 'kubectl get quota'
abbr -a kgequota 'kubectl get quota'
abbr -a kglimitrange 'kubectl get limitrange'
abbr -a kgelimitrange 'kubectl get limitrange'
abbr -a kghpa 'kubectl get hpa'
abbr -a kgehpa 'kubectl get hpa'
abbr -a kgpdb 'kubectl get pdb'
abbr -a kgepdb 'kubectl get pdb'
abbr -a kgsa 'kubectl get sa'
abbr -a kgesa 'kubectl get sa'
abbr -a kdpods 'kubectl describe pods'
abbr -a kdepods 'kubectl describe pods'
abbr -a kdsvc 'kubectl describe svc'
abbr -a kdesvc 'kubectl describe svc'
abbr -a kddeploy 'kubectl describe deploy'
abbr -a kdedeploy 'kubectl describe deploy'
abbr -a kdcm 'kubectl describe cm'
abbr -a kdecm 'kubectl describe cm'
abbr -a kdsecret 'kubectl describe secret'
abbr -a kdesecret 'kubectl describe secret'
abbr -a kdnode 'kubectl describe node'
abbr -a kdenode 'kubectl describe node'
abbr -a kdns 'kubectl describe ns'
abbr -a kdens 'kubectl describe ns'
abbr -a kding 'kubectl describe ing'
abbr -a kdeing 'kubectl describe ing'
abbr -a kdpv 'kubectl describe pv'
abbr -a kdepv 'kubectl describe pv'
abbr -a kdpvc 'kubectl describe pvc'
abbr -a kdepvc 'kubectl describe pvc'
abbr -a kdsts 'kubectl describe sts'
abbr -a kdests 'kubectl describe sts'
abbr -a kdds 'kubectl describe ds'
abbr -a kdeds 'kubectl describe ds'
abbr -a kdjob 'kubectl describe job'
abbr -a kdejob 'kubectl describe job'
abbr -a kdcj 'kubectl describe cj'
abbr -a kdecj 'kubectl describe cj'
abbr -a kdrs 'kubectl describe rs'
abbr -a kders 'kubectl describe rs'
abbr -a kdrc 'kubectl describe rc'
abbr -a kderc 'kubectl describe rc'
abbr -a kdquota 'kubectl describe quota'
abbr -a kdequota 'kubectl describe quota'
abbr -a kdlimitrange 'kubectl describe limitrange'
abbr -a kdelimitrange 'kubectl describe limitrange'
abbr -a kdhpa 'kubectl describe hpa'
abbr -a kdehpa 'kubectl describe hpa'
abbr -a kdpdb 'kubectl describe pdb'
abbr -a kdepdb 'kubectl describe pdb'
abbr -a kdsa 'kubectl describe sa'
abbr -a kdesa 'kubectl describe sa'
abbr -a kepods 'kubectl edit pods'
abbr -a kedpods 'kubectl edit pods'
abbr -a kesvc 'kubectl edit svc'
abbr -a kedsvc 'kubectl edit svc'
abbr -a kedeploy 'kubectl edit deploy'
abbr -a keddeploy 'kubectl edit deploy'
abbr -a kecm 'kubectl edit cm'
abbr -a kedcm 'kubectl edit cm'
abbr -a kesecret 'kubectl edit secret'
abbr -a kedsecret 'kubectl edit secret'
abbr -a kenode 'kubectl edit node'
abbr -a kednode 'kubectl edit node'
abbr -a kens 'kubectl edit ns'
abbr -a kedns 'kubectl edit ns'
abbr -a keing 'kubectl edit ing'
abbr -a keding 'kubectl edit ing'
abbr -a kepv 'kubectl edit pv'
abbr -a kedpv 'kubectl edit pv'
abbr -a kepvc 'kubectl edit pvc'
abbr -a kedpvc 'kubectl edit pvc'
abbr -a kests 'kubectl edit sts'
abbr -a kedsts 'kubectl edit sts'
abbr -a keds 'kubectl edit ds'
abbr -a kedds 'kubectl edit ds'
abbr -a kejob 'kubectl edit job'
abbr -a kedjob 'kubectl edit job'
abbr -a kecj 'kubectl edit cj'
abbr -a kedcj 'kubectl edit cj'
abbr -a kers 'kubectl edit rs'
abbr -a kedrs 'kubectl edit rs'
abbr -a kerc 'kubectl edit rc'
abbr -a kedrc 'kubectl edit rc'
abbr -a kequota 'kubectl edit quota'
abbr -a kedquota 'kubectl edit quota'
abbr -a kelimitrange 'kubectl edit limitrange'
abbr -a kedlimitrange 'kubectl edit limitrange'
abbr -a kehpa 'kubectl edit hpa'
abbr -a kedhpa 'kubectl edit hpa'
abbr -a kepdb 'kubectl edit pdb'
abbr -a kedpdb 'kubectl edit pdb'
abbr -a kesa 'kubectl edit sa'
abbr -a kedsa 'kubectl edit sa'
abbr -a klpods 'kubectl logs pods'
abbr -a klopods 'kubectl logs pods'
abbr -a klsvc 'kubectl logs svc'
abbr -a klosvc 'kubectl logs svc'
abbr -a kldeploy 'kubectl logs deploy'
abbr -a klodeploy 'kubectl logs deploy'
abbr -a klcm 'kubectl logs cm'
abbr -a klocm 'kubectl logs cm'
abbr -a klsecret 'kubectl logs secret'
abbr -a klosecret 'kubectl logs secret'
abbr -a klnode 'kubectl logs node'
abbr -a klonode 'kubectl logs node'
abbr -a klns 'kubectl logs ns'
abbr -a klons 'kubectl logs ns'
abbr -a kling 'kubectl logs ing'
abbr -a kloing 'kubectl logs ing'
abbr -a klpv 'kubectl logs pv'
abbr -a klopv 'kubectl logs pv'
abbr -a klpvc 'kubectl logs pvc'
abbr -a klopvc 'kubectl logs pvc'
abbr -a klsts 'kubectl logs sts'
abbr -a klosts 'kubectl logs sts'
abbr -a klds 'kubectl logs ds'
abbr -a klods 'kubectl logs ds'
abbr -a kljob 'kubectl logs job'
abbr -a klojob 'kubectl logs job'
abbr -a klcj 'kubectl logs cj'
abbr -a klocj 'kubectl logs cj'
abbr -a klrs 'kubectl logs rs'
abbr -a klors 'kubectl logs rs'
abbr -a klrc 'kubectl logs rc'
abbr -a klorc 'kubectl logs rc'
abbr -a klquota 'kubectl logs quota'
abbr -a kloquota 'kubectl logs quota'
abbr -a kllimitrange 'kubectl logs limitrange'
abbr -a klolimitrange 'kubectl logs limitrange'
abbr -a klhpa 'kubectl logs hpa'
abbr -a klohpa 'kubectl logs hpa'
abbr -a klpdb 'kubectl logs pdb'
abbr -a klopdb 'kubectl logs pdb'
abbr -a klsa 'kubectl logs sa'
abbr -a klosa 'kubectl logs sa'
abbr -a kapods 'kubectl apply pods'
abbr -a kappods 'kubectl apply pods'
abbr -a kasvc 'kubectl apply svc'
abbr -a kapsvc 'kubectl apply svc'
abbr -a kadeploy 'kubectl apply deploy'
abbr -a kapdeploy 'kubectl apply deploy'
abbr -a kacm 'kubectl apply cm'
abbr -a kapcm 'kubectl apply cm'
abbr -a kasecret 'kubectl apply secret'
abbr -a kapsecret 'kubectl apply secret'
abbr -a kanode 'kubectl apply node'
abbr -a kapnode 'kubectl apply node'
abbr -a kans 'kubectl apply ns'
abbr -a kapns 'kubectl apply ns'
abbr -a kaing 'kubectl apply ing'
abbr -a kaping 'kubectl apply ing'
abbr -a kapv 'kubectl apply pv'
abbr -a kappv 'kubectl apply pv'
abbr -a kapvc 'kubectl apply pvc'
abbr -a kappvc 'kubectl apply pvc'
abbr -a kasts 'kubectl apply sts'
abbr -a kapsts 'kubectl apply sts'
abbr -a kads 'kubectl apply ds'
abbr -a kapds 'kubectl apply ds'
abbr -a kajob 'kubectl apply job'
abbr -a kapjob 'kubectl apply job'
abbr -a kacj 'kubectl apply cj'
abbr -a kapcj 'kubectl apply cj'
abbr -a kars 'kubectl apply rs'
abbr -a kaprs 'kubectl apply rs'
abbr -a karc 'kubectl apply rc'
abbr -a kaprc 'kubectl apply rc'
abbr -a kaquota 'kubectl apply quota'
abbr -a kapquota 'kubectl apply quota'
abbr -a kalimitrange 'kubectl apply limitrange'
abbr -a kaplimitrange 'kubectl apply limitrange'
abbr -a kahpa 'kubectl apply hpa'
abbr -a kaphpa 'kubectl apply hpa'
abbr -a kapdb 'kubectl apply pdb'
abbr -a kappdb 'kubectl apply pdb'
abbr -a kasa 'kubectl apply sa'
abbr -a kapsa 'kubectl apply sa'
abbr -a kppods 'kubectl patch pods'
abbr -a kpapods 'kubectl patch pods'
abbr -a kpsvc 'kubectl patch svc'
abbr -a kpasvc 'kubectl patch svc'
abbr -a kpdeploy 'kubectl patch deploy'
abbr -a kpadeploy 'kubectl patch deploy'
abbr -a kpcm 'kubectl patch cm'
abbr -a kpacm 'kubectl patch cm'
abbr -a kpsecret 'kubectl patch secret'
abbr -a kpasecret 'kubectl patch secret'
abbr -a kpnode 'kubectl patch node'
abbr -a kpanode 'kubectl patch node'
abbr -a kpns 'kubectl patch ns'
abbr -a kpans 'kubectl patch ns'
abbr -a kping 'kubectl patch ing'
abbr -a kpaing 'kubectl patch ing'
abbr -a kppv 'kubectl patch pv'
abbr -a kpapv 'kubectl patch pv'
abbr -a kppvc 'kubectl patch pvc'
abbr -a kpapvc 'kubectl patch pvc'
abbr -a kpsts 'kubectl patch sts'
abbr -a kpasts 'kubectl patch sts'
abbr -a kpds 'kubectl patch ds'
abbr -a kpads 'kubectl patch ds'
abbr -a kpjob 'kubectl patch job'
abbr -a kpajob 'kubectl patch job'
abbr -a kpcj 'kubectl patch cj'
abbr -a kpacj 'kubectl patch cj'
abbr -a kprs 'kubectl patch rs'
abbr -a kpars 'kubectl patch rs'
abbr -a kprc 'kubectl patch rc'
abbr -a kparc 'kubectl patch rc'
abbr -a kpquota 'kubectl patch quota'
abbr -a kpaquota 'kubectl patch quota'
abbr -a kplimitrange 'kubectl patch limitrange'
abbr -a kpalimitrange 'kubectl patch limitrange'
abbr -a kphpa 'kubectl patch hpa'
abbr -a kpahpa 'kubectl patch hpa'
abbr -a kppdb 'kubectl patch pdb'
abbr -a kpapdb 'kubectl patch pdb'
abbr -a kpsa 'kubectl patch sa'
abbr -a kpasa 'kubectl patch sa'
abbr -a klapods 'kubectl label pods'
abbr -a klasvc 'kubectl label svc'
abbr -a kladeploy 'kubectl label deploy'
abbr -a klacm 'kubectl label cm'
abbr -a klasecret 'kubectl label secret'
abbr -a klanode 'kubectl label node'
abbr -a klans 'kubectl label ns'
abbr -a klaing 'kubectl label ing'
abbr -a klapv 'kubectl label pv'
abbr -a klapvc 'kubectl label pvc'
abbr -a klasts 'kubectl label sts'
abbr -a klads 'kubectl label ds'
abbr -a klajob 'kubectl label job'
abbr -a klacj 'kubectl label cj'
abbr -a klars 'kubectl label rs'
abbr -a klarc 'kubectl label rc'
abbr -a klaquota 'kubectl label quota'
abbr -a klalimitrange 'kubectl label limitrange'
abbr -a klahpa 'kubectl label hpa'
abbr -a klapdb 'kubectl label pdb'
abbr -a klasa 'kubectl label sa'
abbr -a kanpods 'kubectl annotate pods'
abbr -a kansvc 'kubectl annotate svc'
abbr -a kandeploy 'kubectl annotate deploy'
abbr -a kancm 'kubectl annotate cm'
abbr -a kansecret 'kubectl annotate secret'
abbr -a kannode 'kubectl annotate node'
abbr -a kanns 'kubectl annotate ns'
abbr -a kaning 'kubectl annotate ing'
abbr -a kanpv 'kubectl annotate pv'
abbr -a kanpvc 'kubectl annotate pvc'
abbr -a kansts 'kubectl annotate sts'
abbr -a kands 'kubectl annotate ds'
abbr -a kanjob 'kubectl annotate job'
abbr -a kancj 'kubectl annotate cj'
abbr -a kanrs 'kubectl annotate rs'
abbr -a kanrc 'kubectl annotate rc'
abbr -a kanquota 'kubectl annotate quota'
abbr -a kanlimitrange 'kubectl annotate limitrange'
abbr -a kanhpa 'kubectl annotate hpa'
abbr -a kanpdb 'kubectl annotate pdb'
abbr -a kansa 'kubectl annotate sa'
abbr -a kexpods 'kubectl expose pods'
abbr -a kexsvc 'kubectl expose svc'
abbr -a kexdeploy 'kubectl expose deploy'
abbr -a kexcm 'kubectl expose cm'
abbr -a kexsecret 'kubectl expose secret'
abbr -a kexnode 'kubectl expose node'
abbr -a kexns 'kubectl expose ns'
abbr -a kexing 'kubectl expose ing'
abbr -a kexpv 'kubectl expose pv'
abbr -a kexpvc 'kubectl expose pvc'
abbr -a kexsts 'kubectl expose sts'
abbr -a kexds 'kubectl expose ds'
abbr -a kexjob 'kubectl expose job'
abbr -a kexcj 'kubectl expose cj'
abbr -a kexrs 'kubectl expose rs'
abbr -a kexrc 'kubectl expose rc'
abbr -a kexquota 'kubectl expose quota'
abbr -a kexlimitrange 'kubectl expose limitrange'
abbr -a kexhpa 'kubectl expose hpa'
abbr -a kexpdb 'kubectl expose pdb'
abbr -a kexsa 'kubectl expose sa'
abbr -a kspods 'kubectl scale pods'
abbr -a kscpods 'kubectl scale pods'
abbr -a kssvc 'kubectl scale svc'
abbr -a kscsvc 'kubectl scale svc'
abbr -a ksdeploy 'kubectl scale deploy'
abbr -a kscdeploy 'kubectl scale deploy'
abbr -a kscm 'kubectl scale cm'
abbr -a ksccm 'kubectl scale cm'
abbr -a kssecret 'kubectl scale secret'
abbr -a kscsecret 'kubectl scale secret'
abbr -a ksnode 'kubectl scale node'
abbr -a kscnode 'kubectl scale node'
abbr -a ksns 'kubectl scale ns'
abbr -a kscns 'kubectl scale ns'
abbr -a ksing 'kubectl scale ing'
abbr -a kscing 'kubectl scale ing'
abbr -a kspv 'kubectl scale pv'
abbr -a kscpv 'kubectl scale pv'
abbr -a kspvc 'kubectl scale pvc'
abbr -a kscpvc 'kubectl scale pvc'
abbr -a kssts 'kubectl scale sts'
abbr -a kscsts 'kubectl scale sts'
abbr -a ksds 'kubectl scale ds'
abbr -a kscds 'kubectl scale ds'
abbr -a ksjob 'kubectl scale job'
abbr -a kscjob 'kubectl scale job'
abbr -a kscj 'kubectl scale cj'
abbr -a ksccj 'kubectl scale cj'
abbr -a ksrs 'kubectl scale rs'
abbr -a kscrs 'kubectl scale rs'
abbr -a ksrc 'kubectl scale rc'
abbr -a kscrc 'kubectl scale rc'
abbr -a ksquota 'kubectl scale quota'
abbr -a kscquota 'kubectl scale quota'
abbr -a kslimitrange 'kubectl scale limitrange'
abbr -a ksclimitrange 'kubectl scale limitrange'
abbr -a kshpa 'kubectl scale hpa'
abbr -a kschpa 'kubectl scale hpa'
abbr -a kspdb 'kubectl scale pdb'
abbr -a kscpdb 'kubectl scale pdb'
abbr -a kssa 'kubectl scale sa'
abbr -a kscsa 'kubectl scale sa'
abbr -a kaupods 'kubectl autoscale pods'
abbr -a kausvc 'kubectl autoscale svc'
abbr -a kaudeploy 'kubectl autoscale deploy'
abbr -a kaucm 'kubectl autoscale cm'
abbr -a kausecret 'kubectl autoscale secret'
abbr -a kaunode 'kubectl autoscale node'
abbr -a kauns 'kubectl autoscale ns'
abbr -a kauing 'kubectl autoscale ing'
abbr -a kaupv 'kubectl autoscale pv'
abbr -a kaupvc 'kubectl autoscale pvc'
abbr -a kausts 'kubectl autoscale sts'
abbr -a kauds 'kubectl autoscale ds'
abbr -a kaujob 'kubectl autoscale job'
abbr -a kaucj 'kubectl autoscale cj'
abbr -a kaurs 'kubectl autoscale rs'
abbr -a kaurc 'kubectl autoscale rc'
abbr -a kauquota 'kubectl autoscale quota'
abbr -a kaulimitrange 'kubectl autoscale limitrange'
abbr -a kauhpa 'kubectl autoscale hpa'
abbr -a kaupdb 'kubectl autoscale pdb'
abbr -a kausa 'kubectl autoscale sa'
abbr -a krpods 'kubectl rollout pods'
abbr -a kropods 'kubectl rollout pods'
abbr -a krsvc 'kubectl rollout svc'
abbr -a krosvc 'kubectl rollout svc'
abbr -a krdeploy 'kubectl rollout deploy'
abbr -a krodeploy 'kubectl rollout deploy'
abbr -a krcm 'kubectl rollout cm'
abbr -a krocm 'kubectl rollout cm'
abbr -a krsecret 'kubectl rollout secret'
abbr -a krosecret 'kubectl rollout secret'
abbr -a krnode 'kubectl rollout node'
abbr -a kronode 'kubectl rollout node'
abbr -a krns 'kubectl rollout ns'
abbr -a krons 'kubectl rollout ns'
abbr -a kring 'kubectl rollout ing'
abbr -a kroing 'kubectl rollout ing'
abbr -a krpv 'kubectl rollout pv'
abbr -a kropv 'kubectl rollout pv'
abbr -a krpvc 'kubectl rollout pvc'
abbr -a kropvc 'kubectl rollout pvc'
abbr -a krsts 'kubectl rollout sts'
abbr -a krosts 'kubectl rollout sts'
abbr -a krds 'kubectl rollout ds'
abbr -a krods 'kubectl rollout ds'
abbr -a krjob 'kubectl rollout job'
abbr -a krojob 'kubectl rollout job'
abbr -a krcj 'kubectl rollout cj'
abbr -a krocj 'kubectl rollout cj'
abbr -a krrs 'kubectl rollout rs'
abbr -a krors 'kubectl rollout rs'
abbr -a krrc 'kubectl rollout rc'
abbr -a krorc 'kubectl rollout rc'
abbr -a krquota 'kubectl rollout quota'
abbr -a kroquota 'kubectl rollout quota'
abbr -a krlimitrange 'kubectl rollout limitrange'
abbr -a krolimitrange 'kubectl rollout limitrange'
abbr -a krhpa 'kubectl rollout hpa'
abbr -a krohpa 'kubectl rollout hpa'
abbr -a krpdb 'kubectl rollout pdb'
abbr -a kropdb 'kubectl rollout pdb'
abbr -a krsa 'kubectl rollout sa'
abbr -a krosa 'kubectl rollout sa'
abbr -a ktpods 'kubectl top pods'
abbr -a ktopods 'kubectl top pods'
abbr -a ktsvc 'kubectl top svc'
abbr -a ktosvc 'kubectl top svc'
abbr -a ktdeploy 'kubectl top deploy'
abbr -a ktodeploy 'kubectl top deploy'
abbr -a ktcm 'kubectl top cm'
abbr -a ktocm 'kubectl top cm'
abbr -a ktsecret 'kubectl top secret'
abbr -a ktosecret 'kubectl top secret'
abbr -a ktnode 'kubectl top node'
abbr -a ktonode 'kubectl top node'
abbr -a ktns 'kubectl top ns'
abbr -a ktons 'kubectl top ns'
abbr -a kting 'kubectl top ing'
abbr -a ktoing 'kubectl top ing'
abbr -a ktpv 'kubectl top pv'
abbr -a ktopv 'kubectl top pv'
abbr -a ktpvc 'kubectl top pvc'
abbr -a ktopvc 'kubectl top pvc'
abbr -a ktsts 'kubectl top sts'
abbr -a ktosts 'kubectl top sts'
abbr -a ktds 'kubectl top ds'
abbr -a ktods 'kubectl top ds'
abbr -a ktjob 'kubectl top job'
abbr -a ktojob 'kubectl top job'
abbr -a ktcj 'kubectl top cj'
abbr -a ktocj 'kubectl top cj'
abbr -a ktrs 'kubectl top rs'
abbr -a ktors 'kubectl top rs'
abbr -a ktrc 'kubectl top rc'
abbr -a ktorc 'kubectl top rc'
abbr -a ktquota 'kubectl top quota'
abbr -a ktoquota 'kubectl top quota'
abbr -a ktlimitrange 'kubectl top limitrange'
abbr -a ktolimitrange 'kubectl top limitrange'
abbr -a kthpa 'kubectl top hpa'
abbr -a ktohpa 'kubectl top hpa'
abbr -a ktpdb 'kubectl top pdb'
abbr -a ktopdb 'kubectl top pdb'
abbr -a ktsa 'kubectl top sa'
abbr -a ktosa 'kubectl top sa'
abbr -a krupods 'kubectl run pods'
abbr -a krusvc 'kubectl run svc'
abbr -a krudeploy 'kubectl run deploy'
abbr -a krucm 'kubectl run cm'
abbr -a krusecret 'kubectl run secret'
abbr -a krunode 'kubectl run node'
abbr -a kruns 'kubectl run ns'
abbr -a kruing 'kubectl run ing'
abbr -a krupv 'kubectl run pv'
abbr -a krupvc 'kubectl run pvc'
abbr -a krusts 'kubectl run sts'
abbr -a kruds 'kubectl run ds'
abbr -a krujob 'kubectl run job'
abbr -a krucj 'kubectl run cj'
abbr -a krurs 'kubectl run rs'
abbr -a krurc 'kubectl run rc'
abbr -a kruquota 'kubectl run quota'
abbr -a krulimitrange 'kubectl run limitrange'
abbr -a kruhpa 'kubectl run hpa'
abbr -a krupdb 'kubectl run pdb'
abbr -a krusa 'kubectl run sa'
abbr -a katpods 'kubectl attach pods'
abbr -a katsvc 'kubectl attach svc'
abbr -a katdeploy 'kubectl attach deploy'
abbr -a katcm 'kubectl attach cm'
abbr -a katsecret 'kubectl attach secret'
abbr -a katnode 'kubectl attach node'
abbr -a katns 'kubectl attach ns'
abbr -a kating 'kubectl attach ing'
abbr -a katpv 'kubectl attach pv'
abbr -a katpvc 'kubectl attach pvc'
abbr -a katsts 'kubectl attach sts'
abbr -a katds 'kubectl attach ds'
abbr -a katjob 'kubectl attach job'
abbr -a katcj 'kubectl attach cj'
abbr -a katrs 'kubectl attach rs'
abbr -a katrc 'kubectl attach rc'
abbr -a katquota 'kubectl attach quota'
abbr -a katlimitrange 'kubectl attach limitrange'
abbr -a kathpa 'kubectl attach hpa'
abbr -a katpdb 'kubectl attach pdb'
abbr -a katsa 'kubectl attach sa'
abbr -a kpopods 'kubectl port-forward pods'
abbr -a kposvc 'kubectl port-forward svc'
abbr -a kpodeploy 'kubectl port-forward deploy'
abbr -a kpocm 'kubectl port-forward cm'
abbr -a kposecret 'kubectl port-forward secret'
abbr -a kponode 'kubectl port-forward node'
abbr -a kpons 'kubectl port-forward ns'
abbr -a kpoing 'kubectl port-forward ing'
abbr -a kpopv 'kubectl port-forward pv'
abbr -a kpopvc 'kubectl port-forward pvc'
abbr -a kposts 'kubectl port-forward sts'
abbr -a kpods 'kubectl port-forward ds'
abbr -a kpojob 'kubectl port-forward job'
abbr -a kpocj 'kubectl port-forward cj'
abbr -a kpors 'kubectl port-forward rs'
abbr -a kporc 'kubectl port-forward rc'
abbr -a kpoquota 'kubectl port-forward quota'
abbr -a kpolimitrange 'kubectl port-forward limitrange'
abbr -a kpohpa 'kubectl port-forward hpa'
abbr -a kpopdb 'kubectl port-forward pdb'
abbr -a kposa 'kubectl port-forward sa'
abbr -a kcpods 'kubectl cp pods'
abbr -a kcppods 'kubectl cp pods'
abbr -a kcsvc 'kubectl cp svc'
abbr -a kcpsvc 'kubectl cp svc'
abbr -a kcdeploy 'kubectl cp deploy'
abbr -a kcpdeploy 'kubectl cp deploy'
abbr -a kccm 'kubectl cp cm'
abbr -a kcpcm 'kubectl cp cm'
abbr -a kcsecret 'kubectl cp secret'
abbr -a kcpsecret 'kubectl cp secret'
abbr -a kcnode 'kubectl cp node'
abbr -a kcpnode 'kubectl cp node'
abbr -a kcns 'kubectl cp ns'
abbr -a kcpns 'kubectl cp ns'
abbr -a kcing 'kubectl cp ing'
abbr -a kcping 'kubectl cp ing'
abbr -a kcpv 'kubectl cp pv'
abbr -a kcppv 'kubectl cp pv'
abbr -a kcpvc 'kubectl cp pvc'
abbr -a kcppvc 'kubectl cp pvc'
abbr -a kcsts 'kubectl cp sts'
abbr -a kcpsts 'kubectl cp sts'
abbr -a kcds 'kubectl cp ds'
abbr -a kcpds 'kubectl cp ds'
abbr -a kcjob 'kubectl cp job'
abbr -a kcpjob 'kubectl cp job'
abbr -a kccj 'kubectl cp cj'
abbr -a kcpcj 'kubectl cp cj'
abbr -a kcrs 'kubectl cp rs'
abbr -a kcprs 'kubectl cp rs'
abbr -a kcrc 'kubectl cp rc'
abbr -a kcprc 'kubectl cp rc'
abbr -a kcquota 'kubectl cp quota'
abbr -a kcpquota 'kubectl cp quota'
abbr -a kclimitrange 'kubectl cp limitrange'
abbr -a kcplimitrange 'kubectl cp limitrange'
abbr -a kchpa 'kubectl cp hpa'
abbr -a kcphpa 'kubectl cp hpa'
abbr -a kcpdb 'kubectl cp pdb'
abbr -a kcppdb 'kubectl cp pdb'
abbr -a kcsa 'kubectl cp sa'
abbr -a kcpsa 'kubectl cp sa'
abbr -a pacin 'pacman install'
abbr -a pacup 'pacman update'
abbr -a pacre 'pacman remove'
abbr -a pacse 'pacman search'
abbr -a pacli 'pacman list'
abbr -a paccl 'pacman clean'
abbr -a pacau 'pacman autoremove'
abbr -a pacso 'pacman sources'
abbr -a pacch 'pacman check'
abbr -a aptin 'apt-get install'
abbr -a aptup 'apt-get update'
abbr -a aptre 'apt-get remove'
abbr -a aptse 'apt-get search'
abbr -a aptli 'apt-get list'
abbr -a aptcl 'apt-get clean'
abbr -a aptau 'apt-get autoremove'
abbr -a aptso 'apt-get sources'
abbr -a aptch 'apt-get check'
abbr -a dnfin 'dnf install'
abbr -a dnfup 'dnf update'
abbr -a dnfre 'dnf remove'
abbr -a dnfse 'dnf search'
abbr -a dnfli 'dnf list'
abbr -a dnfcl 'dnf clean'
abbr -a dnfau 'dnf autoremove'
abbr -a dnfso 'dnf sources'
abbr -a dnfch 'dnf check'
abbr -a zyin 'zypper install'
abbr -a zyup 'zypper update'
abbr -a zyre 'zypper remove'
abbr -a zyse 'zypper search'
abbr -a zyli 'zypper list'
abbr -a zycl 'zypper clean'
abbr -a zyau 'zypper autoremove'
abbr -a zyso 'zypper sources'
abbr -a zych 'zypper check'
abbr -a brin 'brew install'
abbr -a brup 'brew update'
abbr -a brre 'brew remove'
abbr -a brse 'brew search'
abbr -a brli 'brew list'
abbr -a brcl 'brew clean'
abbr -a brau 'brew autoremove'
abbr -a brso 'brew sources'
abbr -a brch 'brew check'
abbr -a yain 'yay install'
abbr -a yaup 'yay update'
abbr -a yare 'yay remove'
abbr -a yase 'yay search'
abbr -a yali 'yay list'
abbr -a yacl 'yay clean'
abbr -a yaau 'yay autoremove'
abbr -a yaso 'yay sources'
abbr -a yach 'yay check'
abbr -a pain 'paru install'
abbr -a paup 'paru update'
abbr -a pare 'paru remove'
abbr -a pase 'paru search'
abbr -a pali 'paru list'
abbr -a pacl 'paru clean'
abbr -a paau 'paru autoremove'
abbr -a paso 'paru sources'
abbr -a pach 'paru check'
abbr -a apkin 'apk install'
abbr -a apkup 'apk update'
abbr -a apkre 'apk remove'
abbr -a apkse 'apk search'
abbr -a apkli 'apk list'
abbr -a apkcl 'apk clean'
abbr -a apkau 'apk autoremove'
abbr -a apkso 'apk sources'
abbr -a apkch 'apk check'
abbr -a xbpsin 'xbps-install install'
abbr -a xbpsup 'xbps-install update'
abbr -a xbpsre 'xbps-install remove'
abbr -a xbpsse 'xbps-install search'
abbr -a xbpsli 'xbps-install list'
abbr -a xbpscl 'xbps-install clean'
abbr -a xbpsau 'xbps-install autoremove'
abbr -a xbpsso 'xbps-install sources'
abbr -a xbpsch 'xbps-install check'
abbr -a nixin 'nix-env install'
abbr -a nixup 'nix-env update'
abbr -a nixre 'nix-env remove'
abbr -a nixse 'nix-env search'
abbr -a nixli 'nix-env list'
abbr -a nixcl 'nix-env clean'
abbr -a nixau 'nix-env autoremove'
abbr -a nixso 'nix-env sources'
abbr -a nixch 'nix-env check'
abbr -a dnin 'dnf install'
abbr -a dnup 'dnf update'
abbr -a dnre 'dnf remove'
abbr -a dnse 'dnf search'
abbr -a dnli 'dnf list'
abbr -a dncl 'dnf clean'
abbr -a dnau 'dnf autoremove'
abbr -a dnso 'dnf sources'
abbr -a dnch 'dnf check'
abbr -a emin 'emerge install'
abbr -a emup 'emerge update'
abbr -a emre 'emerge remove'
abbr -a emse 'emerge search'
abbr -a emli 'emerge list'
abbr -a emcl 'emerge clean'
abbr -a emau 'emerge autoremove'
abbr -a emso 'emerge sources'
abbr -a emch 'emerge check'
abbr -a yuin 'yum install'
abbr -a yuup 'yum update'
abbr -a yure 'yum remove'
abbr -a yuse 'yum search'
abbr -a yuli 'yum list'
abbr -a yucl 'yum clean'
abbr -a yuau 'yum autoremove'
abbr -a yuso 'yum sources'
abbr -a yuch 'yum check'
abbr -a slin 'slpkg install'
abbr -a slup 'slpkg update'
abbr -a slre 'slpkg remove'
abbr -a slse 'slpkg search'
abbr -a slli 'slpkg list'
abbr -a slcl 'slpkg clean'
abbr -a slau 'slpkg autoremove'
abbr -a slso 'slpkg sources'
abbr -a slch 'slpkg check'
abbr -a lsa 'ls -a'
abbr -a lsh 'ls -h'
abbr -a lsv 'ls -v'
abbr -a lsl 'ls -l'
abbr -a lsR 'ls -R'
abbr -a lsn 'ls -n'
abbr -a lsf 'ls -f'
abbr -a lsi 'ls -i'
abbr -a lst 'ls -t'
abbr -a lsu 'ls -u'
abbr -a ipa 'ip -a'
abbr -a iph 'ip -h'
abbr -a ipv 'ip -v'
abbr -a ipl 'ip -l'
abbr -a ipR 'ip -R'
abbr -a ipn 'ip -n'
abbr -a ipf 'ip -f'
abbr -a ipi 'ip -i'
abbr -a ipt 'ip -t'
abbr -a ipu 'ip -u'
abbr -a nma 'nmcli -a'
abbr -a nmh 'nmcli -h'
abbr -a nmv 'nmcli -v'
abbr -a nml 'nmcli -l'
abbr -a nmR 'nmcli -R'
abbr -a nmn 'nmcli -n'
abbr -a nmf 'nmcli -f'
abbr -a nmi 'nmcli -i'
abbr -a nmt 'nmcli -t'
abbr -a nmu 'nmcli -u'
abbr -a dfa 'df -a'
abbr -a dfh 'df -h'
abbr -a dfv 'df -v'
abbr -a dfl 'df -l'
abbr -a dfR 'df -R'
abbr -a dfn 'df -n'
abbr -a dff 'df -f'
abbr -a dfi 'df -i'
abbr -a dft 'df -t'
abbr -a dfu 'df -u'
abbr -a dua 'du -a'
abbr -a duh 'du -h'
abbr -a duv 'du -v'
abbr -a dul 'du -l'
abbr -a duR 'du -R'
abbr -a dun 'du -n'
abbr -a duf 'du -f'
abbr -a dui 'du -i'
abbr -a dut 'du -t'
abbr -a duu 'du -u'
abbr -a fra 'free -a'
abbr -a frh 'free -h'
abbr -a frv 'free -v'
abbr -a frl 'free -l'
abbr -a frR 'free -R'
abbr -a frn 'free -n'
abbr -a frf 'free -f'
abbr -a fri 'free -i'
abbr -a frt 'free -t'
abbr -a fru 'free -u'
abbr -a psa 'ps -a'
abbr -a psh 'ps -h'
abbr -a psv 'ps -v'
abbr -a psl 'ps -l'
abbr -a psR 'ps -R'
abbr -a psn 'ps -n'
abbr -a psf 'ps -f'
abbr -a psi 'ps -i'
abbr -a pst 'ps -t'
abbr -a psu 'ps -u'
abbr -a toa 'top -a'
abbr -a toh 'top -h'
abbr -a tov 'top -v'
abbr -a tol 'top -l'
abbr -a toR 'top -R'
abbr -a ton 'top -n'
abbr -a tof 'top -f'
abbr -a toi 'top -i'
abbr -a tot 'top -t'
abbr -a tou 'top -u'
abbr -a gra 'grep -a'
abbr -a grh 'grep -h'
abbr -a grv 'grep -v'
abbr -a grl 'grep -l'
abbr -a grR 'grep -R'
abbr -a grn 'grep -n'
abbr -a grf 'grep -f'
abbr -a gri 'grep -i'
abbr -a grt 'grep -t'
abbr -a gru 'grep -u'
abbr -a sea 'sed -a'
abbr -a seh 'sed -h'
abbr -a sev 'sed -v'
abbr -a sel 'sed -l'
abbr -a seR 'sed -R'
abbr -a sen 'sed -n'
abbr -a sef 'sed -f'
abbr -a sei 'sed -i'
abbr -a set 'sed -t'
abbr -a seu 'sed -u'
abbr -a awa 'awk -a'
abbr -a awh 'awk -h'
abbr -a awv 'awk -v'
abbr -a awl 'awk -l'
abbr -a awR 'awk -R'
abbr -a awn 'awk -n'
abbr -a awf 'awk -f'
abbr -a awi 'awk -i'
abbr -a awt 'awk -t'
abbr -a awu 'awk -u'
abbr -a fia 'find -a'
abbr -a fih 'find -h'
abbr -a fiv 'find -v'
abbr -a fil 'find -l'
abbr -a fiR 'find -R'
abbr -a fin 'find -n'
abbr -a fif 'find -f'
abbr -a fii 'find -i'
abbr -a fit 'find -t'
abbr -a fiu 'find -u'
abbr -a cua 'curl -a'
abbr -a cuh 'curl -h'
abbr -a cuv 'curl -v'
abbr -a cul 'curl -l'
abbr -a cuR 'curl -R'
abbr -a cun 'curl -n'
abbr -a cuf 'curl -f'
abbr -a cui 'curl -i'
abbr -a cut 'curl -t'
abbr -a cuu 'curl -u'
abbr -a wga 'wget -a'
abbr -a wgh 'wget -h'
abbr -a wgv 'wget -v'
abbr -a wgl 'wget -l'
abbr -a wgR 'wget -R'
abbr -a wgn 'wget -n'
abbr -a wgf 'wget -f'
abbr -a wgi 'wget -i'
abbr -a wgt 'wget -t'
abbr -a wgu 'wget -u'
abbr -a ssa 'ssh -a'
abbr -a ssh 'ssh -h'
abbr -a ssv 'ssh -v'
abbr -a ssl 'ssh -l'
abbr -a ssR 'ssh -R'
abbr -a ssn 'ssh -n'
abbr -a ssf 'ssh -f'
abbr -a ssi 'ssh -i'
abbr -a sst 'ssh -t'
abbr -a ssu 'ssh -u'
abbr -a sca 'scp -a'
abbr -a sch 'scp -h'
abbr -a scv 'scp -v'
abbr -a scl 'scp -l'
abbr -a scR 'scp -R'
abbr -a scn 'scp -n'
abbr -a scf 'scp -f'
abbr -a sci 'scp -i'
abbr -a sct 'scp -t'
abbr -a scu 'scp -u'
abbr -a rsa 'rsync -a'
abbr -a rsh 'rsync -h'
abbr -a rsv 'rsync -v'
abbr -a rsl 'rsync -l'
abbr -a rsR 'rsync -R'
abbr -a rsn 'rsync -n'
abbr -a rsf 'rsync -f'
abbr -a rsi 'rsync -i'
abbr -a rst 'rsync -t'
abbr -a rsu 'rsync -u'
abbr -a cha 'chmod -a'
abbr -a chh 'chmod -h'
abbr -a chv 'chmod -v'
abbr -a chl 'chmod -l'
abbr -a chR 'chmod -R'
abbr -a chn 'chmod -n'
abbr -a chf 'chmod -f'
abbr -a chi 'chmod -i'
abbr -a cht 'chmod -t'
abbr -a chu 'chmod -u'
abbr -a taa 'tar -a'
abbr -a tah 'tar -h'
abbr -a tav 'tar -v'
abbr -a tal 'tar -l'
abbr -a taR 'tar -R'
abbr -a tan 'tar -n'
abbr -a taf 'tar -f'
abbr -a tai 'tar -i'
abbr -a tat 'tar -t'
abbr -a tau 'tar -u'
abbr -a gza 'gzip -a'
abbr -a gzh 'gzip -h'
abbr -a gzv 'gzip -v'
abbr -a gzl 'gzip -l'
abbr -a gzR 'gzip -R'
abbr -a gzn 'gzip -n'
abbr -a gzf 'gzip -f'
abbr -a gzi 'gzip -i'
abbr -a gzt 'gzip -t'
abbr -a gzu 'gzip -u'
abbr -a zia 'zip -a'
abbr -a zih 'zip -h'
abbr -a ziv 'zip -v'
abbr -a zil 'zip -l'
abbr -a ziR 'zip -R'
abbr -a zin 'zip -n'
abbr -a zif 'zip -f'
abbr -a zii 'zip -i'
abbr -a zit 'zip -t'
abbr -a ziu 'zip -u'