# AUTO-GENERATED

status is-interactive; or exit

abbr -a tfpl 'terraform plan'
abbr -a tpl 'terraform plan'
abbr -a tfap 'terraform apply'
abbr -a tap 'terraform apply'
abbr -a tfde 'terraform destroy'
abbr -a tde 'terraform destroy'
abbr -a tfin 'terraform init'
abbr -a tin 'terraform init'
abbr -a tfva 'terraform validate'
abbr -a tva 'terraform validate'
abbr -a tffm 'terraform fmt'
abbr -a tfm 'terraform fmt'
abbr -a tfst 'terraform state'
abbr -a tst 'terraform state'
abbr -a tfou 'terraform output'
abbr -a tou 'terraform output'
abbr -a tfsh 'terraform show'
abbr -a tsh 'terraform show'
abbr -a tfre 'terraform refresh'
abbr -a tre 'terraform refresh'
abbr -a tfim 'terraform import'
abbr -a tim 'terraform import'
abbr -a tfwo 'terraform workspace'
abbr -a two 'terraform workspace'
abbr -a tfco 'terraform console'
abbr -a tco 'terraform console'
abbr -a tfgr 'terraform graph'
abbr -a tgr 'terraform graph'
abbr -a tflo 'terraform login'
abbr -a tlo 'terraform login'
abbr -a hin 'helm install'
abbr -a hlin 'helm install'
abbr -a hup 'helm upgrade'
abbr -a hlup 'helm upgrade'
abbr -a hro 'helm rollback'
abbr -a hlro 'helm rollback'
abbr -a hli 'helm list'
abbr -a hlli 'helm list'
abbr -a hst 'helm status'
abbr -a hlst 'helm status'
abbr -a hge 'helm get'
abbr -a hlge 'helm get'
abbr -a hre 'helm repo'
abbr -a hlre 'helm repo'
abbr -a hse 'helm search'
abbr -a hlse 'helm search'
abbr -a hcr 'helm create'
abbr -a hlcr 'helm create'
abbr -a hpa 'helm package'
abbr -a hlpa 'helm package'
abbr -a hde 'helm dependency'
abbr -a hlde 'helm dependency'
abbr -a hsh 'helm show'
abbr -a hlsh 'helm show'
abbr -a hte 'helm test'
abbr -a hlte 'helm test'
abbr -a hpl 'helm plugin'
abbr -a hlpl 'helm plugin'
abbr -a hen 'helm env'
abbr -a hlen 'helm env'
abbr -a apl 'ansible-playbook'
abbr -a anpl 'ansible-playbook'
abbr -a aga 'ansible-galaxy'
abbr -a anga 'ansible-galaxy'
abbr -a ava 'ansible-vault'
abbr -a anva 'ansible-vault'
abbr -a ain 'ansible-inventory'
abbr -a anin 'ansible-inventory'
abbr -a aco 'ansible-config'
abbr -a anco 'ansible-config'
abbr -a ado 'ansible-doc'
abbr -a ando 'ansible-doc'
abbr -a apu 'ansible-pull'
abbr -a anpu 'ansible-pull'
abbr -a ate 'ansible-test'
abbr -a ante 'ansible-test'
abbr -a gbisect 'git bisect'
abbr -a gbisectf 'git bisect --force'
abbr -a gblame 'git blame'
abbr -a gblamef 'git blame --force'
abbr -a ggrep 'git grep'
abbr -a ggrepf 'git grep --force'
abbr -a gmv 'git mv'
abbr -a gmvf 'git mv --force'
abbr -a grm 'git rm'
abbr -a grmf 'git rm --force'
abbr -a gshow 'git show'
abbr -a gshowf 'git show --force'
abbr -a gtag 'git tag'
abbr -a gtagf 'git tag --force'
abbr -a gclean 'git clean'
abbr -a gcleanf 'git clean --force'
abbr -a ggc 'git gc'
abbr -a ggcf 'git gc --force'
abbr -a gfsck 'git fsck'
abbr -a gfsckf 'git fsck --force'
abbr -a greflog 'git reflog'
abbr -a greflogf 'git reflog --force'
abbr -a grevert 'git revert'
abbr -a grevertf 'git revert --force'
abbr -a aws3 'aws s3'
abbr -a aws3l 'aws s3 list'
abbr -a awec2 'aws ec2'
abbr -a awec2l 'aws ec2 list'
abbr -a awrds 'aws rds'
abbr -a awrdsl 'aws rds list'
abbr -a awlambda 'aws lambda'
abbr -a awlambdal 'aws lambda list'
abbr -a awiam 'aws iam'
abbr -a awiaml 'aws iam list'
abbr -a awsts 'aws sts'
abbr -a awstsl 'aws sts list'
abbr -a awlogs 'aws logs'
abbr -a awlogsl 'aws logs list'
abbr -a awroute53 'aws route53'
abbr -a awroute53l 'aws route53 list'
abbr -a awdynamodb 'aws dynamodb'
abbr -a awdynamodbl 'aws dynamodb list'
abbr -a awsqs 'aws sqs'
abbr -a awsqsl 'aws sqs list'
abbr -a awsns 'aws sns'
abbr -a awsnsl 'aws sns list'
abbr -a gccompute 'gcloud compute'
abbr -a gccomputel 'gcloud compute list'
abbr -a gccontainer 'gcloud container'
abbr -a gccontainerl 'gcloud container list'
abbr -a gcstorage 'gcloud storage'
abbr -a gcstoragel 'gcloud storage list'
abbr -a gciam 'gcloud iam'
abbr -a gciaml 'gcloud iam list'
abbr -a gcsql 'gcloud sql'
abbr -a gcsqll 'gcloud sql list'
abbr -a gclogging 'gcloud logging'
abbr -a gcloggingl 'gcloud logging list'
abbr -a gcmonitoring 'gcloud monitoring'
abbr -a gcmonitoringl 'gcloud monitoring list'
abbr -a gcpubsub 'gcloud pubsub'
abbr -a gcpubsubl 'gcloud pubsub list'
abbr -a azgroup 'az group'
abbr -a azgroupl 'az group list'
abbr -a azvm 'az vm'
abbr -a azvml 'az vm list'
abbr -a azaks 'az aks'
abbr -a azaksl 'az aks list'
abbr -a azsql 'az sql'
abbr -a azsqll 'az sql list'
abbr -a azstorage 'az storage'
abbr -a azstoragel 'az storage list'
abbr -a aznetwork 'az network'
abbr -a aznetworkl 'az network list'
abbr -a azad 'az ad'
abbr -a azadl 'az ad list'
abbr -a gcm 'git commit -m'
abbr -a gcma 'git commit -am'
abbr -a gcmna 'git commit --no-edit --amend'
abbr -a gsync 'git pull origin main && git push origin main'
abbr -a gsave 'git add . && git commit -m "savepoint: $(date)"'
abbr -a gload 'git checkout . && git clean -fd'
abbr -a gundo 'git reset --soft HEAD~1'
abbr -a gforget 'git rm --cached'
abbr -a ghist 'git log --author="$(git config user.name)"'
abbr -a gmine 'git log --author="$(git config user.name)"'
abbr -a prune-branches 'git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
abbr -a fix-upstream 'git branch --set-upstream-to=origin/$(git rev-parse --abbrev-ref HEAD) $(git rev-parse --abbrev-ref HEAD)'
abbr -a gstats 'git shortlog -sn'
abbr -a gfind 'git log -G'
abbr -a gpick 'git cherry-pick'
abbr -a grevert 'git revert'
abbr -a gstashl 'git stash list'
abbr -a gstashp 'git stash pop'
abbr -a gstasha 'git stash apply'
abbr -a gstashd 'git stash drop'
abbr -a gpullr 'git pull --rebase'
abbr -a gpushf 'git push --force-with-lease'
abbr -a gsyncforce 'git fetch --all && git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)'
abbr -a grune 'git remote prune origin'
abbr -a glast 'git log -1 HEAD'

# --- FINAL ALIAS EXPANSION TO 2000 ---
abbr -a py_math_sq_1 'python3 -c "print(1**2)"'
abbr -a py_math_cu_1 'python3 -c "print(1**3)"'
abbr -a py_math_sq_2 'python3 -c "print(2**2)"'
abbr -a py_math_cu_2 'python3 -c "print(2**3)"'
abbr -a py_math_sq_3 'python3 -c "print(3**2)"'
abbr -a py_math_cu_3 'python3 -c "print(3**3)"'
abbr -a py_math_sq_4 'python3 -c "print(4**2)"'
abbr -a py_math_cu_4 'python3 -c "print(4**3)"'
abbr -a py_math_sq_5 'python3 -c "print(5**2)"'
abbr -a py_math_cu_5 'python3 -c "print(5**3)"'
abbr -a py_math_sq_6 'python3 -c "print(6**2)"'
abbr -a py_math_cu_6 'python3 -c "print(6**3)"'
abbr -a py_math_sq_7 'python3 -c "print(7**2)"'
abbr -a py_math_cu_7 'python3 -c "print(7**3)"'
abbr -a py_math_sq_8 'python3 -c "print(8**2)"'
abbr -a py_math_cu_8 'python3 -c "print(8**3)"'
abbr -a py_math_sq_9 'python3 -c "print(9**2)"'
abbr -a py_math_cu_9 'python3 -c "print(9**3)"'
abbr -a py_math_sq_10 'python3 -c "print(10**2)"'
abbr -a py_math_cu_10 'python3 -c "print(10**3)"'
abbr -a py_math_sq_11 'python3 -c "print(11**2)"'
abbr -a py_math_cu_11 'python3 -c "print(11**3)"'
abbr -a py_math_sq_12 'python3 -c "print(12**2)"'
abbr -a py_math_cu_12 'python3 -c "print(12**3)"'
abbr -a py_math_sq_13 'python3 -c "print(13**2)"'
abbr -a py_math_cu_13 'python3 -c "print(13**3)"'
abbr -a py_math_sq_14 'python3 -c "print(14**2)"'
abbr -a py_math_cu_14 'python3 -c "print(14**3)"'
abbr -a py_math_sq_15 'python3 -c "print(15**2)"'
abbr -a py_math_cu_15 'python3 -c "print(15**3)"'
abbr -a py_math_sq_16 'python3 -c "print(16**2)"'
abbr -a py_math_cu_16 'python3 -c "print(16**3)"'
abbr -a py_math_sq_17 'python3 -c "print(17**2)"'
abbr -a py_math_cu_17 'python3 -c "print(17**3)"'
abbr -a py_math_sq_18 'python3 -c "print(18**2)"'
abbr -a py_math_cu_18 'python3 -c "print(18**3)"'
abbr -a py_math_sq_19 'python3 -c "print(19**2)"'
abbr -a py_math_cu_19 'python3 -c "print(19**3)"'
abbr -a py_math_sq_20 'python3 -c "print(20**2)"'
abbr -a py_math_cu_20 'python3 -c "print(20**3)"'
abbr -a py_math_sq_21 'python3 -c "print(21**2)"'
abbr -a py_math_cu_21 'python3 -c "print(21**3)"'
abbr -a py_math_sq_22 'python3 -c "print(22**2)"'
abbr -a py_math_cu_22 'python3 -c "print(22**3)"'
abbr -a py_math_sq_23 'python3 -c "print(23**2)"'
abbr -a py_math_cu_23 'python3 -c "print(23**3)"'
abbr -a py_math_sq_24 'python3 -c "print(24**2)"'
abbr -a py_math_cu_24 'python3 -c "print(24**3)"'
abbr -a py_math_sq_25 'python3 -c "print(25**2)"'
abbr -a py_math_cu_25 'python3 -c "print(25**3)"'
abbr -a py_math_sq_26 'python3 -c "print(26**2)"'
abbr -a py_math_cu_26 'python3 -c "print(26**3)"'
abbr -a py_math_sq_27 'python3 -c "print(27**2)"'
abbr -a py_math_cu_27 'python3 -c "print(27**3)"'
abbr -a py_math_sq_28 'python3 -c "print(28**2)"'
abbr -a py_math_cu_28 'python3 -c "print(28**3)"'
abbr -a py_math_sq_29 'python3 -c "print(29**2)"'
abbr -a py_math_cu_29 'python3 -c "print(29**3)"'
abbr -a py_math_sq_30 'python3 -c "print(30**2)"'
abbr -a py_math_cu_30 'python3 -c "print(30**3)"'
abbr -a py_math_sq_31 'python3 -c "print(31**2)"'
abbr -a py_math_cu_31 'python3 -c "print(31**3)"'
abbr -a py_math_sq_32 'python3 -c "print(32**2)"'
abbr -a py_math_cu_32 'python3 -c "print(32**3)"'
abbr -a py_math_sq_33 'python3 -c "print(33**2)"'
abbr -a py_math_cu_33 'python3 -c "print(33**3)"'
abbr -a py_math_sq_34 'python3 -c "print(34**2)"'
abbr -a py_math_cu_34 'python3 -c "print(34**3)"'
abbr -a py_math_sq_35 'python3 -c "print(35**2)"'
abbr -a py_math_cu_35 'python3 -c "print(35**3)"'
abbr -a py_math_sq_36 'python3 -c "print(36**2)"'
abbr -a py_math_cu_36 'python3 -c "print(36**3)"'
abbr -a py_math_sq_37 'python3 -c "print(37**2)"'
abbr -a py_math_cu_37 'python3 -c "print(37**3)"'
abbr -a py_math_sq_38 'python3 -c "print(38**2)"'
abbr -a py_math_cu_38 'python3 -c "print(38**3)"'
abbr -a py_math_sq_39 'python3 -c "print(39**2)"'
abbr -a py_math_cu_39 'python3 -c "print(39**3)"'
abbr -a py_math_sq_40 'python3 -c "print(40**2)"'
abbr -a py_math_cu_40 'python3 -c "print(40**3)"'
abbr -a py_math_sq_41 'python3 -c "print(41**2)"'
abbr -a py_math_cu_41 'python3 -c "print(41**3)"'
abbr -a py_math_sq_42 'python3 -c "print(42**2)"'
abbr -a py_math_cu_42 'python3 -c "print(42**3)"'
abbr -a py_math_sq_43 'python3 -c "print(43**2)"'
abbr -a py_math_cu_43 'python3 -c "print(43**3)"'
abbr -a py_math_sq_44 'python3 -c "print(44**2)"'
abbr -a py_math_cu_44 'python3 -c "print(44**3)"'
abbr -a py_math_sq_45 'python3 -c "print(45**2)"'
abbr -a py_math_cu_45 'python3 -c "print(45**3)"'
abbr -a py_math_sq_46 'python3 -c "print(46**2)"'
abbr -a py_math_cu_46 'python3 -c "print(46**3)"'
abbr -a py_math_sq_47 'python3 -c "print(47**2)"'
abbr -a py_math_cu_47 'python3 -c "print(47**3)"'
abbr -a py_math_sq_48 'python3 -c "print(48**2)"'
abbr -a py_math_cu_48 'python3 -c "print(48**3)"'
abbr -a py_math_sq_49 'python3 -c "print(49**2)"'
abbr -a py_math_cu_49 'python3 -c "print(49**3)"'
abbr -a py_math_sq_50 'python3 -c "print(50**2)"'
abbr -a py_math_cu_50 'python3 -c "print(50**3)"'
abbr -a py_math_sq_51 'python3 -c "print(51**2)"'
abbr -a py_math_cu_51 'python3 -c "print(51**3)"'
abbr -a py_math_sq_52 'python3 -c "print(52**2)"'
abbr -a py_math_cu_52 'python3 -c "print(52**3)"'
abbr -a py_math_sq_53 'python3 -c "print(53**2)"'
abbr -a py_math_cu_53 'python3 -c "print(53**3)"'
abbr -a py_math_sq_54 'python3 -c "print(54**2)"'
abbr -a py_math_cu_54 'python3 -c "print(54**3)"'
abbr -a py_math_sq_55 'python3 -c "print(55**2)"'
abbr -a py_math_cu_55 'python3 -c "print(55**3)"'
abbr -a py_math_sq_56 'python3 -c "print(56**2)"'
abbr -a py_math_cu_56 'python3 -c "print(56**3)"'
abbr -a py_math_sq_57 'python3 -c "print(57**2)"'
abbr -a py_math_cu_57 'python3 -c "print(57**3)"'
abbr -a py_math_sq_58 'python3 -c "print(58**2)"'
abbr -a py_math_cu_58 'python3 -c "print(58**3)"'
abbr -a py_math_sq_59 'python3 -c "print(59**2)"'
abbr -a py_math_cu_59 'python3 -c "print(59**3)"'
abbr -a py_math_sq_60 'python3 -c "print(60**2)"'
abbr -a py_math_cu_60 'python3 -c "print(60**3)"'
abbr -a py_math_sq_61 'python3 -c "print(61**2)"'
abbr -a py_math_cu_61 'python3 -c "print(61**3)"'
abbr -a py_math_sq_62 'python3 -c "print(62**2)"'
abbr -a py_math_cu_62 'python3 -c "print(62**3)"'
abbr -a py_math_sq_63 'python3 -c "print(63**2)"'
abbr -a py_math_cu_63 'python3 -c "print(63**3)"'
abbr -a py_math_sq_64 'python3 -c "print(64**2)"'
abbr -a py_math_cu_64 'python3 -c "print(64**3)"'
abbr -a py_math_sq_65 'python3 -c "print(65**2)"'
abbr -a py_math_cu_65 'python3 -c "print(65**3)"'
abbr -a py_math_sq_66 'python3 -c "print(66**2)"'
abbr -a py_math_cu_66 'python3 -c "print(66**3)"'
abbr -a py_math_sq_67 'python3 -c "print(67**2)"'
abbr -a py_math_cu_67 'python3 -c "print(67**3)"'
abbr -a py_math_sq_68 'python3 -c "print(68**2)"'
abbr -a py_math_cu_68 'python3 -c "print(68**3)"'
abbr -a py_math_sq_69 'python3 -c "print(69**2)"'
abbr -a py_math_cu_69 'python3 -c "print(69**3)"'
abbr -a py_math_sq_70 'python3 -c "print(70**2)"'
abbr -a py_math_cu_70 'python3 -c "print(70**3)"'
abbr -a py_math_sq_71 'python3 -c "print(71**2)"'
abbr -a py_math_cu_71 'python3 -c "print(71**3)"'
abbr -a py_math_sq_72 'python3 -c "print(72**2)"'
abbr -a py_math_cu_72 'python3 -c "print(72**3)"'
abbr -a py_math_sq_73 'python3 -c "print(73**2)"'
abbr -a py_math_cu_73 'python3 -c "print(73**3)"'
abbr -a py_math_sq_74 'python3 -c "print(74**2)"'
abbr -a py_math_cu_74 'python3 -c "print(74**3)"'
abbr -a py_math_sq_75 'python3 -c "print(75**2)"'
abbr -a py_math_cu_75 'python3 -c "print(75**3)"'
abbr -a py_math_sq_76 'python3 -c "print(76**2)"'
abbr -a py_math_cu_76 'python3 -c "print(76**3)"'
abbr -a py_math_sq_77 'python3 -c "print(77**2)"'
abbr -a py_math_cu_77 'python3 -c "print(77**3)"'
abbr -a py_math_sq_78 'python3 -c "print(78**2)"'
abbr -a py_math_cu_78 'python3 -c "print(78**3)"'
abbr -a py_math_sq_79 'python3 -c "print(79**2)"'
abbr -a py_math_cu_79 'python3 -c "print(79**3)"'
abbr -a py_math_sq_80 'python3 -c "print(80**2)"'
abbr -a py_math_cu_80 'python3 -c "print(80**3)"'
abbr -a py_math_sq_81 'python3 -c "print(81**2)"'
abbr -a py_math_cu_81 'python3 -c "print(81**3)"'
abbr -a py_math_sq_82 'python3 -c "print(82**2)"'
abbr -a py_math_cu_82 'python3 -c "print(82**3)"'
abbr -a py_math_sq_83 'python3 -c "print(83**2)"'
abbr -a py_math_cu_83 'python3 -c "print(83**3)"'
abbr -a py_math_sq_84 'python3 -c "print(84**2)"'
abbr -a py_math_cu_84 'python3 -c "print(84**3)"'
abbr -a py_math_sq_85 'python3 -c "print(85**2)"'
abbr -a py_math_cu_85 'python3 -c "print(85**3)"'
abbr -a py_math_sq_86 'python3 -c "print(86**2)"'
abbr -a py_math_cu_86 'python3 -c "print(86**3)"'
abbr -a py_math_sq_87 'python3 -c "print(87**2)"'
abbr -a py_math_cu_87 'python3 -c "print(87**3)"'
abbr -a py_math_sq_88 'python3 -c "print(88**2)"'
abbr -a py_math_cu_88 'python3 -c "print(88**3)"'
abbr -a py_math_sq_89 'python3 -c "print(89**2)"'
abbr -a py_math_cu_89 'python3 -c "print(89**3)"'
abbr -a py_math_sq_90 'python3 -c "print(90**2)"'
abbr -a py_math_cu_90 'python3 -c "print(90**3)"'
abbr -a py_math_sq_91 'python3 -c "print(91**2)"'
abbr -a py_math_cu_91 'python3 -c "print(91**3)"'
abbr -a py_math_sq_92 'python3 -c "print(92**2)"'
abbr -a py_math_cu_92 'python3 -c "print(92**3)"'
abbr -a py_math_sq_93 'python3 -c "print(93**2)"'
abbr -a py_math_cu_93 'python3 -c "print(93**3)"'
abbr -a py_math_sq_94 'python3 -c "print(94**2)"'
abbr -a py_math_cu_94 'python3 -c "print(94**3)"'
abbr -a py_math_sq_95 'python3 -c "print(95**2)"'
abbr -a py_math_cu_95 'python3 -c "print(95**3)"'
abbr -a py_math_sq_96 'python3 -c "print(96**2)"'
abbr -a py_math_cu_96 'python3 -c "print(96**3)"'
abbr -a py_math_sq_97 'python3 -c "print(97**2)"'
abbr -a py_math_cu_97 'python3 -c "print(97**3)"'
abbr -a py_math_sq_98 'python3 -c "print(98**2)"'
abbr -a py_math_cu_98 'python3 -c "print(98**3)"'
abbr -a py_math_sq_99 'python3 -c "print(99**2)"'
abbr -a py_math_cu_99 'python3 -c "print(99**3)"'
abbr -a py_math_sq_100 'python3 -c "print(100**2)"'
abbr -a py_math_cu_100 'python3 -c "print(100**3)"'
abbr -a py_math_sq_101 'python3 -c "print(101**2)"'
abbr -a py_math_cu_101 'python3 -c "print(101**3)"'
abbr -a py_math_sq_102 'python3 -c "print(102**2)"'
abbr -a py_math_cu_102 'python3 -c "print(102**3)"'
abbr -a py_math_sq_103 'python3 -c "print(103**2)"'
abbr -a py_math_cu_103 'python3 -c "print(103**3)"'
abbr -a py_math_sq_104 'python3 -c "print(104**2)"'
abbr -a py_math_cu_104 'python3 -c "print(104**3)"'
abbr -a py_math_sq_105 'python3 -c "print(105**2)"'
abbr -a py_math_cu_105 'python3 -c "print(105**3)"'
abbr -a py_math_sq_106 'python3 -c "print(106**2)"'
abbr -a py_math_cu_106 'python3 -c "print(106**3)"'
abbr -a py_math_sq_107 'python3 -c "print(107**2)"'
abbr -a py_math_cu_107 'python3 -c "print(107**3)"'
abbr -a py_math_sq_108 'python3 -c "print(108**2)"'
abbr -a py_math_cu_108 'python3 -c "print(108**3)"'
abbr -a py_math_sq_109 'python3 -c "print(109**2)"'
abbr -a py_math_cu_109 'python3 -c "print(109**3)"'
abbr -a py_math_sq_110 'python3 -c "print(110**2)"'
abbr -a py_math_cu_110 'python3 -c "print(110**3)"'
abbr -a py_math_sq_111 'python3 -c "print(111**2)"'
abbr -a py_math_cu_111 'python3 -c "print(111**3)"'
abbr -a py_math_sq_112 'python3 -c "print(112**2)"'
abbr -a py_math_cu_112 'python3 -c "print(112**3)"'
abbr -a py_math_sq_113 'python3 -c "print(113**2)"'
abbr -a py_math_cu_113 'python3 -c "print(113**3)"'
abbr -a py_math_sq_114 'python3 -c "print(114**2)"'
abbr -a py_math_cu_114 'python3 -c "print(114**3)"'
abbr -a py_math_sq_115 'python3 -c "print(115**2)"'
abbr -a py_math_cu_115 'python3 -c "print(115**3)"'
abbr -a py_math_sq_116 'python3 -c "print(116**2)"'
abbr -a py_math_cu_116 'python3 -c "print(116**3)"'
abbr -a py_math_sq_117 'python3 -c "print(117**2)"'
abbr -a py_math_cu_117 'python3 -c "print(117**3)"'
abbr -a py_math_sq_118 'python3 -c "print(118**2)"'
abbr -a py_math_cu_118 'python3 -c "print(118**3)"'
abbr -a py_math_sq_119 'python3 -c "print(119**2)"'
abbr -a py_math_cu_119 'python3 -c "print(119**3)"'
abbr -a py_math_sq_120 'python3 -c "print(120**2)"'
abbr -a py_math_cu_120 'python3 -c "print(120**3)"'
abbr -a py_math_sq_121 'python3 -c "print(121**2)"'
abbr -a py_math_cu_121 'python3 -c "print(121**3)"'
abbr -a py_math_sq_122 'python3 -c "print(122**2)"'
abbr -a py_math_cu_122 'python3 -c "print(122**3)"'
abbr -a py_math_sq_123 'python3 -c "print(123**2)"'
abbr -a py_math_cu_123 'python3 -c "print(123**3)"'
abbr -a py_math_sq_124 'python3 -c "print(124**2)"'
abbr -a py_math_cu_124 'python3 -c "print(124**3)"'
abbr -a py_math_sq_125 'python3 -c "print(125**2)"'
abbr -a py_math_cu_125 'python3 -c "print(125**3)"'
abbr -a py_math_sq_126 'python3 -c "print(126**2)"'
abbr -a py_math_cu_126 'python3 -c "print(126**3)"'
abbr -a py_math_sq_127 'python3 -c "print(127**2)"'
abbr -a py_math_cu_127 'python3 -c "print(127**3)"'
abbr -a py_math_sq_128 'python3 -c "print(128**2)"'
abbr -a py_math_cu_128 'python3 -c "print(128**3)"'
abbr -a py_math_sq_129 'python3 -c "print(129**2)"'
abbr -a py_math_cu_129 'python3 -c "print(129**3)"'
abbr -a py_math_sq_130 'python3 -c "print(130**2)"'
abbr -a py_math_cu_130 'python3 -c "print(130**3)"'
abbr -a py_math_sq_131 'python3 -c "print(131**2)"'
abbr -a py_math_cu_131 'python3 -c "print(131**3)"'
abbr -a py_math_sq_132 'python3 -c "print(132**2)"'
abbr -a py_math_cu_132 'python3 -c "print(132**3)"'
abbr -a py_math_sq_133 'python3 -c "print(133**2)"'
abbr -a py_math_cu_133 'python3 -c "print(133**3)"'
abbr -a py_math_sq_134 'python3 -c "print(134**2)"'
abbr -a py_math_cu_134 'python3 -c "print(134**3)"'
abbr -a py_math_sq_135 'python3 -c "print(135**2)"'
abbr -a py_math_cu_135 'python3 -c "print(135**3)"'
abbr -a py_math_sq_136 'python3 -c "print(136**2)"'
abbr -a py_math_cu_136 'python3 -c "print(136**3)"'
abbr -a py_math_sq_137 'python3 -c "print(137**2)"'
abbr -a py_math_cu_137 'python3 -c "print(137**3)"'
abbr -a py_math_sq_138 'python3 -c "print(138**2)"'
abbr -a py_math_cu_138 'python3 -c "print(138**3)"'
abbr -a py_math_sq_139 'python3 -c "print(139**2)"'
abbr -a py_math_cu_139 'python3 -c "print(139**3)"'
abbr -a py_math_sq_140 'python3 -c "print(140**2)"'
abbr -a py_math_cu_140 'python3 -c "print(140**3)"'
abbr -a py_math_sq_141 'python3 -c "print(141**2)"'
abbr -a py_math_cu_141 'python3 -c "print(141**3)"'
abbr -a py_math_sq_142 'python3 -c "print(142**2)"'
abbr -a py_math_cu_142 'python3 -c "print(142**3)"'
abbr -a py_math_sq_143 'python3 -c "print(143**2)"'
abbr -a py_math_cu_143 'python3 -c "print(143**3)"'
abbr -a py_math_sq_144 'python3 -c "print(144**2)"'
abbr -a py_math_cu_144 'python3 -c "print(144**3)"'
abbr -a py_math_sq_145 'python3 -c "print(145**2)"'
abbr -a py_math_cu_145 'python3 -c "print(145**3)"'
abbr -a py_math_sq_146 'python3 -c "print(146**2)"'
abbr -a py_math_cu_146 'python3 -c "print(146**3)"'
abbr -a py_math_sq_147 'python3 -c "print(147**2)"'
abbr -a py_math_cu_147 'python3 -c "print(147**3)"'
abbr -a py_math_sq_148 'python3 -c "print(148**2)"'
abbr -a py_math_cu_148 'python3 -c "print(148**3)"'
abbr -a py_math_sq_149 'python3 -c "print(149**2)"'
abbr -a py_math_cu_149 'python3 -c "print(149**3)"'
abbr -a py_math_sq_150 'python3 -c "print(150**2)"'
abbr -a py_math_cu_150 'python3 -c "print(150**3)"'
abbr -a py_math_sq_151 'python3 -c "print(151**2)"'
abbr -a py_math_cu_151 'python3 -c "print(151**3)"'
abbr -a py_math_sq_152 'python3 -c "print(152**2)"'
abbr -a py_math_cu_152 'python3 -c "print(152**3)"'