#!/usr/bin/env fish
alias .. "cd .."
alias ... "cd ../.."
alias .... "cd ../../.."
alias ..... "cd ../../../.."
alias home "cd ~"
alias dots "cd $DOTFILES_DIR"
alias dotfiles "cd $DOTFILES_DIR"
alias dotst "git -C $DOTFILES_DIR status --short --branch"
alias edots "$EDITOR $DOTFILES_DIR"
alias reload "exec $SHELL -l"
alias mkdirp "mkdir -p"
alias please "sudo"
alias ports "netstat -tulanp 2>/dev/null; or ss -tulanp"
alias myip "curl -fsSL https://ifconfig.me 2>/dev/null; or curl -fsSL https://ipinfo.io/ip 2>/dev/null"
alias weather "curl -fsSL wttr.in"
alias serve "python3 -m http.server"
alias g "git"
alias gs "git status --short --branch"
alias ga "git add"
alias gaa "git add -A"
alias gc "git commit"
alias gcm "git commit -m"
alias gca "git commit --amend"
alias gp "git push"
alias gpf "git push --force-with-lease"
alias gpl "git pull --rebase --autostash"
alias gf "git fetch --all --prune"
alias gl "git log --oneline --decorate --graph --all -30"
alias gd "git diff"
alias gds "git diff --staged"
alias gb "git branch"
alias gco "git checkout"
alias gsw "git switch"
alias gst "git stash push -u"
alias gsp "git stash pop"
alias grbc "git rebase --continue"
alias grba "git rebase --abort"
alias ls "eza --icons=auto --group-directories-first 2>/dev/null; or command ls"
alias ll "eza -lah --icons=auto --group-directories-first 2>/dev/null; or command ls -lah"
alias la "eza -AGa --icons=auto 2>/dev/null; or command ls -a"
alias lt "eza --tree --level=2 --icons=auto 2>/dev/null; or find . -maxdepth 2 -print"
alias cat "bat --paging=never 2>/dev/null; or command cat"
alias grep "rg 2>/dev/null; or command grep"
alias duh "du -sh"
alias dfh "df -h"
alias freeh "free -h"
alias psg "ps aux | grep -i"
alias topcpu "ps aux --sort=-%cpu | head"
alias topmem "ps aux --sort=-%mem | head"
alias j "jobs -l"
alias h "history"
alias c "clear"
alias cls "clear"
alias k "kubectl"
alias kgp "kubectl get pods"
alias kgs "kubectl get svc"
alias kctx "kubectl config current-context"
alias d "docker"
alias dps "docker ps"
alias dpsa "docker ps -a"
alias di "docker images"
alias dc "docker compose"
alias tf "terraform"
alias tfi "terraform init"
alias tfp "terraform plan"
alias tfa "terraform apply"
alias py "python3"
alias pipup "python3 -m pip install --upgrade pip"
alias venv "python3 -m venv .venv"
alias nr "npm run"
alias ni "npm install"
alias nt "npm test"
alias nd "npm run dev"
alias prune "git remote prune origin"
alias today "date +%F"
alias now "date '+%F %T'"
alias matrix "printf '01101000 01100101 01101100 01101100 01101111\\n'"
alias shipit "git status --short; and git push"
alias focus "printf 'focus\n'"
alias coinflip "printf 'coinflip\n'"
alias pathlines "string split : $PATH"