abbr -a aco 'ansible-config'
abbr -a ado 'ansible-doc'
abbr -a aga 'ansible-galaxy'
abbr -a ain 'ansible-inventory'
abbr -a anco 'ansible-config'
abbr -a ando 'ansible-doc'
abbr -a anga 'ansible-galaxy'
abbr -a anin 'ansible-inventory'
abbr -a anpl 'ansible-playbook'
abbr -a anpu 'ansible-pull'
abbr -a ante 'ansible-test'
abbr -a anva 'ansible-vault'
abbr -a apkau 'apk autoremove'
abbr -a apkch 'apk check'
abbr -a apkcl 'apk clean'
abbr -a apkin 'apk install'
abbr -a apkli 'apk list'
abbr -a apkre 'apk remove'
abbr -a apkse 'apk search'
abbr -a apkso 'apk sources'
abbr -a apkup 'apk update'
abbr -a apl 'ansible-playbook'
abbr -a aptau 'apt-get autoremove'
abbr -a aptch 'apt-get check'
abbr -a aptcl 'apt-get clean'
abbr -a aptin 'apt-get install'
abbr -a aptli 'apt-get list'
abbr -a aptre 'apt-get remove'
abbr -a aptse 'apt-get search'
abbr -a aptso 'apt-get sources'
abbr -a aptup 'apt-get update'
abbr -a apu 'ansible-pull'
abbr -a ate 'ansible-test'
abbr -a ava 'ansible-vault'
abbr -a awa 'awk -a'
abbr -a awdynamodb 'aws dynamodb'
abbr -a awdynamodbl 'aws dynamodb list'
abbr -a awec2 'aws ec2'
abbr -a awec2l 'aws ec2 list'
abbr -a awf 'awk -f'
abbr -a awh 'awk -h'
abbr -a awiam 'aws iam'
abbr -a awiaml 'aws iam list'
abbr -a awi 'awk -i'
abbr -a awlambda 'aws lambda'
abbr -a awlambdal 'aws lambda list'
abbr -a awl 'awk -l'
abbr -a awlogs 'aws logs'
abbr -a awlogsl 'aws logs list'
abbr -a awn 'awk -n'
abbr -a awR 'awk -R'
abbr -a awrds 'aws rds'
abbr -a awrdsl 'aws rds list'
abbr -a awroute53 'aws route53'
abbr -a awroute53l 'aws route53 list'
abbr -a aws3 'aws s3'
abbr -a aws3l 'aws s3 list'
abbr -a awsns 'aws sns'
abbr -a awsnsl 'aws sns list'
abbr -a awsqs 'aws sqs'
abbr -a awsqsl 'aws sqs list'
abbr -a awsts 'aws sts'
abbr -a awstsl 'aws sts list'
abbr -a awt 'awk -t'
abbr -a awu 'awk -u'
abbr -a awv 'awk -v'
abbr -a azad 'az ad'
abbr -a azadl 'az ad list'
abbr -a azaks 'az aks'
abbr -a azaksl 'az aks list'
abbr -a azgroup 'az group'
abbr -a azgroupl 'az group list'
abbr -a aznetwork 'az network'
abbr -a aznetworkl 'az network list'
abbr -a azsql 'az sql'
abbr -a azsqll 'az sql list'
abbr -a azstorage 'az storage'
abbr -a azstoragel 'az storage list'
abbr -a azvm 'az vm'
abbr -a azvml 'az vm list'
abbr -a back 'cd -'
abbr -a bconf '$EDITOR ~/.config/fish/config.fish'
abbr -a brau 'brew autoremove'
abbr -a brch 'brew check'
abbr -a brcl 'brew clean'
abbr -a brin 'brew install'
abbr -a brli 'brew list'
abbr -a brre 'brew remove'
abbr -a brse 'brew search'
abbr -a brso 'brew sources'
abbr -a brup 'brew update'
abbr -a cbld 'cargo build'
abbr -a .. 'cd ..'
abbr -a ... 'cd ../..'
abbr -a .... 'cd ../../..'
abbr -a ..... 'cd ../../../..'
abbr -a cha 'chmod -a'
abbr -a chf 'chmod -f'
abbr -a chh 'chmod -h'
abbr -a chi 'chmod -i'
abbr -a chl 'chmod -l'
abbr -a chn 'chmod -n'
abbr -a chR 'chmod -R'
abbr -a cht 'chmod -t'
abbr -a chu 'chmod -u'
abbr -a chv 'chmod -v'
abbr -a cleancache rm -rf ~/.cache/*
abbr -a cleanpkg rm -rf /var/cache/*
abbr -a cleanup 'sudo apt autoremove -y'
abbr -a cpf 'cp -rf'
abbr -a cpuinfo 'lscpu'
abbr -a crel 'cargo run --release'
abbr -a crun 'cargo run'
abbr -a ctst 'cargo test'
abbr -a cua 'curl -a'
abbr -a cuf 'curl -f'
abbr -a cuh 'curl -h'
abbr -a cui 'curl -i'
abbr -a cul 'curl -l'
abbr -a cun 'curl -n'
abbr -a cuR 'curl -R'
abbr -a cut 'curl -t'
abbr -a cuu 'curl -u'
abbr -a cuv 'curl -v'
abbr -a dcdn 'docker-compose down'
abbr -a dc 'docker-compose'
abbr -a dcls 'docker-compose logs -f'
abbr -a dcrs 'docker-compose restart'
abbr -a dcup 'docker-compose up -d'
abbr -a d 'docker'
abbr -a dex 'docker exec -it'
abbr -a dfa 'df -a'
abbr -a dff 'df -f'
abbr -a dfh 'df -h'
abbr -a dfi 'df -i'
abbr -a dfl 'df -l'
abbr -a dfn 'df -n'
abbr -a dfR 'df -R'
abbr -a dft 'df -t'
abbr -a dfu 'df -u'
abbr -a dfv 'df -v'
abbr -a di 'docker images'
abbr -a diskinfo 'lsblk && echo "" && df -h'
abbr -a dl 'cd ~/Downloads'
abbr -a dnau 'dnf autoremove'
abbr -a dnch 'dnf check'
abbr -a dncl 'dnf clean'
abbr -a dnfau 'dnf autoremove'
abbr -a dnfch 'dnf check'
abbr -a dnfcl 'dnf clean'
abbr -a dnfin 'dnf install'
abbr -a dnfli 'dnf list'
abbr -a dnfre 'dnf remove'
abbr -a dnfse 'dnf search'
abbr -a dnfso 'dnf sources'
abbr -a dnfup 'dnf update'
abbr -a dnin 'dnf install'
abbr -a dnli 'dnf list'
abbr -a dnre 'dnf remove'
abbr -a dnse 'dnf search'
abbr -a dnso 'dnf sources'
abbr -a dnup 'dnf update'
abbr -a docs 'cd ~/Documents'
abbr -a dprune 'docker system prune -af'
abbr -a dps 'docker ps'
abbr -a dsync 'dot_sync'
abbr -a dua 'du -a'
abbr -a duf 'du -f'
abbr -a duh 'du -h'
abbr -a dui 'du -i'
abbr -a dul 'du -l'
abbr -a dun 'du -n'
abbr -a duR 'du -R'
abbr -a dut 'du -t'
abbr -a duu 'du -u'
abbr -a duv 'du -v'
abbr -a editbash '$EDITOR ~/.bashrc'
abbr -a editfish '$EDITOR ~/.config/fish/config.fish'
abbr -a editgit '$EDITOR ~/.gitconfig'
abbr -a editstarship '$EDITOR ~/.config/starship.toml'
abbr -a editzsh '$EDITOR ~/.zshrc'
abbr -a emau 'emerge autoremove'
abbr -a emch 'emerge check'
abbr -a emcl 'emerge clean'
abbr -a emin 'emerge install'
abbr -a emli 'emerge list'
abbr -a emre 'emerge remove'
abbr -a emse 'emerge search'
abbr -a emso 'emerge sources'
abbr -a emup 'emerge update'
abbr -a fastping 'ping -c 100 -s.2'
abbr -a fetch fastfetch
abbr -a fia 'find -a'
abbr -a fif 'find -f'
abbr -a fih 'find -h'
abbr -a fii 'find -i'
abbr -a fil 'find -l'
abbr -a fin 'find -n'
abbr -a fiR 'find -R'
abbr -a fit 'find -t'
abbr -a fiu 'find -u'
abbr -a fiv 'find -v'
abbr -a fix-upstream 'git branch --set-upstream-to=origin/$(git rev-parse --abbrev-ref HEAD) $(git rev-parse --abbrev-ref HEAD)'
abbr -a fra 'free -a'
abbr -a frf 'free -f'
abbr -a frh 'free -h'
abbr -a fri 'free -i'
abbr -a frl 'free -l'
abbr -a frn 'free -n'
abbr -a frR 'free -R'
abbr -a frt 'free -t'
abbr -a fru 'free -u'
abbr -a frv 'free -v'
abbr -a gaa 'git add --all'
abbr -a gadf 'git add --force'
abbr -a gad 'git add'
abbr -a gadv 'git add --verbose'
abbr -a ga 'git add'
abbr -a gap 'git add -p'
abbr -a gb 'git branch'
abbr -a gbif 'git bisect --force'
abbr -a gbi 'git bisect'
abbr -a gbisectf 'git bisect --force'
abbr -a gbisect 'git bisect'
abbr -a gbiv 'git bisect --verbose'
abbr -a gblamef 'git blame --force'
abbr -a gblame 'git blame'
abbr -a gblf 'git blame --force'
abbr -a gbl 'git blame'
abbr -a gblv 'git blame --verbose'
abbr -a gbrf 'git branch --force'
abbr -a gbr 'git branch'
abbr -a gbrv 'git branch --verbose'
abbr -a gbsort 'git branch --sort=-committerdate'
abbr -a gcb 'git checkout -b'
abbr -a gccompute 'gcloud compute'
abbr -a gccomputel 'gcloud compute list'
abbr -a gccontainer 'gcloud container'
abbr -a gccontainerl 'gcloud container list'
abbr -a gc 'git commit'
abbr -a gchf 'git checkout --force'
abbr -a gch 'git checkout'
abbr -a gchv 'git checkout --verbose'
abbr -a gciam 'gcloud iam'
abbr -a gciaml 'gcloud iam list'
abbr -a gcleanf 'git clean --force'
abbr -a gclean 'git clean'
abbr -a gclf 'git clean --force'
abbr -a gcl 'git clean'
abbr -a gclogging 'gcloud logging'
abbr -a gcloggingl 'gcloud logging list'
abbr -a gclv 'git clean --verbose'
abbr -a gcma 'git commit -am'
abbr -a gcm 'git commit -m'
abbr -a gcmna 'git commit --no-edit --amend'
abbr -a gcmonitoring 'gcloud monitoring'
abbr -a gcmonitoringl 'gcloud monitoring list'
abbr -a gcof 'git commit --force'
abbr -a gco 'git checkout'
abbr -a gco 'git commit'
abbr -a gcov 'git commit --verbose'
abbr -a gcpubsub 'gcloud pubsub'
abbr -a gcpubsubl 'gcloud pubsub list'
abbr -a gcsql 'gcloud sql'
abbr -a gcsqll 'gcloud sql list'
abbr -a gcstorage 'gcloud storage'
abbr -a gcstoragel 'gcloud storage list'
abbr -a gd 'git diff'
abbr -a gdif 'git diff --force'
abbr -a gdi 'git diff'
abbr -a gdiv 'git diff --verbose'
abbr -a gfef 'git fetch --force'
abbr -a gfe 'git fetch'
abbr -a gfev 'git fetch --verbose'
abbr -a gf 'git fetch'
abbr -a gfind 'git log -G'
abbr -a gforget 'git rm --cached'
abbr -a gfsckf 'git fsck --force'
abbr -a gfsck 'git fsck'
abbr -a ggcf 'git gc --force'
abbr -a ggc 'git gc'
abbr -a gg 'git grep'
abbr -a ggrepf 'git grep --force'
abbr -a ggrep 'git grep'
abbr -a ggrf 'git grep --force'
abbr -a ggr 'git grep'
abbr -a ggrv 'git grep --verbose'
abbr -a ghist 'git log --author="$(git config user.name)"'
abbr -a gi 'git init'
abbr -a ginf 'git init --force'
abbr -a gin 'git init'
abbr -a ginv 'git init --verbose'
abbr -a glast 'git log -1 HEAD'
abbr -a gl 'git log'
abbr -a gload 'git checkout . && git clean -fd'
abbr -a glof 'git log --force'
abbr -a glo 'git log'
abbr -a glogstat 'git log --oneline --graph --decorate --stat'
abbr -a glov 'git log --verbose'
abbr -a gmef 'git merge --force'
abbr -a gme 'git merge'
abbr -a gmev 'git merge --verbose'
abbr -a gm 'git merge'
abbr -a gmine 'git log --author="$(git config user.name)"'
abbr -a gmvf 'git mv --force'
abbr -a gmv 'git mv'
abbr -a gob 'go build .'
abbr -a gor 'go run .'
abbr -a got 'go test ./...'
abbr -a gp 'git push'
abbr -a gpick 'git cherry-pick'
abbr -a gpl 'git pull'
abbr -a gps 'git push'
abbr -a gpuf 'git push --force'
abbr -a gpu 'git push'
abbr -a gpullr 'git pull --rebase'
abbr -a gpushf 'git push --force-with-lease'
abbr -a gpuv 'git push --verbose'
abbr -a gra 'grep -a'
abbr -a gref 'git rebase --force'
abbr -a greflogf 'git reflog --force'
abbr -a greflog 'git reflog'
abbr -a gre 'git rebase'
abbr -a greset 'git reset --hard HEAD'
abbr -a grevertf 'git revert --force'
abbr -a grevert 'git revert'
abbr -a grev 'git rebase --verbose'
abbr -a grf 'grep -f'
abbr -a gr 'git rebase'
abbr -a grh 'grep -h'
abbr -a gri 'grep -i'
abbr -a grl 'grep -l'
abbr -a grmf 'git rm --force'
abbr -a grm 'git rm'
abbr -a grn 'grep -n'
abbr -a grR 'grep -R'
abbr -a grt 'grep -t'
abbr -a gru 'grep -u'
abbr -a grune 'git remote prune origin'
abbr -a grv 'grep -v'
abbr -a gsave 'git add . && git commit -m "savepoint: $(date)"'
abbr -a gs 'git status'
abbr -a gshf 'git show --force'
abbr -a gsh 'git show'
abbr -a gshowf 'git show --force'
abbr -a gshow 'git show'
abbr -a gshv 'git show --verbose'
abbr -a gsm 'git stash push -m'
abbr -a gstasha 'git stash apply'
abbr -a gstashd 'git stash drop'
abbr -a gstashl 'git stash list'
abbr -a gstashp 'git stash pop'
abbr -a gstats 'git shortlog -sn'
abbr -a gstd 'git stash drop'
abbr -a gstf 'git status --force'
abbr -a gst 'git stash'
abbr -a gst 'git status'
abbr -a gstv 'git status --verbose'
abbr -a gsyncforce 'git fetch --all && git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)'
abbr -a gsync 'git pull origin main && git push origin main'
abbr -a gtaf 'git tag --force'
abbr -a gtagf 'git tag --force'
abbr -a gtag 'git tag'
abbr -a gta 'git tag'
abbr -a gtav 'git tag --verbose'
abbr -a gt 'git tag'
abbr -a gundo 'git reset --soft HEAD~1'
abbr -a gw 'git worktree'
abbr -a gwof 'git worktree --force'
abbr -a gwo 'git worktree'
abbr -a gwov 'git worktree --verbose'
abbr -a gza 'gzip -a'
abbr -a gzf 'gzip -f'
abbr -a gzh 'gzip -h'
abbr -a gzi 'gzip -i'
abbr -a gzl 'gzip -l'
abbr -a gzn 'gzip -n'
abbr -a gzR 'gzip -R'
abbr -a gzt 'gzip -t'
abbr -a gzu 'gzip -u'
abbr -a gzv 'gzip -v'
abbr -a hcr 'helm create'
abbr -a hde 'helm dependency'
abbr -a hen 'helm env'
abbr -a hge 'helm get'
abbr -a hg 'history | grep'
abbr -a h 'history'
abbr -a hin 'helm install'
abbr -a hlcr 'helm create'
abbr -a hlde 'helm dependency'
abbr -a hlen 'helm env'
abbr -a hlge 'helm get'
abbr -a hli 'helm list'
abbr -a hlin 'helm install'
abbr -a hlli 'helm list'
abbr -a hlpa 'helm package'
abbr -a hlpl 'helm plugin'
abbr -a hlre 'helm repo'
abbr -a hlro 'helm rollback'
abbr -a hlse 'helm search'
abbr -a hlsh 'helm show'
abbr -a hlst 'helm status'
abbr -a hlte 'helm test'
abbr -a hlup 'helm upgrade'
abbr -a home 'cd ~'
abbr -a hpa 'helm package'
abbr -a hpl 'helm plugin'
abbr -a hre 'helm repo'
abbr -a hro 'helm rollback'
abbr -a hse 'helm search'
abbr -a hsh 'helm show'
abbr -a hst 'helm status'
abbr -a hte 'helm test'
abbr -a hup 'helm upgrade'
abbr -a ins
abbr -a ins -k update
abbr -a ipa 'ip -a'
abbr -a ipa 'ip -br addr'
abbr -a ipf 'ip -f'
abbr -a iph 'ip -h'
abbr -a ipi 'ip -i'
abbr -a ipl 'ip -br link'
abbr -a ipl 'ip -l'
abbr -a ipn 'ip -n'
abbr -a ipR 'ip -R'
abbr -a ipt 'ip -t'
abbr -a ipu 'ip -u'
abbr -a ipv 'ip -v'
abbr -a kacj 'kubectl apply cj'
abbr -a kacm 'kubectl apply cm'
abbr -a kadeploy 'kubectl apply deploy'
abbr -a kads 'kubectl apply ds'
abbr -a kahpa 'kubectl apply hpa'
abbr -a kaing 'kubectl apply ing'
abbr -a kajob 'kubectl apply job'
abbr -a kalimitrange 'kubectl apply limitrange'
abbr -a kancj 'kubectl annotate cj'
abbr -a kancm 'kubectl annotate cm'
abbr -a kandeploy 'kubectl annotate deploy'
abbr -a kands 'kubectl annotate ds'
abbr -a kanhpa 'kubectl annotate hpa'
abbr -a kaning 'kubectl annotate ing'
abbr -a kanjob 'kubectl annotate job'
abbr -a kanlimitrange 'kubectl annotate limitrange'
abbr -a kannode 'kubectl annotate node'
abbr -a kanns 'kubectl annotate ns'
abbr -a kanode 'kubectl apply node'
abbr -a kanpdb 'kubectl annotate pdb'
abbr -a kanpods 'kubectl annotate pods'
abbr -a kanpvc 'kubectl annotate pvc'
abbr -a kanpv 'kubectl annotate pv'
abbr -a kanquota 'kubectl annotate quota'
abbr -a kanrc 'kubectl annotate rc'
abbr -a kanrs 'kubectl annotate rs'
abbr -a kansa 'kubectl annotate sa'
abbr -a kansecret 'kubectl annotate secret'
abbr -a kans 'kubectl apply ns'
abbr -a kansts 'kubectl annotate sts'
abbr -a kansvc 'kubectl annotate svc'
abbr -a kapcj 'kubectl apply cj'
abbr -a kapcm 'kubectl apply cm'
abbr -a kapdb 'kubectl apply pdb'
abbr -a kapdeploy 'kubectl apply deploy'
abbr -a kapds 'kubectl apply ds'
abbr -a kaphpa 'kubectl apply hpa'
abbr -a kaping 'kubectl apply ing'
abbr -a kapjob 'kubectl apply job'
abbr -a kaplimitrange 'kubectl apply limitrange'
abbr -a kapnode 'kubectl apply node'
abbr -a kapns 'kubectl apply ns'
abbr -a kapods 'kubectl apply pods'
abbr -a kappdb 'kubectl apply pdb'
abbr -a kappods 'kubectl apply pods'
abbr -a kappvc 'kubectl apply pvc'
abbr -a kappv 'kubectl apply pv'
abbr -a kapquota 'kubectl apply quota'
abbr -a kaprc 'kubectl apply rc'
abbr -a kaprs 'kubectl apply rs'
abbr -a kapsa 'kubectl apply sa'
abbr -a kapsecret 'kubectl apply secret'
abbr -a kapsts 'kubectl apply sts'
abbr -a kapsvc 'kubectl apply svc'
abbr -a kapvc 'kubectl apply pvc'
abbr -a kapv 'kubectl apply pv'
abbr -a kaquota 'kubectl apply quota'
abbr -a karc 'kubectl apply rc'
abbr -a kars 'kubectl apply rs'
abbr -a kasa 'kubectl apply sa'
abbr -a kasecret 'kubectl apply secret'
abbr -a kasts 'kubectl apply sts'
abbr -a kasvc 'kubectl apply svc'
abbr -a katcj 'kubectl attach cj'
abbr -a katcm 'kubectl attach cm'
abbr -a katdeploy 'kubectl attach deploy'
abbr -a katds 'kubectl attach ds'
abbr -a kathpa 'kubectl attach hpa'
abbr -a kating 'kubectl attach ing'
abbr -a katjob 'kubectl attach job'
abbr -a katlimitrange 'kubectl attach limitrange'
abbr -a katnode 'kubectl attach node'
abbr -a katns 'kubectl attach ns'
abbr -a katpdb 'kubectl attach pdb'
abbr -a katpods 'kubectl attach pods'
abbr -a katpvc 'kubectl attach pvc'
abbr -a katpv 'kubectl attach pv'
abbr -a katquota 'kubectl attach quota'
abbr -a katrc 'kubectl attach rc'
abbr -a katrs 'kubectl attach rs'
abbr -a katsa 'kubectl attach sa'
abbr -a katsecret 'kubectl attach secret'
abbr -a katsts 'kubectl attach sts'
abbr -a katsvc 'kubectl attach svc'
abbr -a kaucj 'kubectl autoscale cj'
abbr -a kaucm 'kubectl autoscale cm'
abbr -a kaudeploy 'kubectl autoscale deploy'
abbr -a kauds 'kubectl autoscale ds'
abbr -a kauhpa 'kubectl autoscale hpa'
abbr -a kauing 'kubectl autoscale ing'
abbr -a kaujob 'kubectl autoscale job'
abbr -a kaulimitrange 'kubectl autoscale limitrange'
abbr -a kaunode 'kubectl autoscale node'
abbr -a kauns 'kubectl autoscale ns'
abbr -a kaupdb 'kubectl autoscale pdb'
abbr -a kaupods 'kubectl autoscale pods'
abbr -a kaupvc 'kubectl autoscale pvc'
abbr -a kaupv 'kubectl autoscale pv'
abbr -a kauquota 'kubectl autoscale quota'
abbr -a kaurc 'kubectl autoscale rc'
abbr -a kaurs 'kubectl autoscale rs'
abbr -a kausa 'kubectl autoscale sa'
abbr -a kausecret 'kubectl autoscale secret'
abbr -a kausts 'kubectl autoscale sts'
abbr -a kausvc 'kubectl autoscale svc'
abbr -a kccj 'kubectl cp cj'
abbr -a kccm 'kubectl cp cm'
abbr -a kcdeploy 'kubectl cp deploy'
abbr -a kcds 'kubectl cp ds'
abbr -a kchpa 'kubectl cp hpa'
abbr -a kcing 'kubectl cp ing'
abbr -a kcjob 'kubectl cp job'
abbr -a kclimitrange 'kubectl cp limitrange'
abbr -a kcnode 'kubectl cp node'
abbr -a kcns 'kubectl cp ns'
abbr -a kcpcj 'kubectl cp cj'
abbr -a kcpcm 'kubectl cp cm'
abbr -a kcpdb 'kubectl cp pdb'
abbr -a kcpdeploy 'kubectl cp deploy'
abbr -a kcpds 'kubectl cp ds'
abbr -a kcphpa 'kubectl cp hpa'
abbr -a kcping 'kubectl cp ing'
abbr -a kcpjob 'kubectl cp job'
abbr -a kcplimitrange 'kubectl cp limitrange'
abbr -a kcpnode 'kubectl cp node'
abbr -a kcpns 'kubectl cp ns'
abbr -a kcpods 'kubectl cp pods'
abbr -a kcppdb 'kubectl cp pdb'
abbr -a kcppods 'kubectl cp pods'
abbr -a kcppvc 'kubectl cp pvc'
abbr -a kcppv 'kubectl cp pv'
abbr -a kcpquota 'kubectl cp quota'
abbr -a kcprc 'kubectl cp rc'
abbr -a kcprs 'kubectl cp rs'
abbr -a kcpsa 'kubectl cp sa'
abbr -a kcpsecret 'kubectl cp secret'
abbr -a kcpsts 'kubectl cp sts'
abbr -a kcpsvc 'kubectl cp svc'
abbr -a kcpvc 'kubectl cp pvc'
abbr -a kcpv 'kubectl cp pv'
abbr -a kcquota 'kubectl cp quota'
abbr -a kcrc 'kubectl cp rc'
abbr -a kcrs 'kubectl cp rs'
abbr -a kcsa 'kubectl cp sa'
abbr -a kcsecret 'kubectl cp secret'
abbr -a kcsts 'kubectl cp sts'
abbr -a kcsvc 'kubectl cp svc'
abbr -a kdcj 'kubectl describe cj'
abbr -a kdcm 'kubectl describe cm'
abbr -a kddeploy 'kubectl describe deploy'
abbr -a kdds 'kubectl describe ds'
abbr -a kdecj 'kubectl describe cj'
abbr -a kdecm 'kubectl describe cm'
abbr -a kdedeploy 'kubectl describe deploy'
abbr -a kdeds 'kubectl describe ds'
abbr -a kdehpa 'kubectl describe hpa'
abbr -a kdeing 'kubectl describe ing'
abbr -a kdejob 'kubectl describe job'
abbr -a kdelimitrange 'kubectl describe limitrange'
abbr -a kdenode 'kubectl describe node'
abbr -a kdens 'kubectl describe ns'
abbr -a kdepdb 'kubectl describe pdb'
abbr -a kdepods 'kubectl describe pods'
abbr -a kdepvc 'kubectl describe pvc'
abbr -a kdepv 'kubectl describe pv'
abbr -a kdequota 'kubectl describe quota'
abbr -a kderc 'kubectl describe rc'
abbr -a kders 'kubectl describe rs'
abbr -a kdesa 'kubectl describe sa'
abbr -a kdesecret 'kubectl describe secret'
abbr -a kdests 'kubectl describe sts'
abbr -a kdesvc 'kubectl describe svc'
abbr -a kdhpa 'kubectl describe hpa'
abbr -a kding 'kubectl describe ing'
abbr -a kdjob 'kubectl describe job'
abbr -a kdlimitrange 'kubectl describe limitrange'
abbr -a kdnode 'kubectl describe node'
abbr -a kdns 'kubectl describe ns'
abbr -a kdpdb 'kubectl describe pdb'
abbr -a kdpods 'kubectl describe pods'
abbr -a kdpvc 'kubectl describe pvc'
abbr -a kdpv 'kubectl describe pv'
abbr -a kdquota 'kubectl describe quota'
abbr -a kdrc 'kubectl describe rc'
abbr -a kdrs 'kubectl describe rs'
abbr -a kdsa 'kubectl describe sa'
abbr -a kdsecret 'kubectl describe secret'
abbr -a kdsts 'kubectl describe sts'
abbr -a kdsvc 'kubectl describe svc'
abbr -a kecj 'kubectl edit cj'
abbr -a kecm 'kubectl edit cm'
abbr -a kedcj 'kubectl edit cj'
abbr -a kedcm 'kubectl edit cm'
abbr -a keddeploy 'kubectl edit deploy'
abbr -a kedds 'kubectl edit ds'
abbr -a kedeploy 'kubectl edit deploy'
abbr -a kedhpa 'kubectl edit hpa'
abbr -a keding 'kubectl edit ing'
abbr -a kedjob 'kubectl edit job'
abbr -a kedlimitrange 'kubectl edit limitrange'
abbr -a kednode 'kubectl edit node'
abbr -a kedns 'kubectl edit ns'
abbr -a kedpdb 'kubectl edit pdb'
abbr -a kedpods 'kubectl edit pods'
abbr -a kedpvc 'kubectl edit pvc'
abbr -a kedpv 'kubectl edit pv'
abbr -a kedquota 'kubectl edit quota'
abbr -a kedrc 'kubectl edit rc'
abbr -a kedrs 'kubectl edit rs'
abbr -a kedsa 'kubectl edit sa'
abbr -a kedsecret 'kubectl edit secret'
abbr -a keds 'kubectl edit ds'
abbr -a kedsts 'kubectl edit sts'
abbr -a kedsvc 'kubectl edit svc'
abbr -a kehpa 'kubectl edit hpa'
abbr -a keing 'kubectl edit ing'
abbr -a kejob 'kubectl edit job'
abbr -a kelimitrange 'kubectl edit limitrange'
abbr -a kenode 'kubectl edit node'
abbr -a kens 'kubectl edit ns'
abbr -a kepdb 'kubectl edit pdb'
abbr -a kepods 'kubectl edit pods'
abbr -a kepvc 'kubectl edit pvc'
abbr -a kepv 'kubectl edit pv'
abbr -a kequota 'kubectl edit quota'
abbr -a kerc 'kubectl edit rc'
abbr -a kers 'kubectl edit rs'
abbr -a kesa 'kubectl edit sa'
abbr -a kesecret 'kubectl edit secret'
abbr -a kests 'kubectl edit sts'
abbr -a kesvc 'kubectl edit svc'
abbr -a kexcj 'kubectl expose cj'
abbr -a kexcm 'kubectl expose cm'
abbr -a kexdeploy 'kubectl expose deploy'
abbr -a kexds 'kubectl expose ds'
abbr -a kexhpa 'kubectl expose hpa'
abbr -a kexing 'kubectl expose ing'
abbr -a kexjob 'kubectl expose job'
abbr -a kexlimitrange 'kubectl expose limitrange'
abbr -a kexnode 'kubectl expose node'
abbr -a kexns 'kubectl expose ns'
abbr -a kexpdb 'kubectl expose pdb'
abbr -a kexpods 'kubectl expose pods'
abbr -a kexpvc 'kubectl expose pvc'
abbr -a kexpv 'kubectl expose pv'
abbr -a kexquota 'kubectl expose quota'
abbr -a kexrc 'kubectl expose rc'
abbr -a kexrs 'kubectl expose rs'
abbr -a kexsa 'kubectl expose sa'
abbr -a kexsecret 'kubectl expose secret'
abbr -a kexsts 'kubectl expose sts'
abbr -a kexsvc 'kubectl expose svc'
abbr -a kgcj 'kubectl get cj'
abbr -a kgcm 'kubectl get cm'
abbr -a kgdeploy 'kubectl get deploy'
abbr -a kgds 'kubectl get ds'
abbr -a kgecj 'kubectl get cj'
abbr -a kgecm 'kubectl get cm'
abbr -a kgedeploy 'kubectl get deploy'
abbr -a kgeds 'kubectl get ds'
abbr -a kgehpa 'kubectl get hpa'
abbr -a kgeing 'kubectl get ing'
abbr -a kgejob 'kubectl get job'
abbr -a kgelimitrange 'kubectl get limitrange'
abbr -a kgenode 'kubectl get node'
abbr -a kgens 'kubectl get ns'
abbr -a kgepdb 'kubectl get pdb'
abbr -a kgepods 'kubectl get pods'
abbr -a kgepvc 'kubectl get pvc'
abbr -a kgepv 'kubectl get pv'
abbr -a kgequota 'kubectl get quota'
abbr -a kgerc 'kubectl get rc'
abbr -a kgers 'kubectl get rs'
abbr -a kgesa 'kubectl get sa'
abbr -a kgesecret 'kubectl get secret'
abbr -a kgests 'kubectl get sts'
abbr -a kgesvc 'kubectl get svc'
abbr -a kghpa 'kubectl get hpa'
abbr -a kging 'kubectl get ing'
abbr -a kgjob 'kubectl get job'
abbr -a kglimitrange 'kubectl get limitrange'
abbr -a kgnode 'kubectl get node'
abbr -a kgns 'kubectl get ns'
abbr -a kgpdb 'kubectl get pdb'
abbr -a kgpods 'kubectl get pods'
abbr -a kgpvc 'kubectl get pvc'
abbr -a kgpv 'kubectl get pv'
abbr -a kgquota 'kubectl get quota'
abbr -a kgrc 'kubectl get rc'
abbr -a kgrs 'kubectl get rs'
abbr -a kgsa 'kubectl get sa'
abbr -a kgsecret 'kubectl get secret'
abbr -a kgsts 'kubectl get sts'
abbr -a kgsvc 'kubectl get svc'
abbr -a killi 'kill -9'
abbr -a klacj 'kubectl label cj'
abbr -a klacm 'kubectl label cm'
abbr -a kladeploy 'kubectl label deploy'
abbr -a klads 'kubectl label ds'
abbr -a klahpa 'kubectl label hpa'
abbr -a klaing 'kubectl label ing'
abbr -a klajob 'kubectl label job'
abbr -a klalimitrange 'kubectl label limitrange'
abbr -a klanode 'kubectl label node'
abbr -a klans 'kubectl label ns'
abbr -a klapdb 'kubectl label pdb'
abbr -a klapods 'kubectl label pods'
abbr -a klapvc 'kubectl label pvc'
abbr -a klapv 'kubectl label pv'
abbr -a klaquota 'kubectl label quota'
abbr -a klarc 'kubectl label rc'
abbr -a klars 'kubectl label rs'
abbr -a klasa 'kubectl label sa'
abbr -a klasecret 'kubectl label secret'
abbr -a klasts 'kubectl label sts'
abbr -a klasvc 'kubectl label svc'
abbr -a klcj 'kubectl logs cj'
abbr -a klcm 'kubectl logs cm'
abbr -a kldeploy 'kubectl logs deploy'
abbr -a klds 'kubectl logs ds'
abbr -a klhpa 'kubectl logs hpa'
abbr -a kling 'kubectl logs ing'
abbr -a kljob 'kubectl logs job'
abbr -a kllimitrange 'kubectl logs limitrange'
abbr -a klnode 'kubectl logs node'
abbr -a klns 'kubectl logs ns'
abbr -a klocj 'kubectl logs cj'
abbr -a klocm 'kubectl logs cm'
abbr -a klodeploy 'kubectl logs deploy'
abbr -a klods 'kubectl logs ds'
abbr -a klohpa 'kubectl logs hpa'
abbr -a kloing 'kubectl logs ing'
abbr -a klojob 'kubectl logs job'
abbr -a klolimitrange 'kubectl logs limitrange'
abbr -a klonode 'kubectl logs node'
abbr -a klons 'kubectl logs ns'
abbr -a klopdb 'kubectl logs pdb'
abbr -a klopods 'kubectl logs pods'
abbr -a klopvc 'kubectl logs pvc'
abbr -a klopv 'kubectl logs pv'
abbr -a kloquota 'kubectl logs quota'
abbr -a klorc 'kubectl logs rc'
abbr -a klors 'kubectl logs rs'
abbr -a klosa 'kubectl logs sa'
abbr -a klosecret 'kubectl logs secret'
abbr -a klosts 'kubectl logs sts'
abbr -a klosvc 'kubectl logs svc'
abbr -a klpdb 'kubectl logs pdb'
abbr -a klpods 'kubectl logs pods'
abbr -a klpvc 'kubectl logs pvc'
abbr -a klpv 'kubectl logs pv'
abbr -a klquota 'kubectl logs quota'
abbr -a klrc 'kubectl logs rc'
abbr -a klrs 'kubectl logs rs'
abbr -a klsa 'kubectl logs sa'
abbr -a klsecret 'kubectl logs secret'
abbr -a klsts 'kubectl logs sts'
abbr -a klsvc 'kubectl logs svc'
abbr -a kpacj 'kubectl patch cj'
abbr -a kpacm 'kubectl patch cm'
abbr -a kpadeploy 'kubectl patch deploy'
abbr -a kpads 'kubectl patch ds'
abbr -a kpahpa 'kubectl patch hpa'
abbr -a kpaing 'kubectl patch ing'
abbr -a kpajob 'kubectl patch job'
abbr -a kpalimitrange 'kubectl patch limitrange'
abbr -a kpanode 'kubectl patch node'
abbr -a kpans 'kubectl patch ns'
abbr -a kpapdb 'kubectl patch pdb'
abbr -a kpapods 'kubectl patch pods'
abbr -a kpapvc 'kubectl patch pvc'
abbr -a kpapv 'kubectl patch pv'
abbr -a kpaquota 'kubectl patch quota'
abbr -a kparc 'kubectl patch rc'
abbr -a kpars 'kubectl patch rs'
abbr -a kpasa 'kubectl patch sa'
abbr -a kpasecret 'kubectl patch secret'
abbr -a kpasts 'kubectl patch sts'
abbr -a kpasvc 'kubectl patch svc'
abbr -a kpcj 'kubectl patch cj'
abbr -a kpcm 'kubectl patch cm'
abbr -a kpdeploy 'kubectl patch deploy'
abbr -a kpds 'kubectl patch ds'
abbr -a kphpa 'kubectl patch hpa'
abbr -a kping 'kubectl patch ing'
abbr -a kpjob 'kubectl patch job'
abbr -a kplimitrange 'kubectl patch limitrange'
abbr -a kpnode 'kubectl patch node'
abbr -a kpns 'kubectl patch ns'
abbr -a kpocj 'kubectl port-forward cj'
abbr -a kpocm 'kubectl port-forward cm'
abbr -a kpodeploy 'kubectl port-forward deploy'
abbr -a kpods 'kubectl port-forward ds'
abbr -a kpohpa 'kubectl port-forward hpa'
abbr -a kpoing 'kubectl port-forward ing'
abbr -a kpojob 'kubectl port-forward job'
abbr -a kpolimitrange 'kubectl port-forward limitrange'
abbr -a kponode 'kubectl port-forward node'
abbr -a kpons 'kubectl port-forward ns'
abbr -a kpopdb 'kubectl port-forward pdb'
abbr -a kpopods 'kubectl port-forward pods'
abbr -a kpopvc 'kubectl port-forward pvc'
abbr -a kpopv 'kubectl port-forward pv'
abbr -a kpoquota 'kubectl port-forward quota'
abbr -a kporc 'kubectl port-forward rc'
abbr -a kpors 'kubectl port-forward rs'
abbr -a kposa 'kubectl port-forward sa'
abbr -a kposecret 'kubectl port-forward secret'
abbr -a kposts 'kubectl port-forward sts'
abbr -a kposvc 'kubectl port-forward svc'
abbr -a kppdb 'kubectl patch pdb'
abbr -a kppods 'kubectl patch pods'
abbr -a kppvc 'kubectl patch pvc'
abbr -a kppv 'kubectl patch pv'
abbr -a kpquota 'kubectl patch quota'
abbr -a kprc 'kubectl patch rc'
abbr -a kprs 'kubectl patch rs'
abbr -a kpsa 'kubectl patch sa'
abbr -a kpsecret 'kubectl patch secret'
abbr -a kpsts 'kubectl patch sts'
abbr -a kpsvc 'kubectl patch svc'
abbr -a krcj 'kubectl rollout cj'
abbr -a krcm 'kubectl rollout cm'
abbr -a krdeploy 'kubectl rollout deploy'
abbr -a krds 'kubectl rollout ds'
abbr -a krhpa 'kubectl rollout hpa'
abbr -a kring 'kubectl rollout ing'
abbr -a krjob 'kubectl rollout job'
abbr -a krlimitrange 'kubectl rollout limitrange'
abbr -a krnode 'kubectl rollout node'
abbr -a krns 'kubectl rollout ns'
abbr -a krocj 'kubectl rollout cj'
abbr -a krocm 'kubectl rollout cm'
abbr -a krodeploy 'kubectl rollout deploy'
abbr -a krods 'kubectl rollout ds'
abbr -a krohpa 'kubectl rollout hpa'
abbr -a kroing 'kubectl rollout ing'
abbr -a krojob 'kubectl rollout job'
abbr -a krolimitrange 'kubectl rollout limitrange'
abbr -a kronode 'kubectl rollout node'
abbr -a krons 'kubectl rollout ns'
abbr -a kropdb 'kubectl rollout pdb'
abbr -a kropods 'kubectl rollout pods'
abbr -a kropvc 'kubectl rollout pvc'
abbr -a kropv 'kubectl rollout pv'
abbr -a kroquota 'kubectl rollout quota'
abbr -a krorc 'kubectl rollout rc'
abbr -a krors 'kubectl rollout rs'
abbr -a krosa 'kubectl rollout sa'
abbr -a krosecret 'kubectl rollout secret'
abbr -a krosts 'kubectl rollout sts'
abbr -a krosvc 'kubectl rollout svc'
abbr -a krpdb 'kubectl rollout pdb'
abbr -a krpods 'kubectl rollout pods'
abbr -a krpvc 'kubectl rollout pvc'
abbr -a krpv 'kubectl rollout pv'
abbr -a krquota 'kubectl rollout quota'
abbr -a krrc 'kubectl rollout rc'
abbr -a krrs 'kubectl rollout rs'
abbr -a krsa 'kubectl rollout sa'
abbr -a krsecret 'kubectl rollout secret'
abbr -a krsts 'kubectl rollout sts'
abbr -a krsvc 'kubectl rollout svc'
abbr -a krucj 'kubectl run cj'
abbr -a krucm 'kubectl run cm'
abbr -a krudeploy 'kubectl run deploy'
abbr -a kruds 'kubectl run ds'
abbr -a kruhpa 'kubectl run hpa'
abbr -a kruing 'kubectl run ing'
abbr -a krujob 'kubectl run job'
abbr -a krulimitrange 'kubectl run limitrange'
abbr -a krunode 'kubectl run node'
abbr -a kruns 'kubectl run ns'
abbr -a krupdb 'kubectl run pdb'
abbr -a krupods 'kubectl run pods'
abbr -a krupvc 'kubectl run pvc'
abbr -a krupv 'kubectl run pv'
abbr -a kruquota 'kubectl run quota'
abbr -a krurc 'kubectl run rc'
abbr -a krurs 'kubectl run rs'
abbr -a krusa 'kubectl run sa'
abbr -a krusecret 'kubectl run secret'
abbr -a krusts 'kubectl run sts'
abbr -a krusvc 'kubectl run svc'
abbr -a ksccj 'kubectl scale cj'
abbr -a ksccm 'kubectl scale cm'
abbr -a kscdeploy 'kubectl scale deploy'
abbr -a kscds 'kubectl scale ds'
abbr -a kschpa 'kubectl scale hpa'
abbr -a kscing 'kubectl scale ing'
abbr -a kscj 'kubectl scale cj'
abbr -a kscjob 'kubectl scale job'
abbr -a ksclimitrange 'kubectl scale limitrange'
abbr -a kscm 'kubectl scale cm'
abbr -a kscnode 'kubectl scale node'
abbr -a kscns 'kubectl scale ns'
abbr -a kscpdb 'kubectl scale pdb'
abbr -a kscpods 'kubectl scale pods'
abbr -a kscpvc 'kubectl scale pvc'
abbr -a kscpv 'kubectl scale pv'
abbr -a kscquota 'kubectl scale quota'
abbr -a kscrc 'kubectl scale rc'
abbr -a kscrs 'kubectl scale rs'
abbr -a kscsa 'kubectl scale sa'
abbr -a kscsecret 'kubectl scale secret'
abbr -a kscsts 'kubectl scale sts'
abbr -a kscsvc 'kubectl scale svc'
abbr -a ksdeploy 'kubectl scale deploy'
abbr -a ksds 'kubectl scale ds'
abbr -a kshpa 'kubectl scale hpa'
abbr -a ksing 'kubectl scale ing'
abbr -a ksjob 'kubectl scale job'
abbr -a kslimitrange 'kubectl scale limitrange'
abbr -a ksnode 'kubectl scale node'
abbr -a ksns 'kubectl scale ns'
abbr -a kspdb 'kubectl scale pdb'
abbr -a kspods 'kubectl scale pods'
abbr -a kspvc 'kubectl scale pvc'
abbr -a kspv 'kubectl scale pv'
abbr -a ksquota 'kubectl scale quota'
abbr -a ksrc 'kubectl scale rc'
abbr -a ksrs 'kubectl scale rs'
abbr -a kssa 'kubectl scale sa'
abbr -a kssecret 'kubectl scale secret'
abbr -a kssts 'kubectl scale sts'
abbr -a kssvc 'kubectl scale svc'
abbr -a ktcj 'kubectl top cj'
abbr -a ktcm 'kubectl top cm'
abbr -a ktdeploy 'kubectl top deploy'
abbr -a ktds 'kubectl top ds'
abbr -a kthpa 'kubectl top hpa'
abbr -a kting 'kubectl top ing'
abbr -a ktjob 'kubectl top job'
abbr -a ktlimitrange 'kubectl top limitrange'
abbr -a ktnode 'kubectl top node'
abbr -a ktns 'kubectl top ns'
abbr -a ktocj 'kubectl top cj'
abbr -a ktocm 'kubectl top cm'
abbr -a ktodeploy 'kubectl top deploy'
abbr -a ktods 'kubectl top ds'
abbr -a ktohpa 'kubectl top hpa'
abbr -a ktoing 'kubectl top ing'
abbr -a ktojob 'kubectl top job'
abbr -a ktolimitrange 'kubectl top limitrange'
abbr -a ktonode 'kubectl top node'
abbr -a ktons 'kubectl top ns'
abbr -a ktopdb 'kubectl top pdb'
abbr -a ktopods 'kubectl top pods'
abbr -a ktopvc 'kubectl top pvc'
abbr -a ktopv 'kubectl top pv'
abbr -a ktoquota 'kubectl top quota'
abbr -a ktorc 'kubectl top rc'
abbr -a ktors 'kubectl top rs'
abbr -a ktosa 'kubectl top sa'
abbr -a ktosecret 'kubectl top secret'
abbr -a ktosts 'kubectl top sts'
abbr -a ktosvc 'kubectl top svc'
abbr -a ktpdb 'kubectl top pdb'
abbr -a ktpods 'kubectl top pods'
abbr -a ktpvc 'kubectl top pvc'
abbr -a ktpv 'kubectl top pv'
abbr -a ktquota 'kubectl top quota'
abbr -a ktrc 'kubectl top rc'
abbr -a ktrs 'kubectl top rs'
abbr -a ktsa 'kubectl top sa'
abbr -a ktsecret 'kubectl top secret'
abbr -a ktsts 'kubectl top sts'
abbr -a ktsvc 'kubectl top svc'
abbr -a lla 'ls -la'
abbr -a llh 'ls -lh'
abbr -a lsa 'ls -a'
abbr -a lsf 'ls -f'
abbr -a lsh 'ls -h'
abbr -a lsi 'ls -i'
abbr -a lsl 'ls -l'
abbr -a lsn 'ls -n'
abbr -a lsp
abbr -a lsR 'ls -R'
abbr -a lst 'ls -t'
abbr -a lsu 'ls -u'
abbr -a lsv 'ls -v'
abbr -a meminfo 'free -h && cat /proc/meminfo'
abbr -a mvf 'mv -f'
abbr -a neo neofetch
abbr -a nixau 'nix-env autoremove'
abbr -a nixch 'nix-env check'
abbr -a nixcl 'nix-env clean'
abbr -a nixin 'nix-env install'
abbr -a nixli 'nix-env list'
abbr -a nixre 'nix-env remove'
abbr -a nixse 'nix-env search'
abbr -a nixso 'nix-env sources'
abbr -a nixup 'nix-env update'
abbr -a nma 'nmcli -a'
abbr -a nmf 'nmcli -f'
abbr -a nmh 'nmcli -h'
abbr -a nmi 'nmcli -i'
abbr -a nml 'nmcli -l'
abbr -a nmn 'nmcli -n'
abbr -a nmR 'nmcli -R'
abbr -a nmt 'nmcli -t'
abbr -a nmu 'nmcli -u'
abbr -a nmv 'nmcli -v'
abbr -a nowdate 'date "+%d-%m-%Y"'
abbr -a nowdate 'date +"%d-%m-%Y"'
abbr -a now 'date "+%T"'
abbr -a now 'date +"%T"'
abbr -a nrb 'npm run build'
abbr -a nrd 'npm run dev'
abbr -a nrs 'npm run start'
abbr -a paau 'paru autoremove'
abbr -a pacau 'pacman autoremove'
abbr -a pacch 'pacman check'
abbr -a paccl 'pacman clean'
abbr -a pach 'paru check'
abbr -a pacin 'pacman install'
abbr -a pacli 'pacman list'
abbr -a pacl 'paru clean'
abbr -a pacre 'pacman remove'
abbr -a pacse 'pacman search'
abbr -a pacso 'pacman sources'
abbr -a pacup 'pacman update'
abbr -a pain 'paru install'
abbr -a pali 'paru list'
abbr -a pare 'paru remove'
abbr -a pase 'paru search'
abbr -a paso 'paru sources'
abbr -a path 'echo $PATH | tr ":" "\\n" | nl'
abbr -a path 'echo $PATH | tr ":" "\n" | nl'
abbr -a paup 'paru update'
abbr -a ping 'ping -c 5'
abbr -a ports 'netstat -tulanp'
abbr -a ports 'netstat -tulanp 2>/dev/null; or ss -tuln'
abbr -a prune-branches 'git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
abbr -a psa 'ps -a'
abbr -a psf 'ps -f'
abbr -a psg 'ps aux | grep -v grep | grep -i'
abbr -a psh 'ps -h'
abbr -a psi 'ps -i'
abbr -a psl 'ps -l'
abbr -a psn 'ps -n'
abbr -a psR 'ps -R'
abbr -a pst 'ps -t'
abbr -a psu 'ps -u'
abbr -a psv 'ps -v'
abbr -a py_math_cu_100 'python3 -c "print(100**3)"'
abbr -a py_math_cu_101 'python3 -c "print(101**3)"'
abbr -a py_math_cu_102 'python3 -c "print(102**3)"'
abbr -a py_math_cu_103 'python3 -c "print(103**3)"'
abbr -a py_math_cu_104 'python3 -c "print(104**3)"'
abbr -a py_math_cu_105 'python3 -c "print(105**3)"'
abbr -a py_math_cu_106 'python3 -c "print(106**3)"'
abbr -a py_math_cu_107 'python3 -c "print(107**3)"'
abbr -a py_math_cu_108 'python3 -c "print(108**3)"'
abbr -a py_math_cu_109 'python3 -c "print(109**3)"'
abbr -a py_math_cu_10 'python3 -c "print(10**3)"'
abbr -a py_math_cu_110 'python3 -c "print(110**3)"'
abbr -a py_math_cu_111 'python3 -c "print(111**3)"'
abbr -a py_math_cu_112 'python3 -c "print(112**3)"'
abbr -a py_math_cu_113 'python3 -c "print(113**3)"'
abbr -a py_math_cu_114 'python3 -c "print(114**3)"'
abbr -a py_math_cu_115 'python3 -c "print(115**3)"'
abbr -a py_math_cu_116 'python3 -c "print(116**3)"'
abbr -a py_math_cu_117 'python3 -c "print(117**3)"'
abbr -a py_math_cu_118 'python3 -c "print(118**3)"'
abbr -a py_math_cu_119 'python3 -c "print(119**3)"'
abbr -a py_math_cu_11 'python3 -c "print(11**3)"'
abbr -a py_math_cu_120 'python3 -c "print(120**3)"'
abbr -a py_math_cu_121 'python3 -c "print(121**3)"'
abbr -a py_math_cu_122 'python3 -c "print(122**3)"'
abbr -a py_math_cu_123 'python3 -c "print(123**3)"'
abbr -a py_math_cu_124 'python3 -c "print(124**3)"'
abbr -a py_math_cu_125 'python3 -c "print(125**3)"'
abbr -a py_math_cu_126 'python3 -c "print(126**3)"'
abbr -a py_math_cu_127 'python3 -c "print(127**3)"'
abbr -a py_math_cu_128 'python3 -c "print(128**3)"'
abbr -a py_math_cu_129 'python3 -c "print(129**3)"'
abbr -a py_math_cu_12 'python3 -c "print(12**3)"'
abbr -a py_math_cu_130 'python3 -c "print(130**3)"'
abbr -a py_math_cu_131 'python3 -c "print(131**3)"'
abbr -a py_math_cu_132 'python3 -c "print(132**3)"'
abbr -a py_math_cu_133 'python3 -c "print(133**3)"'
abbr -a py_math_cu_134 'python3 -c "print(134**3)"'
abbr -a py_math_cu_135 'python3 -c "print(135**3)"'
abbr -a py_math_cu_136 'python3 -c "print(136**3)"'
abbr -a py_math_cu_137 'python3 -c "print(137**3)"'
abbr -a py_math_cu_138 'python3 -c "print(138**3)"'
abbr -a py_math_cu_139 'python3 -c "print(139**3)"'
abbr -a py_math_cu_13 'python3 -c "print(13**3)"'
abbr -a py_math_cu_140 'python3 -c "print(140**3)"'
abbr -a py_math_cu_141 'python3 -c "print(141**3)"'
abbr -a py_math_cu_142 'python3 -c "print(142**3)"'
abbr -a py_math_cu_143 'python3 -c "print(143**3)"'
abbr -a py_math_cu_144 'python3 -c "print(144**3)"'
abbr -a py_math_cu_145 'python3 -c "print(145**3)"'
abbr -a py_math_cu_146 'python3 -c "print(146**3)"'
abbr -a py_math_cu_147 'python3 -c "print(147**3)"'
abbr -a py_math_cu_148 'python3 -c "print(148**3)"'
abbr -a py_math_cu_149 'python3 -c "print(149**3)"'
abbr -a py_math_cu_14 'python3 -c "print(14**3)"'
abbr -a py_math_cu_150 'python3 -c "print(150**3)"'
abbr -a py_math_cu_151 'python3 -c "print(151**3)"'
abbr -a py_math_cu_152 'python3 -c "print(152**3)"'
abbr -a py_math_cu_15 'python3 -c "print(15**3)"'
abbr -a py_math_cu_16 'python3 -c "print(16**3)"'
abbr -a py_math_cu_17 'python3 -c "print(17**3)"'
abbr -a py_math_cu_18 'python3 -c "print(18**3)"'
abbr -a py_math_cu_19 'python3 -c "print(19**3)"'
abbr -a py_math_cu_1 'python3 -c "print(1**3)"'
abbr -a py_math_cu_20 'python3 -c "print(20**3)"'
abbr -a py_math_cu_21 'python3 -c "print(21**3)"'
abbr -a py_math_cu_22 'python3 -c "print(22**3)"'
abbr -a py_math_cu_23 'python3 -c "print(23**3)"'
abbr -a py_math_cu_24 'python3 -c "print(24**3)"'
abbr -a py_math_cu_25 'python3 -c "print(25**3)"'
abbr -a py_math_cu_26 'python3 -c "print(26**3)"'
abbr -a py_math_cu_27 'python3 -c "print(27**3)"'
abbr -a py_math_cu_28 'python3 -c "print(28**3)"'
abbr -a py_math_cu_29 'python3 -c "print(29**3)"'
abbr -a py_math_cu_2 'python3 -c "print(2**3)"'
abbr -a py_math_cu_30 'python3 -c "print(30**3)"'
abbr -a py_math_cu_31 'python3 -c "print(31**3)"'
abbr -a py_math_cu_32 'python3 -c "print(32**3)"'
abbr -a py_math_cu_33 'python3 -c "print(33**3)"'
abbr -a py_math_cu_34 'python3 -c "print(34**3)"'
abbr -a py_math_cu_35 'python3 -c "print(35**3)"'
abbr -a py_math_cu_36 'python3 -c "print(36**3)"'
abbr -a py_math_cu_37 'python3 -c "print(37**3)"'
abbr -a py_math_cu_38 'python3 -c "print(38**3)"'
abbr -a py_math_cu_39 'python3 -c "print(39**3)"'
abbr -a py_math_cu_3 'python3 -c "print(3**3)"'
abbr -a py_math_cu_40 'python3 -c "print(40**3)"'
abbr -a py_math_cu_41 'python3 -c "print(41**3)"'
abbr -a py_math_cu_42 'python3 -c "print(42**3)"'
abbr -a py_math_cu_43 'python3 -c "print(43**3)"'
abbr -a py_math_cu_44 'python3 -c "print(44**3)"'
abbr -a py_math_cu_45 'python3 -c "print(45**3)"'
abbr -a py_math_cu_46 'python3 -c "print(46**3)"'
abbr -a py_math_cu_47 'python3 -c "print(47**3)"'
abbr -a py_math_cu_48 'python3 -c "print(48**3)"'
abbr -a py_math_cu_49 'python3 -c "print(49**3)"'
abbr -a py_math_cu_4 'python3 -c "print(4**3)"'
abbr -a py_math_cu_50 'python3 -c "print(50**3)"'
abbr -a py_math_cu_51 'python3 -c "print(51**3)"'
abbr -a py_math_cu_52 'python3 -c "print(52**3)"'
abbr -a py_math_cu_53 'python3 -c "print(53**3)"'
abbr -a py_math_cu_54 'python3 -c "print(54**3)"'
abbr -a py_math_cu_55 'python3 -c "print(55**3)"'
abbr -a py_math_cu_56 'python3 -c "print(56**3)"'
abbr -a py_math_cu_57 'python3 -c "print(57**3)"'
abbr -a py_math_cu_58 'python3 -c "print(58**3)"'
abbr -a py_math_cu_59 'python3 -c "print(59**3)"'
abbr -a py_math_cu_5 'python3 -c "print(5**3)"'
abbr -a py_math_cu_60 'python3 -c "print(60**3)"'
abbr -a py_math_cu_61 'python3 -c "print(61**3)"'
abbr -a py_math_cu_62 'python3 -c "print(62**3)"'
abbr -a py_math_cu_63 'python3 -c "print(63**3)"'
abbr -a py_math_cu_64 'python3 -c "print(64**3)"'
abbr -a py_math_cu_65 'python3 -c "print(65**3)"'
abbr -a py_math_cu_66 'python3 -c "print(66**3)"'
abbr -a py_math_cu_67 'python3 -c "print(67**3)"'
abbr -a py_math_cu_68 'python3 -c "print(68**3)"'
abbr -a py_math_cu_69 'python3 -c "print(69**3)"'
abbr -a py_math_cu_6 'python3 -c "print(6**3)"'
abbr -a py_math_cu_70 'python3 -c "print(70**3)"'
abbr -a py_math_cu_71 'python3 -c "print(71**3)"'
abbr -a py_math_cu_72 'python3 -c "print(72**3)"'
abbr -a py_math_cu_73 'python3 -c "print(73**3)"'
abbr -a py_math_cu_74 'python3 -c "print(74**3)"'
abbr -a py_math_cu_75 'python3 -c "print(75**3)"'
abbr -a py_math_cu_76 'python3 -c "print(76**3)"'
abbr -a py_math_cu_77 'python3 -c "print(77**3)"'
abbr -a py_math_cu_78 'python3 -c "print(78**3)"'
abbr -a py_math_cu_79 'python3 -c "print(79**3)"'
abbr -a py_math_cu_7 'python3 -c "print(7**3)"'
abbr -a py_math_cu_80 'python3 -c "print(80**3)"'
abbr -a py_math_cu_81 'python3 -c "print(81**3)"'
abbr -a py_math_cu_82 'python3 -c "print(82**3)"'
abbr -a py_math_cu_83 'python3 -c "print(83**3)"'
abbr -a py_math_cu_84 'python3 -c "print(84**3)"'
abbr -a py_math_cu_85 'python3 -c "print(85**3)"'
abbr -a py_math_cu_86 'python3 -c "print(86**3)"'
abbr -a py_math_cu_87 'python3 -c "print(87**3)"'
abbr -a py_math_cu_88 'python3 -c "print(88**3)"'
abbr -a py_math_cu_89 'python3 -c "print(89**3)"'
abbr -a py_math_cu_8 'python3 -c "print(8**3)"'
abbr -a py_math_cu_90 'python3 -c "print(90**3)"'
abbr -a py_math_cu_91 'python3 -c "print(91**3)"'
abbr -a py_math_cu_92 'python3 -c "print(92**3)"'
abbr -a py_math_cu_93 'python3 -c "print(93**3)"'
abbr -a py_math_cu_94 'python3 -c "print(94**3)"'
abbr -a py_math_cu_95 'python3 -c "print(95**3)"'
abbr -a py_math_cu_96 'python3 -c "print(96**3)"'
abbr -a py_math_cu_97 'python3 -c "print(97**3)"'
abbr -a py_math_cu_98 'python3 -c "print(98**3)"'
abbr -a py_math_cu_99 'python3 -c "print(99**3)"'
abbr -a py_math_cu_9 'python3 -c "print(9**3)"'
abbr -a py_math_sq_100 'python3 -c "print(100**2)"'
abbr -a py_math_sq_101 'python3 -c "print(101**2)"'
abbr -a py_math_sq_102 'python3 -c "print(102**2)"'
abbr -a py_math_sq_103 'python3 -c "print(103**2)"'
abbr -a py_math_sq_104 'python3 -c "print(104**2)"'
abbr -a py_math_sq_105 'python3 -c "print(105**2)"'
abbr -a py_math_sq_106 'python3 -c "print(106**2)"'
abbr -a py_math_sq_107 'python3 -c "print(107**2)"'
abbr -a py_math_sq_108 'python3 -c "print(108**2)"'
abbr -a py_math_sq_109 'python3 -c "print(109**2)"'
abbr -a py_math_sq_10 'python3 -c "print(10**2)"'
abbr -a py_math_sq_110 'python3 -c "print(110**2)"'
abbr -a py_math_sq_111 'python3 -c "print(111**2)"'
abbr -a py_math_sq_112 'python3 -c "print(112**2)"'
abbr -a py_math_sq_113 'python3 -c "print(113**2)"'
abbr -a py_math_sq_114 'python3 -c "print(114**2)"'
abbr -a py_math_sq_115 'python3 -c "print(115**2)"'
abbr -a py_math_sq_116 'python3 -c "print(116**2)"'
abbr -a py_math_sq_117 'python3 -c "print(117**2)"'
abbr -a py_math_sq_118 'python3 -c "print(118**2)"'
abbr -a py_math_sq_119 'python3 -c "print(119**2)"'
abbr -a py_math_sq_11 'python3 -c "print(11**2)"'
abbr -a py_math_sq_120 'python3 -c "print(120**2)"'
abbr -a py_math_sq_121 'python3 -c "print(121**2)"'
abbr -a py_math_sq_122 'python3 -c "print(122**2)"'
abbr -a py_math_sq_123 'python3 -c "print(123**2)"'
abbr -a py_math_sq_124 'python3 -c "print(124**2)"'
abbr -a py_math_sq_125 'python3 -c "print(125**2)"'
abbr -a py_math_sq_126 'python3 -c "print(126**2)"'
abbr -a py_math_sq_127 'python3 -c "print(127**2)"'
abbr -a py_math_sq_128 'python3 -c "print(128**2)"'
abbr -a py_math_sq_129 'python3 -c "print(129**2)"'
abbr -a py_math_sq_12 'python3 -c "print(12**2)"'
abbr -a py_math_sq_130 'python3 -c "print(130**2)"'
abbr -a py_math_sq_131 'python3 -c "print(131**2)"'
abbr -a py_math_sq_132 'python3 -c "print(132**2)"'
abbr -a py_math_sq_133 'python3 -c "print(133**2)"'
abbr -a py_math_sq_134 'python3 -c "print(134**2)"'
abbr -a py_math_sq_135 'python3 -c "print(135**2)"'
abbr -a py_math_sq_136 'python3 -c "print(136**2)"'
abbr -a py_math_sq_137 'python3 -c "print(137**2)"'
abbr -a py_math_sq_138 'python3 -c "print(138**2)"'
abbr -a py_math_sq_139 'python3 -c "print(139**2)"'
abbr -a py_math_sq_13 'python3 -c "print(13**2)"'
abbr -a py_math_sq_140 'python3 -c "print(140**2)"'
abbr -a py_math_sq_141 'python3 -c "print(141**2)"'
abbr -a py_math_sq_142 'python3 -c "print(142**2)"'
abbr -a py_math_sq_143 'python3 -c "print(143**2)"'
abbr -a py_math_sq_144 'python3 -c "print(144**2)"'
abbr -a py_math_sq_145 'python3 -c "print(145**2)"'
abbr -a py_math_sq_146 'python3 -c "print(146**2)"'
abbr -a py_math_sq_147 'python3 -c "print(147**2)"'
abbr -a py_math_sq_148 'python3 -c "print(148**2)"'
abbr -a py_math_sq_149 'python3 -c "print(149**2)"'
abbr -a py_math_sq_14 'python3 -c "print(14**2)"'
abbr -a py_math_sq_150 'python3 -c "print(150**2)"'
abbr -a py_math_sq_151 'python3 -c "print(151**2)"'
abbr -a py_math_sq_152 'python3 -c "print(152**2)"'
abbr -a py_math_sq_15 'python3 -c "print(15**2)"'
abbr -a py_math_sq_16 'python3 -c "print(16**2)"'
abbr -a py_math_sq_17 'python3 -c "print(17**2)"'
abbr -a py_math_sq_18 'python3 -c "print(18**2)"'
abbr -a py_math_sq_19 'python3 -c "print(19**2)"'
abbr -a py_math_sq_1 'python3 -c "print(1**2)"'
abbr -a py_math_sq_20 'python3 -c "print(20**2)"'
abbr -a py_math_sq_21 'python3 -c "print(21**2)"'
abbr -a py_math_sq_22 'python3 -c "print(22**2)"'
abbr -a py_math_sq_23 'python3 -c "print(23**2)"'
abbr -a py_math_sq_24 'python3 -c "print(24**2)"'
abbr -a py_math_sq_25 'python3 -c "print(25**2)"'
abbr -a py_math_sq_26 'python3 -c "print(26**2)"'
abbr -a py_math_sq_27 'python3 -c "print(27**2)"'
abbr -a py_math_sq_28 'python3 -c "print(28**2)"'
abbr -a py_math_sq_29 'python3 -c "print(29**2)"'
abbr -a py_math_sq_2 'python3 -c "print(2**2)"'
abbr -a py_math_sq_30 'python3 -c "print(30**2)"'
abbr -a py_math_sq_31 'python3 -c "print(31**2)"'
abbr -a py_math_sq_32 'python3 -c "print(32**2)"'
abbr -a py_math_sq_33 'python3 -c "print(33**2)"'
abbr -a py_math_sq_34 'python3 -c "print(34**2)"'
abbr -a py_math_sq_35 'python3 -c "print(35**2)"'
abbr -a py_math_sq_36 'python3 -c "print(36**2)"'
abbr -a py_math_sq_37 'python3 -c "print(37**2)"'
abbr -a py_math_sq_38 'python3 -c "print(38**2)"'
abbr -a py_math_sq_39 'python3 -c "print(39**2)"'
abbr -a py_math_sq_3 'python3 -c "print(3**2)"'
abbr -a py_math_sq_40 'python3 -c "print(40**2)"'
abbr -a py_math_sq_41 'python3 -c "print(41**2)"'
abbr -a py_math_sq_42 'python3 -c "print(42**2)"'
abbr -a py_math_sq_43 'python3 -c "print(43**2)"'
abbr -a py_math_sq_44 'python3 -c "print(44**2)"'
abbr -a py_math_sq_45 'python3 -c "print(45**2)"'
abbr -a py_math_sq_46 'python3 -c "print(46**2)"'
abbr -a py_math_sq_47 'python3 -c "print(47**2)"'
abbr -a py_math_sq_48 'python3 -c "print(48**2)"'
abbr -a py_math_sq_49 'python3 -c "print(49**2)"'
abbr -a py_math_sq_4 'python3 -c "print(4**2)"'
abbr -a py_math_sq_50 'python3 -c "print(50**2)"'
abbr -a py_math_sq_51 'python3 -c "print(51**2)"'
abbr -a py_math_sq_52 'python3 -c "print(52**2)"'
abbr -a py_math_sq_53 'python3 -c "print(53**2)"'
abbr -a py_math_sq_54 'python3 -c "print(54**2)"'
abbr -a py_math_sq_55 'python3 -c "print(55**2)"'
abbr -a py_math_sq_56 'python3 -c "print(56**2)"'
abbr -a py_math_sq_57 'python3 -c "print(57**2)"'
abbr -a py_math_sq_58 'python3 -c "print(58**2)"'
abbr -a py_math_sq_59 'python3 -c "print(59**2)"'
abbr -a py_math_sq_5 'python3 -c "print(5**2)"'
abbr -a py_math_sq_60 'python3 -c "print(60**2)"'
abbr -a py_math_sq_61 'python3 -c "print(61**2)"'
abbr -a py_math_sq_62 'python3 -c "print(62**2)"'
abbr -a py_math_sq_63 'python3 -c "print(63**2)"'
abbr -a py_math_sq_64 'python3 -c "print(64**2)"'
abbr -a py_math_sq_65 'python3 -c "print(65**2)"'
abbr -a py_math_sq_66 'python3 -c "print(66**2)"'
abbr -a py_math_sq_67 'python3 -c "print(67**2)"'
abbr -a py_math_sq_68 'python3 -c "print(68**2)"'
abbr -a py_math_sq_69 'python3 -c "print(69**2)"'
abbr -a py_math_sq_6 'python3 -c "print(6**2)"'
abbr -a py_math_sq_70 'python3 -c "print(70**2)"'
abbr -a py_math_sq_71 'python3 -c "print(71**2)"'
abbr -a py_math_sq_72 'python3 -c "print(72**2)"'
abbr -a py_math_sq_73 'python3 -c "print(73**2)"'
abbr -a py_math_sq_74 'python3 -c "print(74**2)"'
abbr -a py_math_sq_75 'python3 -c "print(75**2)"'
abbr -a py_math_sq_76 'python3 -c "print(76**2)"'
abbr -a py_math_sq_77 'python3 -c "print(77**2)"'
abbr -a py_math_sq_78 'python3 -c "print(78**2)"'
abbr -a py_math_sq_79 'python3 -c "print(79**2)"'
abbr -a py_math_sq_7 'python3 -c "print(7**2)"'
abbr -a py_math_sq_80 'python3 -c "print(80**2)"'
abbr -a py_math_sq_81 'python3 -c "print(81**2)"'
abbr -a py_math_sq_82 'python3 -c "print(82**2)"'
abbr -a py_math_sq_83 'python3 -c "print(83**2)"'
abbr -a py_math_sq_84 'python3 -c "print(84**2)"'
abbr -a py_math_sq_85 'python3 -c "print(85**2)"'
abbr -a py_math_sq_86 'python3 -c "print(86**2)"'
abbr -a py_math_sq_87 'python3 -c "print(87**2)"'
abbr -a py_math_sq_88 'python3 -c "print(88**2)"'
abbr -a py_math_sq_89 'python3 -c "print(89**2)"'
abbr -a py_math_sq_8 'python3 -c "print(8**2)"'
abbr -a py_math_sq_90 'python3 -c "print(90**2)"'
abbr -a py_math_sq_91 'python3 -c "print(91**2)"'
abbr -a py_math_sq_92 'python3 -c "print(92**2)"'
abbr -a py_math_sq_93 'python3 -c "print(93**2)"'
abbr -a py_math_sq_94 'python3 -c "print(94**2)"'
abbr -a py_math_sq_95 'python3 -c "print(95**2)"'
abbr -a py_math_sq_96 'python3 -c "print(96**2)"'
abbr -a py_math_sq_97 'python3 -c "print(97**2)"'
abbr -a py_math_sq_98 'python3 -c "print(98**2)"'
abbr -a py_math_sq_99 'python3 -c "print(99**2)"'
abbr -a py_math_sq_9 'python3 -c "print(9**2)"'
abbr -a reload 'source ~/.config/fish/config.fish'
abbr -a rem
abbr -a rmf 'rm -rf'
abbr -a rsa 'rsync -a'
abbr -a rsf 'rsync -f'
abbr -a rsh 'rsync -h'
abbr -a rsi 'rsync -i'
abbr -a rsl 'rsync -l'
abbr -a rsn 'rsync -n'
abbr -a rsR 'rsync -R'
abbr -a rst 'rsync -t'
abbr -a rsu 'rsync -u'
abbr -a rsv 'rsync -v'
abbr -a sca 'scp -a'
abbr -a scf 'scp -f'
abbr -a sch 'scp -h'
abbr -a sci 'scp -i'
abbr -a scl 'scp -l'
abbr -a scn 'scp -n'
abbr -a scR 'scp -R'
abbr -a sct 'scp -t'
abbr -a scu 'scp -u'
abbr -a scv 'scp -v'
abbr -a se
abbr -a sea 'sed -a'
abbr -a sef 'sed -f'
abbr -a seh 'sed -h'
abbr -a sei 'sed -i'
abbr -a sel 'sed -l'
abbr -a sen 'sed -n'
abbr -a seR 'sed -R'
abbr -a serve3000 'python3 -m http.server 3000'
abbr -a serve8000 'python3 -m http.server 8000'
abbr -a serve8080 'python3 -m http.server 8080'
abbr -a set 'sed -t'
abbr -a seu 'sed -u'
abbr -a sev 'sed -v'
abbr -a sfc 'source ~/.config/fish/config.fish'
abbr -a slau 'slpkg autoremove'
abbr -a slch 'slpkg check'
abbr -a slcl 'slpkg clean'
abbr -a slin 'slpkg install'
abbr -a slli 'slpkg list'
abbr -a slre 'slpkg remove'
abbr -a slse 'slpkg search'
abbr -a slso 'slpkg sources'
abbr -a slup 'slpkg update'
abbr -a ssa 'ssh -a'
abbr -a ssf 'ssh -f'
abbr -a ssh 'ssh -h'
abbr -a ssi 'ssh -i'
abbr -a ssl 'ssh -l'
abbr -a ssn 'ssh -n'
abbr -a ssR 'ssh -R'
abbr -a sst 'ssh -t'
abbr -a ssu 'ssh -u'
abbr -a ssv 'ssh -v'
abbr -a sv 'sudo nvim'
abbr -a taa 'tar -a'
abbr -a taf 'tar -f'
abbr -a tah 'tar -h'
abbr -a tai 'tar -i'
abbr -a tal 'tar -l'
abbr -a tan 'tar -n'
abbr -a tap 'terraform apply'
abbr -a taR 'tar -R'
abbr -a tat 'tar -t'
abbr -a tau 'tar -u'
abbr -a tav 'tar -v'
abbr -a tco 'terraform console'
abbr -a tde 'terraform destroy'
abbr -a tfap 'terraform apply'
abbr -a tfco 'terraform console'
abbr -a tfde 'terraform destroy'
abbr -a tffm 'terraform fmt'
abbr -a tfgr 'terraform graph'
abbr -a tfim 'terraform import'
abbr -a tfin 'terraform init'
abbr -a tflo 'terraform login'
abbr -a tfm 'terraform fmt'
abbr -a tfou 'terraform output'
abbr -a tfpl 'terraform plan'
abbr -a tfre 'terraform refresh'
abbr -a tfsh 'terraform show'
abbr -a tfst 'terraform state'
abbr -a tfva 'terraform validate'
abbr -a tfwo 'terraform workspace'
abbr -a tgr 'terraform graph'
abbr -a tim 'terraform import'
abbr -a tin 'terraform init'
abbr -a tlo 'terraform login'
abbr -a toa 'top -a'
abbr -a tof 'top -f'
abbr -a toh 'top -h'
abbr -a toi 'top -i'
abbr -a tol 'top -l'
abbr -a ton 'top -n'
abbr -a toR 'top -R'
abbr -a tot 'top -t'
abbr -a tou 'terraform output'
abbr -a tou 'top -u'
abbr -a tov 'top -v'
abbr -a tpl 'terraform plan'
abbr -a tre 'terraform refresh'
abbr -a tsh 'terraform show'
abbr -a tst 'terraform state'
abbr -a tva 'terraform validate'
abbr -a two 'terraform workspace'
abbr -a update 'sudo apt update && sudo apt upgrade -y'
abbr -a upgrade 'update'
abbr -a vact 'source .venv/bin/activate.fish'
abbr -a venv 'python3 -m venv'
abbr -a v 'nvim'
abbr -a wga 'wget -a'
abbr -a wgf 'wget -f'
abbr -a wgh 'wget -h'
abbr -a wgi 'wget -i'
abbr -a wgl 'wget -l'
abbr -a wgn 'wget -n'
abbr -a wgR 'wget -R'
abbr -a wgt 'wget -t'
abbr -a wgu 'wget -u'
abbr -a wgv 'wget -v'
abbr -a wtrc 'curl -s wttr.in?format=3'
abbr -a wtr 'curl -s wttr.in'
abbr -a xbpsau 'xbps-install autoremove'
abbr -a xbpsch 'xbps-install check'
abbr -a xbpscl 'xbps-install clean'
abbr -a xbpsin 'xbps-install install'
abbr -a xbpsli 'xbps-install list'
abbr -a xbpsre 'xbps-install remove'
abbr -a xbpsse 'xbps-install search'
abbr -a xbpsso 'xbps-install sources'
abbr -a xbpsup 'xbps-install update'
abbr -a yaau 'yay autoremove'
abbr -a yach 'yay check'
abbr -a yacl 'yay clean'
abbr -a yain 'yay install'
abbr -a yali 'yay list'
abbr -a yare 'yay remove'
abbr -a yase 'yay search'
abbr -a yaso 'yay sources'
abbr -a yaup 'yay update'
abbr -a yuau 'yum autoremove'
abbr -a yuch 'yum check'
abbr -a yucl 'yum clean'
abbr -a yuin 'yum install'
abbr -a yuli 'yum list'
abbr -a yure 'yum remove'
abbr -a yuse 'yum search'
abbr -a yuso 'yum sources'
abbr -a yuup 'yum update'
abbr -a zconf '$EDITOR ~/.zshrc'
abbr -a zia 'zip -a'
abbr -a zif 'zip -f'
abbr -a zih 'zip -h'
abbr -a zii 'zip -i'
abbr -a zil 'zip -l'
abbr -a zin 'zip -n'
abbr -a ziR 'zip -R'
abbr -a zit 'zip -t'
abbr -a ziu 'zip -u'
abbr -a ziv 'zip -v'
abbr -a zyau 'zypper autoremove'
abbr -a zych 'zypper check'
abbr -a zycl 'zypper clean'
abbr -a zyin 'zypper install'
abbr -a zyli 'zypper list'
abbr -a zyre 'zypper remove'
abbr -a zyse 'zypper search'
abbr -a zyso 'zypper sources'
abbr -a zyup 'zypper update'
