"$schema" = 'https://starship.rs/config-schema.json'
format = """[](nord_polar_night_2)$os$hostname${custom.root}${custom.user}[](bg:nord_polar_night_1 fg:nord_polar_night_2)$directory[](bg:nord_polar_night_2 fg:nord_polar_night_1)($git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$hg_state$fossil_branch$vcsh$pijul_channel)[](bg:nord_polar_night_1 fg:nord_polar_night_2)($package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$gradle$guix_shell$haskell$haxe$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$raku$rlang$ruby$rust$scala$solidity$swift$terraform$typst$vlang$vagrant$zig$buf$nix_shell$conda$solana$meson$spack$crystal)[](bg:nord_polar_night_2 fg:nord_polar_night_1)($docker_context$kubernetes$aws$gcloud$openstack$azure$direnv$mise$env_var$singularity$container$netns)[](bg:nord_polar_night_3 fg:nord_polar_night_2)(${custom.cpu_load}${custom.shell_mem}${custom.disk_free}${custom.uptime}$sudo$shlvl$memory_usage$localip$shell$time$battery)[](nord_polar_night_3)$line_break$character"""
right_format = """$cmd_duration$jobs"""
add_newline = true
palette = "nord"

[palettes.nord]
nord_polar_night_0 = "#2E3440"
nord_polar_night_1 = "#3B4252"
nord_polar_night_2 = "#434C5E"
nord_polar_night_3 = "#4C566A"
nord_snow_storm_0 = "#D8DEE9"
nord_snow_storm_1 = "#E5E9F0"
nord_snow_storm_2 = "#ECEFF4"
nord_frost_cyan = "#8FBCBB"
nord_frost_blue = "#88C0D0"
nord_frost_arctic = "#81A1C1"
nord_frost_deep = "#5E81AC"
nord_aurora_red = "#BF616A"
nord_aurora_orange = "#D08770"
nord_aurora_yellow = "#EBCB8B"
nord_aurora_green = "#A3BE8C"
nord_aurora_purple = "#B48EAD"

[character]
success_symbol = "[󰄬 ](bold nord_aurora_green)"
error_symbol = "[󰅙 ](bold nord_aurora_red)"
vicmd_symbol = "[󰘳 ](bold nord_frost_blue)"

[os]
disabled = false
style = "bg:nord_polar_night_2 fg:nord_snow_storm_2"
format = "[$symbol]($style)"

[os.symbols]
Macos = " "

[directory]
style = "bg:nord_polar_night_1 fg:nord_frost_arctic"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"
home_symbol = "󱂵 "

[hostname]
ssh_only = false
format = "[$ssh_symbol$hostname]($style) "
style = "bg:nord_polar_night_2 fg:nord_aurora_yellow"
ssh_symbol = "󰣀 "

[git_branch]
symbol = " "
style = "bg:nord_polar_night_2 fg:nord_aurora_purple"
format = "[$symbol$branch]($style)"

[git_status]
style = "bg:nord_polar_night_2 fg:nord_aurora_red"
format = "[$all_status$ahead_behind]($style)"

[custom.cpu_load]
command = "cut -d' ' -f1 /proc/loadavg"
style = "bg:nord_polar_night_3 fg:nord_aurora_yellow"
format = "[ 󰻠 $output ]($style)"
os = "linux"

[custom.shell_mem]
command = "ps -o rss= -p $$ | awk '{printf \"%.1fMi\", $1/1024}'"
style = "bg:nord_polar_night_3 fg:nord_frost_blue"
format = "[ 󰍛 $output ]($style)"

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
format = "[ $symbol$percentage ]($style)"

[aws]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[azure]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[bun]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[c]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[cmake]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[cobol]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[crystal]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[daml]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[dart]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[deno]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[dotnet]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[elixir]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[elm]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[erlang]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[fennel]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[gcloud]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[golang]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[gradle]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[guix_shell]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[haskell]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[haxe]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[helm]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[java]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[julia]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[kotlin]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[lua]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[meson]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[nim]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[nix_shell]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[nodejs]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[ocaml]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[opa]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[perl]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[php]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[pulumi]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[purescript]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[python]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[raku]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[rlang]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[ruby]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[rust]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[scala]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"


[solidity]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[spack]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[swift]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[terraform]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[typst]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[vlang]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[vagrant]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

[zig]
symbol = "◆ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"

