"$schema" = 'https://starship.rs/config-schema.json'
format = """
[](nord_polar_night_2)\
$os${custom.root}${custom.user}\
[](bg:nord_polar_night_1 fg:nord_polar_night_2)\
$directory\
[](bg:nord_polar_night_2 fg:nord_polar_night_1)\
($git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$hg_state$fossil_branch$vcsh$pijul_channel)\
[](bg:nord_polar_night_1 fg:nord_polar_night_2)\
($package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$gradle$guix_shell$haskell$haxe$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$pure$python$raku$rlang$red$ruby$rust$scala$solidity$swift$terraform$typst$vlang$vagrant$zig$buf$nix_shell$conda$solana$meson$spack$crystal)\
[](bg:nord_polar_night_2 fg:nord_polar_night_1)\
($docker_context$kubernetes$aws$gcloud$openstack$azure$direnv$mise$env_var$singularity$container$netns)\
[](bg:nord_polar_night_3 fg:nord_polar_night_2)\
(${custom.cpu_load}${custom.shell_mem}${custom.disk_free}${custom.uptime}$sudo$shlvl$memory_usage$localip$shell$time$battery)\
[](nord_polar_night_3)\
$line_break\
$character"""
right_format = """$cmd_duration$jobs"""
add_newline = true
palette = "nord"
command_timeout = 5000
[palettes.nord]
nord_polar_night_0 = "#2e3440"
nord_polar_night_1 = "#3b4252"
nord_polar_night_2 = "#434c5e"
nord_polar_night_3 = "#4c566a"
nord_snow_storm_0 = "#d8dee9"
nord_snow_storm_1 = "#e5e9f0"
nord_snow_storm_2 = "#eceff4"
nord_frost_mint = "#8fbcbb"
nord_frost_blue = "#88c0d0"
nord_frost_arctic = "#81a1c1"
nord_frost_deep = "#5e81ac"
nord_aurora_red = "#bf616a"
nord_aurora_orange = "#d08770"
nord_aurora_yellow = "#ebcb8b"
nord_aurora_green = "#a3be8c"
nord_aurora_purple = "#b48ead"
[os]
disabled = false
style = "bg:nord_polar_night_2 fg:nord_snow_storm_2"
[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞇 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
Oracle = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
[custom.root]
command = "echo ' ROOT! '"
when = "test $(id -u) -eq 0"
style = "bg:nord_polar_night_2 fg:nord_aurora_red bold"
format = "[$output]($style)"
[custom.user]
command = "echo \"$USER\""
when = "true"
style = "bg:nord_polar_night_2 fg:nord_snow_storm_2"
format = "[ 😎 $output ]($style)"
[directory]
style = "bg:nord_polar_night_1 fg:nord_aurora_orange bold"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 1
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󰇚 "
"Music" = "󰎄 "
"Pictures" = "󰉏 "
"Videos" = "󰕧 "
"Projects" = "󱂵 "
"work" = "󰑴 "
"src" = " "
"lib" = "󰆧 "
"test" = "🧪 "
"bin" = "󰲒 "
"include" = "󰅴 "
"venv" = "🐍 "
".git" = "󰊢 "
"node_modules" = " "
"target" = "🎯 "
"build" = "🏗️ "
"dist" = "📦 "
"public" = "🌐 "
"private" = "🔒 "
"config" = "⚙️ "
"scripts" = "📜 "
"data" = "📊 "
"assets" = "🎨 "
"docs" = "📚 "
"tests" = "🧪 "
"tools" = "🛠️ "
"internal" = "🔒 "
"pkg" = "📦 "
"cmd" = "󰘳 "
"api" = "🔌 "
"web" = "🕸️ "
[git_branch]
symbol = ""
style = "bg:nord_polar_night_2 fg:nord_aurora_green"
format = "[ $symbol $branch ]($style)"
[git_status]
style = "bg:nord_polar_night_2 fg:nord_aurora_red"
format = "[($all_status$ahead_behind )]($style)"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
[git_state]
style = "bg:nord_polar_night_2 fg:nord_aurora_yellow"
format = "[ \\($state( $progress_current/$progress_total)\\) ]($style)"
[git_metrics]
added_style = "bold blue"
deleted_style = "bold red"
disabled = false
[git_commit]
commit_hash_length = 7
style = "bg:nord_polar_night_2 fg:nord_snow_storm_0"
format = "[ @$hash ]($style)"
[package]
symbol = "󰏗 "
style = "bg:nord_polar_night_1 fg:nord_snow_storm_0"
format = "[ via $symbol$version ]($style)"
[c]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[cmake]
symbol = "△ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[cobol]
symbol = "⚙️ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[daml]
symbol = "λ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[dart]
symbol = "🎯 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[deno]
symbol = "🦕 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[dotnet]
symbol = "󰪮 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[elixir]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_aurora_purple"
format = "[ via $symbol$version ]($style)"
[elm]
symbol = "🌳 "
style = "bg:nord_polar_night_1 fg:nord_aurora_green"
format = "[ via $symbol$version ]($style)"
[erlang]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_aurora_red"
format = "[ via $symbol$version ]($style)"
[fennel]
symbol = "果 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[golang]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_mint"
format = "[ via $symbol$version ]($style)"
[gradle]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[guix_shell]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[haskell]
symbol = "λ "
style = "bg:nord_polar_night_1 fg:nord_aurora_purple"
format = "[ via $symbol$version ]($style)"
[haxe]
symbol = "⌘ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[helm]
symbol = "⎈ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[java]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_aurora_red"
format = "[ via $symbol$version ]($style)"
[julia]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[kotlin]
symbol = "󱈙 "
style = "bg:nord_polar_night_1 fg:nord_aurora_purple"
format = "[ via $symbol$version ]($style)"
[lua]
symbol = "🌙 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[nim]
symbol = "👑 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[nodejs]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_aurora_green"
format = "[ via $symbol$version ]($style)"
[ocaml]
symbol = "🐫 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[opa]
symbol = "OPA "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[perl]
symbol = "🐪 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[php]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_deep"
format = "[ via $symbol$version ]($style)"
[pulumi]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[pure]
symbol = "λ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[python]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_aurora_yellow"
format = "[ via $symbol$version ]($style)"
[raku]
symbol = "🦋 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[rlang]
symbol = "R "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[red]
symbol = "🛑 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[ruby]
symbol = "💎 "
style = "bg:nord_polar_night_1 fg:nord_aurora_red"
format = "[ via $symbol$version ]($style)"
[rust]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_aurora_orange"
format = "[ via $symbol$version ]($style)"
[scala]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[solidity]
symbol = "𝕊 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[swift]
symbol = "🍎 "
style = "bg:nord_polar_night_1 fg:nord_aurora_orange"
format = "[ via $symbol$version ]($style)"
[terraform]
symbol = "󱁢 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[typst]
symbol = "T "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[vlang]
symbol = "V "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[vagrant]
symbol = "⍱ "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[zig]
symbol = "⚡ "
style = "bg:nord_polar_night_1 fg:nord_aurora_yellow"
format = "[ via $symbol$version ]($style)"
[buf]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[nix_shell]
symbol = "❄️  "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$state ]($style)"
[conda]
symbol = " "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$environment ]($style)"
[solana]
symbol = "󱥠 "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[meson]
symbol = "M "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[spack]
symbol = "Sp "
style = "bg:nord_polar_night_1 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[crystal]
symbol = "💎 "
style = "bg:nord_polar_night_1 fg:nord_aurora_red"
format = "[ via $symbol$version ]($style)"
[docker_context]
symbol = " "
style = "bg:nord_polar_night_2 fg:nord_frost_blue"
format = "[ via $symbol$context ]($style)"
[kubernetes]
symbol = "󱃾 "
style = "bg:nord_polar_night_2 fg:nord_aurora_purple"
format = "[ via $symbol$context ]($style)"
[aws]
symbol = "󰸏 "
style = "bg:nord_polar_night_2 fg:nord_aurora_orange"
format = "[ via $symbol$profile(\\($region\\)) ]($style)"
[gcloud]
symbol = "☁️  "
style = "bg:nord_polar_night_2 fg:nord_frost_blue"
format = "[ via $symbol$project ]($style)"
[openstack]
symbol = " OpenStack "
style = "bg:nord_polar_night_2 fg:nord_frost_blue"
format = "[ via $symbol$project ]($style)"
[azure]
symbol = " Azure "
style = "bg:nord_polar_night_2 fg:nord_frost_blue"
format = "[ via $symbol$subscription ]($style)"
[direnv]
symbol = "󰉓 "
style = "bg:nord_polar_night_2 fg:nord_aurora_yellow"
format = "[ $symbol$allowed ]($style)"
[mise]
symbol = "󱗼 "
style = "bg:nord_polar_night_2 fg:nord_frost_blue"
format = "[ via $symbol$version ]($style)"
[env_var]
variable = "STARSHIP_SHELL"
style = "bg:nord_polar_night_2 fg:nord_snow_storm_0"
format = "[ via $env_value ]($style)"
[singularity]
symbol = " "
style = "bg:nord_polar_night_2 fg:nord_snow_storm_0"
format = "[ via $symbol$env ]($style)"
[container]
symbol = "⬢ "
style = "bg:nord_polar_night_2 fg:nord_snow_storm_0"
format = "[ via $symbol$name ]($style)"
[netns]
symbol = "󰩟 "
style = "bg:nord_polar_night_2 fg:nord_snow_storm_0"
format = "[ via $symbol$name ]($style)"
[custom.cpu_load]
command = "top -bn1 | grep 'Cpu(s)' | awk '{print $2}'"
when = "test $(uname) = Linux"
style = "bg:nord_polar_night_3 fg:nord_aurora_orange"
format = "[ 󰻠 $output% ]($style)"
disabled = false
[custom.shell_mem]
command = "free -h | awk '/^Mem:/ {print $3 \"/\" $2}'"
when = "test $(uname) = Linux"
style = "bg:nord_polar_night_3 fg:nord_frost_arctic"
format = "[ 󰍛 $output ]($style)"
disabled = false
[custom.disk_free]
command = "df -h / | awk 'NR==2 {print $4}'"
when = "true"
style = "bg:nord_polar_night_3 fg:nord_frost_blue"
format = "[ 󰋊 $output ]($style)"
disabled = false
[custom.uptime]
command = "uptime -p | sed 's/up //'"
when = "true"
style = "bg:nord_polar_night_3 fg:nord_snow_storm_0"
format = "[ 󰅐 $output ]($style)"
disabled = false
[shell]
fish_indicator = "󰈺 fish"
bash_indicator = " bash"
zsh_indicator = "󱆃 zsh"
style = "bg:nord_polar_night_3 fg:nord_snow_storm_0"
format = "[ via $indicator ]($style)"
disabled = false
[time]
disabled = false
time_format = "%l:%M:%S %p"
use_12hr = true
style = "bg:nord_polar_night_3 fg:nord_snow_storm_2"
format = '[  $time ]($style)'
[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
format = '[ $symbol$percentage ](bg:nord_polar_night_3 fg:nord_snow_storm_2)'
disabled = false
[[battery.display]]
threshold = 10
style = "bg:nord_polar_night_3 fg:nord_aurora_red"
[[battery.display]]
threshold = 30
style = "bg:nord_polar_night_3 fg:nord_aurora_yellow"
[character]
success_symbol = "[❯](bold nord_aurora_green)"
error_symbol = "[❯](bold nord_aurora_red)"
[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "bold nord_aurora_yellow"
[sudo]
symbol = "󰰓 "
style = "bg:nord_polar_night_3 fg:nord_aurora_red"
format = "[ $symbol]($style)"
disabled = false
[shlvl]
symbol = "↕ "
style = "bg:nord_polar_night_3 fg:nord_aurora_purple"
format = "[ $symbol$shlvl ]($style)"
disabled = false
threshold = 2
[memory_usage]
symbol = "󰍛 "
style = "bg:nord_polar_night_3 fg:nord_frost_arctic"
format = "[ $symbol$ram ]($style)"
disabled = false
threshold = 0
[localip]
ssh_only = true
style = "bg:nord_polar_night_3 fg:nord_snow_storm_0"
format = "[ 󰩟 $localip ]($style)"
disabled = false
[hg_branch]
symbol = ""
style = "bg:nord_polar_night_2 fg:nord_aurora_green"
format = "[ $symbol $branch ]($style)"
[hg_state]
style = "bg:nord_polar_night_2 fg:nord_aurora_red"
format = "[ \\($state( $progress_current/$progress_total)\\) ]($style)"
[fossil_branch]
symbol = ""
style = "bg:nord_polar_night_2 fg:nord_aurora_green"
format = "[ on $symbol $branch ]($style)"
[vcsh]
symbol = ""
style = "bg:nord_polar_night_2 fg:nord_aurora_green"
format = "[ on $symbol $repo ]($style)"
[pijul_channel]
symbol = ""
style = "bg:nord_polar_night_2 fg:nord_aurora_green"
format = "[ on $symbol $channel ]($style)"
[hostname]
ssh_only = false
style = "bold muted"
format = "[$hostname]($style) "
disabled = false
[username]
show_always = true
style_user = "bold nord_frost_arctic"
style_root = "bold nord_aurora_red"
format = "[$user]($style) "
disabled = false
[status]
disabled = false
format = '[\[$status\]]($style) '
[jobs]
symbol = "󰒋 "
style = "bold nord_aurora_yellow"
format = "[$symbol$number]($style) "
[aws.region_aliases]
us-east-1 = "va"
us-west-2 = "or"
af-south-1 = "cp"
[battery.display.state]
charging = "⚡"
discharging = "󰂃"
[c.commands]
cc = ["cc", "-v"]
gcc = ["gcc", "-v"]
clang = ["clang", "-v"]
[container.commands]
docker = ["docker", "ps"]
podman = ["podman", "ps"]
[crystal.commands]
crystal = ["crystal", "-v"]
[dart.commands]
dart = ["dart", "--version"]
[deno.commands]
deno = ["deno", "--version"]
[docker_context.commands]
docker = ["docker", "context", "ls"]
[dotnet.commands]
dotnet = ["dotnet", "--version"]
[elixir.commands]
elixir = ["elixir", "-v"]
[elm.commands]
elm = ["elm", "--version"]
[erlang.commands]
erl = ["erl", "-version"]
[fennel.commands]
fennel = ["fennel", "-v"]
[fossil_branch.commands]
fossil = ["fossil", "branch", "current"]
[gcloud.commands]
gcloud = ["gcloud", "--version"]
[golang.commands]
go = ["go", "version"]
[gradle.commands]
gradle = ["gradle", "-v"]
[guix_shell.commands]
guix = ["guix", "--version"]
[haskell.commands]
ghc = ["ghc", "--version"]
[haxe.commands]
haxe = ["haxe", "-version"]
[helm.commands]
helm = ["helm", "version"]
[hg_branch.commands]
hg = ["hg", "branch"]
[java.commands]
java = ["java", "-version"]
[julia.commands]
julia = ["julia", "-v"]
[kotlin.commands]
kotlin = ["kotlin", "-version"]
[kubernetes.commands]
kubectl = ["kubectl", "version", "--client"]
[lua.commands]
lua = ["lua", "-v"]
[meson.commands]
meson = ["meson", "--version"]
[mise.commands]
mise = ["mise", "--version"]
[nim.commands]
nim = ["nim", "-v"]
[nix_shell.commands]
nix-shell = ["nix-shell", "--version"]
[nodejs.commands]
node = ["node", "-v"]
[ocaml.commands]
ocaml = ["ocaml", "-version"]
[opa.commands]
opa = ["opa", "version"]
[openstack.commands]
openstack = ["openstack", "--version"]
[perl.commands]
perl = ["perl", "-v"]
[php.commands]
php = ["php", "-v"]
[pijul_channel.commands]
pijul = ["pijul", "channel"]
[pulumi.commands]
pulumi = ["pulumi", "version"]
[pure.commands]
pure = ["pure", "-v"]
[python.commands]
python = ["python", "--version"]
python3 = ["python3", "--version"]
[raku.commands]
raku = ["raku", "-v"]
[red.commands]
red = ["red", "-v"]
[rlang.commands]
R = ["R", "--version"]
[ruby.commands]
ruby = ["ruby", "-v"]
[rust.commands]
rustc = ["rustc", "--version"]
[scala.commands]
scala = ["scala", "-version"]
[singularity.commands]
singularity = ["singularity", "--version"]
[solana.commands]
solana = ["solana", "--version"]
[solidity.commands]
solc = ["solc", "--version"]
[spack.commands]
spack = ["spack", "--version"]
[swift.commands]
swift = ["swift", "--version"]
[terraform.commands]
terraform = ["terraform", "version"]
[typst.commands]
typst = ["typst", "--version"]
[vagrant.commands]
vagrant = ["vagrant", "--version"]
[vcsh.commands]
vcsh = ["vcsh", "--version"]
[vlang.commands]
v = ["v", "-v"]
[zig.commands]
zig = ["zig", "version"]
