#!/usr/bin/env bash
alias cat='bat --paging=never 2>/dev/null || cat'
alias c='clear'
alias .....='cd ../../../..'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias cls='clear'
alias coinflip='awk "BEGIN{srand();print rand()<0.5?\"heads\":\"tails\"}"'
alias dc='docker compose'
alias d='docker'
alias dfh='df -h'
alias di='docker images'
alias dotfiles='cd "$DOTFILES_DIR"'
alias dots='cd "$DOTFILES_DIR"'
alias dotst='git -C "$DOTFILES_DIR" status --short --branch'
alias dpsa='docker ps -a'
alias dps='docker ps'
alias duh='du -sh'
alias edots='$EDITOR "$DOTFILES_DIR"'
alias focus='printf "\033c" && date +"%F %T"'
alias freeh='free -h'
alias gaa='git add -A'
alias ga='git add'
alias gb='git branch'
alias gca='git commit --amend'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch --all --prune'
alias g='git'
alias gl='git log --oneline --decorate --graph --all -30'
alias gpf='git push --force-with-lease'
alias gp='git push'
alias gpl='git pull --rebase --autostash'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grep='rg 2>/dev/null || grep'
alias gs='git status --short --branch'
alias gsp='git stash pop'
alias gst='git stash push -u'
alias gsw='git switch'
alias h='history'
alias home='cd ~'
alias j='jobs -l'
alias kctx='kubectl config current-context'
alias kgp='kubectl get pods'
alias kgs='kubectl get svc'
alias k='kubectl'
alias la='eza -AGa --icons=auto 2>/dev/null || ls -a'
alias ll='eza -lah --icons=auto --group-directories-first 2>/dev/null || ls -lah'
alias ls='eza --icons=auto --group-directories-first 2>/dev/null || ls'
alias lt='eza --tree --level=2 --icons=auto 2>/dev/null || find . -maxdepth 2 -print'
alias matrix='printf "\01101000\01100101\01101100\01101100\01101111\n"'
alias mkdirp='mkdir -p'
alias myip='curl -fsSL https://ifconfig.me 2>/dev/null || curl -fsSL https://ipinfo.io/ip 2>/dev/null'
alias nd='npm run dev'
alias ni='npm install'
alias now='date +%F %T'
alias nr='npm run'
alias nt='npm test'
alias pathlines='printf "%s\n" ${PATH//:/\\n}'
alias pipup='python3 -m pip install --upgrade pip'
alias please='sudo'
alias ports='netstat -tulanp 2>/dev/null || ss -tulanp'
alias prune='git remote prune origin'
alias psg='ps aux | grep -i'
alias py='python3'
alias reload='exec "$SHELL" -l'
alias serve='python3 -m http.server'
alias shipit='git status --short && git push'
alias tfa='terraform apply'
alias tfi='terraform init'
alias tfp='terraform plan'
alias tf='terraform'
alias today='date +%F'
alias topcpu='ps aux --sort=-%cpu | head'
alias topmem='ps aux --sort=-%mem | head'
alias venv='python3 -m venv .venv'
alias weather='curl -fsSL wttr.in'
