animations {
  enabled = true

  bezier = fluide, 0.3, 0.0, 0.3, 1.0
  bezier = smoothOut, 0.36, 0, 0.66, -0.56
  bezier = smoothIn, 0.25, 0.1, 0.25, 1
  bezier = smoothWS, 0.25, 0.1, 0.25, 1
  bezier = spring, 0.05, 0.7, 0.1, 1.0
  bezier = bouncy, 0.05, 1.2, 0.1, 1.0

  animation = windows, 1, 6, spring, slide
  animation = windowsOut, 1, 5, smoothOut, slide
  animation = windowsMove, 1, 6, spring, slide
  animation = border, 1, 10, default
  animation = borderangle, 1, 25, default, once
  animation = fade, 1, 5, smoothIn
  animation = fadeDim, 1, 5, smoothIn
  animation = workspaces, 1, 7, smoothWS, slide
  animation = specialWorkspace, 1, 7, smoothWS, slide
}
