# Autostart — executed on Hyprland startup
exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = xdg-desktop-portal-hyprland
exec-once = nm-applet --indicator
exec-once = dunst
exec-once = newsflash
