-- =============================================================================
-- GPU / ENVIRONMENT VARIABLES
-- =============================================================================
-- These variables configure GPU drivers, Wayland backends, and app-specific
-- environment. They are typically auto-generated by the set-env script,
-- but can also be set manually for debugging or specific hardware setups.
-- =============================================================================

-- =============================================================================
-- GPU RENDERING
-- =============================================================================

-- Direct Rendering Manager device (primary GPU)
hl.env("AQ_DRM_DEVICES", "/dev/dri/card1")

-- Video acceleration driver (Intel = iHD, AMD = radeonsi, NVIDIA = nvidia)
hl.env("LIBVA_DRIVER_NAME", "iHD")

-- VDPAU driver (video playback acceleration)
hl.env("VDPAU_DRIVER", "va_gl")

-- =============================================================================
-- DESKTOP ENVIRONMENT
-- =============================================================================

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")

-- =============================================================================
-- APPLICATION BACKENDS
-- =============================================================================

-- GTK: Force Wayland backend
hl.env("GDK_BACKEND", "wayland")

-- Qt: Prefer Wayland, fallback to XCB
hl.env("QT_QPA_PLATFORM", "wayland;xcb")

-- Firefox/Thunderbird: Enable Wayland
hl.env("MOZ_ENABLE_WAYLAND", "1")

-- SDL2: Use Wayland backend
hl.env("SDL_VIDEODRIVER", "wayland")

-- Clutter: Use Wayland backend
hl.env("CLUTTER_BACKEND", "wayland")

-- =============================================================================
-- ADDITIONAL ENVIRONMENT VARIABLES
-- =============================================================================

-- Qt: Support both Wayland and XCB
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

-- Electron: Force Wayland
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- Java/Swing: Use Wayland (experimental)
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")

-- PipeWire: Set default node (usually not needed)
-- hl.env("PIPEWIRE_NODE", "")

-- NVIDIA specific (uncomment if using NVIDIA GPU)
-- hl.env("GBM_BACKEND", "nvidia-drm")
-- hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
-- hl.env("WLR_NO_HARDWARE_CURSORS", "1")
-- hl.env("WLR_RENDERER", "vulkan")

-- AMD specific (uncomment if using AMD GPU)
-- hl.env("RADV_PERFTEST", "ngg")
-- hl.env("ACO_DEBUG", "")

-- =============================================================================
-- NOTES
-- =============================================================================
-- To regenerate these variables:
--   ~/.local/share/dotfiles/hypr/scripts/set-env
--
-- To verify current environment:
--   env | grep -E '(WAYLAND|AQ_|LIBVA|MOZ_|QT_|GDK_)'
--
-- To debug GPU issues:
--   glxinfo | grep "OpenGL renderer"  (XWayland)
--   vdpauinfo                          (VDPAU)
--   vainfo                             (VA-API)
-- =============================================================================
