# Input configuration
input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options =
  kb_rules =

  follow_mouse = 2
  mouse_refocus = false

  touchpad {
    natural_scroll = true
    disable_while_typing = true
    tap-to-click = true
    drag_lock = true
    scroll_factor = 0.8
  }

  accel_profile = flat
  sensitivity = 0
}

gesture {
  workspace_swipe = true
  workspace_swipe_fingers = 3
  workspace_swipe_min_speed_to_force = 10
}
