# Window rules
windowrule = match:class pavucontrol, float on, center on
windowrule = match:class pavucontrol, size "60% 60%"
windowrule = match:class blueman-manager, float on
windowrule = match:class xdg-desktop-portal, float on
windowrule = match:title "^(Picture-in-Picture)$", float on, pin on
windowrule = match:class rofi, no_blur on, no_shadow on
windowrule = match:class Rofi, no_blur on, no_shadow on
windowrule = match:class xwaylandvideobridge, opacity 0.0 override 0.0 override, no_anim on, max_size "1 1"
windowrule = match:class waybar, no_blur on, no_shadow on, no_focus on, no_initial_focus on, stay_focused on
windowrule = match:class Waybar, no_blur on, no_shadow on, no_focus on, no_initial_focus on, stay_focused on
