# Workspace configuration
dwindle {
  preserve_split = true
  default_split_ratio = 1.5
  smart_split = false
  smart_resizing = true
  permanent_direction_override = true
}

master {
  new_status = slave
  mfact = 0.55
  orientation = center
  slave_count_for_center_master = 0
}

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  disable_splash_rendering = true
  animate_mouse_windowdragging = false
  enable_swallow = true
  swallow_regex = ^(kitty)$
  on_focus_under_fullscreen = 2
  initial_workspace_tracking = 2
  mouse_move_enables_dpms = true
  key_press_enables_dpms = false
  disable_autoreload = true
}

debug {
  vfr = true
  damage_tracking = 2
}

render {
  direct_scanout = true
}

xwayland {
  force_zero_scaling = true
}

